import { ReactiveTrapEffect } from './reactiveTypes';

export const TRAP_PRESETS: Record<string, ReactiveTrapEffect> = {
  spike_pit: {
    type: 'trap_damage',
    name: 'Fosso de Estacas Oculto',
    description: 'Um alçapão camuflado que se abre sob os pés, revelando estacas afiadas de ferro.',
    detectDC: 13,
    disarmDC: 14,
    saveStat: 'dex',
    saveDC: 13,
    damageDice: '2d10',
    damageType: 'Perfurante',
    conditionApplied: 'Caído',
    revealedToPlayers: false,
    isArmed: true,
    oneShot: true,
    soundEffect: 'trap_spike',
  },
  poison_dart: {
    type: 'trap_damage',
    name: 'Dardos Envenenados na Parede',
    description: 'Um fio quase invisível rente ao chão que dispara dardos embebidos em veneno de serpente.',
    detectDC: 14,
    disarmDC: 15,
    saveStat: 'con',
    saveDC: 13,
    damageDice: '1d4 + 2d6',
    damageType: 'Veneno',
    conditionApplied: 'Envenenado',
    revealedToPlayers: false,
    isArmed: true,
    oneShot: true,
    soundEffect: 'trap_poison',
  },
  fire_glyph: {
    type: 'trap_damage',
    name: 'Glifo Explosivo de Chamas',
    description: 'Uma runa mágica arcana inscrita no piso que explode em uma labareda ao ser pisada.',
    detectDC: 15,
    disarmDC: 16,
    saveStat: 'dex',
    saveDC: 15,
    damageDice: '5d8',
    damageType: 'Fogo',
    revealedToPlayers: false,
    isArmed: true,
    oneShot: true,
    soundEffect: 'trap_explosion',
  },
  sleep_gas: {
    type: 'trap_damage',
    name: 'Válvula de Gás Sonífero',
    description: 'Pisos de pressão que liberam um vapor adocicado e denso que induz ao sono.',
    detectDC: 13,
    disarmDC: 13,
    saveStat: 'con',
    saveDC: 13,
    damageDice: '0',
    damageType: 'Psíquico',
    conditionApplied: 'Inconsciente',
    revealedToPlayers: false,
    isArmed: true,
    oneShot: true,
    soundEffect: 'trap_poison',
  },
  scythe_blade: {
    type: 'trap_damage',
    name: 'Lâmina de Foice Pendular',
    description: 'Uma pesada lâmina curva de ferro que balança violentamente cortando o corredor.',
    detectDC: 14,
    disarmDC: 14,
    saveStat: 'dex',
    saveDC: 14,
    damageDice: '3d8',
    damageType: 'Cortante',
    revealedToPlayers: false,
    isArmed: true,
    oneShot: false, // Continua oscilando!
    soundEffect: 'trap_spike',
  },
  portcullis_plate: {
    type: 'pressure_plate',
    name: 'Placa de Pressão de Grade (Portcullis)',
    description: 'Uma placa de pedra no piso que aciona o mecanismo de descida de uma grade de ferro reforçada.',
    detectDC: 12,
    disarmDC: 13,
    targetId: 'portcullis_1',
    revealedToPlayers: false,
    isArmed: true,
    oneShot: true,
    soundEffect: 'gate_close',
  },
  grease_surface: {
    type: 'surface_hazard',
    name: 'Chão Coberto de Graxa Escorregadia',
    description: 'Uma superfície oleosa e escorregadia. Ao entrar na área, deve passar em salvaguarda ou cair de bruços.',
    detectDC: 10,
    disarmDC: 10,
    saveStat: 'dex',
    saveDC: 12,
    damageDice: '0',
    damageType: 'Contundente',
    conditionApplied: 'Caído',
    revealedToPlayers: true,
    isArmed: true,
    oneShot: false,
    soundEffect: 'trap_click',
  },
  boulder_trap: {
    type: 'trap_damage',
    name: 'Pedra Rolante Gigante',
    description: 'Uma esfera maciça de pedra que desaba de um compartimento superior rolando pelo corredor.',
    detectDC: 15,
    disarmDC: 15,
    saveStat: 'dex',
    saveDC: 15,
    damageDice: '4d10',
    damageType: 'Contundente',
    conditionApplied: 'Caído',
    revealedToPlayers: false,
    isArmed: true,
    oneShot: true,
    soundEffect: 'trap_explosion',
  },
};
