import { SRDItem } from './types';

export const BATCH_14_UNIQUES: SRDItem[] = [
  {
    id: 'chime-of-opening',
    name: 'Sino da Abertura',
    englishName: 'Chime of Opening',
    type: 'Item Mágico (Sino)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Um tubo de metal fino de 30cm oco. Você pode usar uma ação para tocá-lo apontando-o. O som emite uma vibração que destranca perfeitamente baús, algemas, portas e portões que estiverem trancados por magia ou mecânica mundana num raio de 6 metros. (Possui 10 usos, ao fim o sino racha e quebra para sempre).',
    value: '4.000 PO',
    weight: 1,
  },
  {
    id: 'iron-flask',
    name: 'Frasco de Ferro',
    englishName: 'Iron Flask',
    type: 'Item Mágico (Frasco)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: false,
    description: 'Um cântaro místico impenetrável de latão pesado runado. Usando uma Ação, você conjura e força magicamente com comando qualquer criatura extra-planar num raio a ser sugada pra dentro eterna e irrestrita se ela falhar no teste Sáb CD 17 (Ou prender aliados para cura e guarda). Se soltar a fera depois apontando o bico, a besta que sair te servirá passivamente amiga sob controle mental telepático por 1 Hora antes de virar neutra/hostil.',
    value: '80.000 PO',
    weight: 2,
  },
  {
    id: 'marvelous-pigments',
    name: 'Pigmentos Maravilhosos de Nolzur',
    englishName: 'Marvelous Pigments',
    type: 'Item Mágico (Material)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Um pote contendo 1d4 potes de tintas mágicas que misturam a realidade, com um pincel feito de cerdas finas divinas. Qualquer objeto bidimensional que pintar ou desenhar durante 10 minutos (porta, janela falsa, fosso, corda ou até tesouro falso) numa parede ou chão e fechar com o pigmento, magicamente toma pura e exata vida absoluta num autêntico sólido e denso objeto tridimensional que existirá perfeitamente real! Não desenha vidas reais e só recria 3 metros cúbicos.',
    value: '15.000 PO',
    weight: 1,
  },
  {
    id: 'talisman-of-pure-good',
    name: 'Talismã do Bem Puro',
    englishName: 'Talisman of Pure Good',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização por criatura de tendência Boa',
    description: 'Artefato clérigo paladino divino da luz absoluta celestial que destrói almas das trevas. Causa imenso Dano radiante mortífero divino (6d6 e 8d6) a qualquer ser Neutro/Mau que tocá-lo para tentar pegá-lo. Concede Vantagem global extra e Bônus passivo alto em feitiços. Acesso a habilidade absoluta gastando 1 Carga: Fenda de luz no chão se abre engolindo perigosos e divinos clérigos do Mal irrestritamente pro precipício infinito absoluto finalizador do fim!',
    value: '100.000 PO',
    weight: 1,
  },
  {
    id: 'talisman-of-ultimate-evil',
    name: 'Talismã do Mal Supremo',
    englishName: 'Talisman of Ultimate Evil',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização por criatura de tendência Má',
    description: 'A contraparte profana do artefato divino. Pedra negra de sangue cristalizado, amaldiçoa quem toca de bem puro desferindo fogo do abismo letal, e permite seu lorde do mal rachar solo focado abrindo rachaduras ácidas chamas do mundo infernal abaixo engolindo o paladino bondoso herói letal da luz para os infernos sem retorno (Se falhar a salvaguarda DC 20 alta e brutal).',
    value: '100.000 PO',
    weight: 1,
  },
  {
    id: 'robe-of-eyes',
    name: 'Robe dos Olhos',
    englishName: 'Robe of Eyes',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Vestimenta costurada coberta inteira por olhos bordados piscarem magicamente vivo abertos e iluminados em luz e na escuridão profunda. O portador terá Visão perfeita Darkvision (36 metros), vê pura mágica aura do Invisível letal nos éteres cósmicos próximos puros; pode observar lateralmente e nas costas para trás perfeitamente impedindo qualquer perigo de pegá-lo surpresa nas lutas.',
    value: '12.000 PO',
    weight: 1,
  },
  {
    id: 'dust-of-disappearance',
    name: 'Pó do Desaparecimento',
    englishName: 'Dust of Disappearance',
    type: 'Item Mágico (Pó)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Areia de vidro fino prateada invisível (Trazida em pacote). Quando lançar essa fina fuligem nos ares, todos na exata fumaça da nuvem absorvem sumindo e ficando irrestritamente invisíveis por 2d4 longos contínuos gloriosos limpos Minutos totais. Qualquer ataque de armas invisíveis finaliza e descobre o pó letal.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'dust-of-sneezing-and-choking',
    name: 'Pó do Espirro e Engasgo',
    englishName: 'Dust of Sneezing and Choking',
    type: 'Item Mágico (Pó Amaldiçoado)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Saco letal perigoso disfarçado visualmente perfeito mágico de (Pó da Invasão). Lançá-lo 9 metros ar gera nuvem fuligem sufocante; Toda a respiração viva engasga e falha em pura sufocação tóxica ficando com pura (Condição Incapacitado Atordoado letais e lentos asfixiantes desmaiando sem dano de sangue mas de ar) precisando sucessos Constitucionais 15.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'wind-fan',
    name: 'Leque dos Ventos',
    englishName: 'Wind Fan',
    type: 'Item Mágico (Leque)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Leque oriental luxuoso forjado com plumas celestiais puras divinas brancas. Usar a Ação canaliza e atira instantâneo o milagre místico turbilhão divino poderoso elemental atirando (Feitiço mágico Rajada de Ventos: Gust of Wind). Ao usar mais de vez diário pode ser destruído total mágico em frangalhos (Tem rolagem letal para usar com ganância).',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'rope-of-climbing',
    name: 'Corda de Escalada',
    englishName: 'Rope of Climbing',
    type: 'Item Mágico (Corda)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Trança mística grossa celestial de finíssimos couros brancos, 18 m imensos. Você usa de forma viva falada pra atirar que se arrasta viva qual uma víbora rápida prendendo se nó firme absoluto impossível se arrancar no alto num gancho. Sustenta imensos totais peso brutais absurdos (1.500 Kg limpos de heróis).',
    value: '500 PO',
    weight: 3,
  },
  {
    id: 'ring-of-spell-turning',
    name: 'Anel de Refletir Magia',
    englishName: 'Ring of Spell Turning',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Joia de diamante mágico protetor passivo que te dá global pura e letal Vantagem absolutas nos Salvamentos passivos diretos de alvos letais cósmicos mirados. E, se ao passar por um ataque de magia forte na salvaguarda mágica pura você Rolar e cair Nat 20 absoluto fatal celestial da sorte extrema: Ela é Refletida cósmica atirando no Caster inimigo original letal absoluto de volta inteiramente sem ferir o anel!',
    value: '75.000 PO',
    weight: 0.1,
  },
  {
    id: 'scarab-of-protection',
    name: 'Escaravelho de Proteção',
    englishName: 'Scarab of Protection',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Incrustação dourada peitoral pura de joias que defende divinamente o possuidor contra os deuses e raios e maldições da peste e letal necrose sombrias puros passivos sem limite; e intercepta até 12 absolutos Raios letais divinos necromânticos destruindo-os. Após 12 magias celestiais destruídas ele estourará.',
    value: '50.000 PO',
    weight: 1,
  },
  {
    id: 'sun-blade',
    name: 'Lâmina do Sol',
    englishName: 'Sun Blade',
    type: 'Item Mágico (Espada)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Cabo místico que ao puxar ativo o gatilho, expele em flash estourado vivo imortal um plasma de fina espada pura branca dourada letal sagrada (Atributo de sabre longo/curto veloz destreza mágico). Dano é de Radiação luminosa solar letal em área letal contra sombrios letais. Ilumina abismos profundos das grutas absolutas na luz de dia do sol em 18m.',
    value: '6.000 PO',
    weight: 1,
  }
];
