import { SRDSpell } from './types';
import { BATCH_2_SPELLS } from './srd-spells-batch-2';
import { BATCH_3_SPELLS } from './srd-spells-batch-3';
import { BATCH_4_SPELLS } from './srd-spells-batch-4';
import { BATCH_5_SPELLS } from './srd-spells-batch-5';
import { BATCH_6_SPELLS } from './srd-spells-batch-6';
import { BATCH_7_SPELLS } from './srd-spells-batch-7';
import { BATCH_8_SPELLS } from './srd-spells-batch-8';
import { BATCH_9_SPELLS } from './srd-spells-batch-9';
import { BATCH_10_SPELLS } from './srd-spells-batch-10';

const BASE_SPELLS: SRDSpell[] = [
  // ── TRUQUES (NÍVEL 0) ──
  {
    id: 'acid-splash',
    name: 'Espirro de Ácido (Acid Splash)',
    englishName: 'Acid Splash',
    level: 0,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Esfera de 1.5m (duas criaturas adjacentes)' },
    damageSave: { damageDice: '1d6', damageType: 'Ácido', saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Você arremessa uma bolha de ácido. Escolha uma ou duas criaturas a até 1,5 metro uma da outra ao alcance. Cada alvo deve passar num teste de resistência de Destreza ou sofrer 1d6 de dano de ácido.\n\nO dano aumenta em 1d6 no 5º nível (2d6), 11º nível (3d6) e 17º nível (4d6).',
    higherLevels: 'O dano escala automaticamente com o nível do personagem.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'blade-ward',
    name: 'Proteção contra Lâminas (Blade Ward)',
    englishName: 'Blade Ward',
    level: 0,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'self', formatted: 'Pessoal' },
    damageSave: { attackType: 'utility' },
    description: 'Você estende suas mãos e traça um sinal de proteção no ar. Até o final do seu próximo turno, você tem resistência a dano concussivo, cortante e perfurante causado por ataques com armas.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'chill-touch',
    name: 'Toque da Necrose (Chill Touch)',
    englishName: 'Chill Touch',
    level: 0,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura ao alcance' },
    damageSave: { damageDice: '1d8', damageType: 'Necrótico', attackType: 'ranged_spell' },
    description: 'Você cria uma mão esquelética espectral no espaço de uma criatura ao alcance. Faça um ataque à distância com magia. Se acertar, o alvo sofre 1d8 de dano necrótico e não pode recuperar pontos de vida até o início do seu próximo turno. Se o alvo for um morto-vivo, ele também tem desvantagem nas jogadas de ataque contra você até o final do seu próximo turno.',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'dancing-lights',
    name: 'Luzes Dançantes (Dancing Lights)',
    englishName: 'Dancing Lights',
    level: 0,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pouco de fósforo, vaga-lume ou madeira luminosa', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 3, sizeUnit: 'm', formatted: '4 luzes em área de 3m' },
    damageSave: { attackType: 'utility' },
    description: 'Você cria até quatro luzes do tamanho de tochas, fazendo com que pareçam lanternas ou orbes brilhantes. Cada luz emite penumbra num raio de 3 metros. Com uma ação bônus, você pode mover as luzes até 18 metros.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'druidcraft',
    name: 'Truque de Druida (Druidcraft)',
    englishName: 'Druidcraft',
    level: 0,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Cubo de 1.5m' },
    damageSave: { attackType: 'utility' },
    description: 'Whispering to the spirits of nature, você cria um efeito sensorial menor: prever o clima pelas próximas 24 horas, fazer uma flor desabrochar, criar uma brisa suave ou acender/apagar uma vela ou fogueira pequena.',
    classes: ['Druida']
  },
  {
    id: 'eldritch-blast',
    name: 'Explosão Mística (Eldritch Blast)',
    englishName: 'Eldritch Blast',
    level: 0,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: '1 a 4 feixes a alvos ao alcance' },
    damageSave: { damageDice: '1d10', damageType: 'Força', attackType: 'ranged_spell' },
    description: 'Um feixe de energia crepitante dispara em direção a uma criatura ao alcance. Faça um ataque à distância com magia. Acerto: 1d10 de dano de força.\n\nA magia cria feixes adicionais nos níveis 5 (2 feixes), 11 (3 feixes) e 17 (4 feixes). Você pode direcionar os feixes para o mesmo alvo ou alvos diferentes.',
    classes: ['Bruxo']
  },
  {
    id: 'fire-bolt',
    name: 'Raio de Fogo (Fire Bolt)',
    englishName: 'Fire Bolt',
    level: 0,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura ou objeto ao alcance' },
    damageSave: { damageDice: '1d10', damageType: 'Fogo', attackType: 'ranged_spell' },
    description: 'Você arremessa uma estilha de fogo numa criatura ou objeto ao alcance. Faça um ataque à distância com magia. Em um acerto, o alvo sofre 1d10 de dano de fogo. Um objeto inflamável atingido se incendeia se não estiver sendo vestido ou carregado.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'friends',
    name: 'Amizade (Friends)',
    englishName: 'Friends',
    level: 0,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: false, somatic: true, material: true, materialsDescription: 'um pouco de maquiagem aplicada ao rosto', raw: 'S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Um humanoide não hostil' },
    damageSave: { attackType: 'utility' },
    description: 'Pela duração, você tem vantagem em todos os testes de Carisma direcionados a uma pessoa não hostil. Quando a magia termina, a criatura percebe que foi manipulada por magia e se torna hostil a você.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'guidance',
    name: 'Orientação (Guidance)',
    englishName: 'Guidance',
    level: 0,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Uma criatura voluntária tocada' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura voluntária. Uma vez antes da magia terminar, o alvo pode rolar um d4 e adicionar o número rolado a um teste de habilidade à sua escolha.',
    classes: ['Clérigo', 'Druida']
  },
  {
    id: 'light',
    name: 'Luz (Light)',
    englishName: 'Light',
    level: 0,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: true, materialsDescription: 'um vaga-lume ou musgo fosforescente', raw: 'V, M' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Um objeto tocado' },
    damageSave: { saveStat: 'DEX', saveEffect: 'negate', attackType: 'utility' },
    description: 'Você toca um objeto que não meça mais de 3 metros em qualquer dimensão. Até a magia terminar, o objeto emite luz brilhante num raio de 6 metros e luz penumbra por mais 6 metros.',
    classes: ['Bardo', 'Clérigo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'mage-hand',
    name: 'Mão dos Magos (Mage Hand)',
    englishName: 'Mage Hand',
    level: 0,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Um ponto ao alcance' },
    damageSave: { attackType: 'utility' },
    description: 'Uma mão espectral e flutuante aparece no ponto escolhido ao alcance. Você pode usar a mão para manipular um objeto, abrir uma porta não trancada, carregar até 4.5kg ou derramar um recipiente.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'mending',
    name: 'Consertar (Mending)',
    englishName: 'Mending',
    level: 0,
    school: 'Transmutação',
    castingTime: '1 minuto',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'duas pedras-ímã', raw: 'V, S, M' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Um objeto com rasgo ou quebra (até 30cm)' },
    damageSave: { attackType: 'utility' },
    description: 'Esta magia repara uma única quebra ou rasgo em um objeto que você tocar, como um elo de corrente quebrado, duas metades de uma chave partida ou um rasgo numa capa.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Feiticeiro', 'Mago']
  },
  {
    id: 'message',
    name: 'Mensagem (Message)',
    englishName: 'Message',
    level: 0,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pedaço de fio de cobre', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura ao alcance' },
    damageSave: { attackType: 'utility' },
    description: 'Você aponta o dedo para uma criatura ao alcance e sussurra uma mensagem. O alvo (e apenas ele) ouve a mensagem e pode responder em um sussurro que apenas você pode ouvir.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'minor-illusion',
    name: 'Ilusão Menor (Minor Illusion)',
    englishName: 'Minor Illusion',
    level: 0,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: false, somatic: true, material: true, materialsDescription: 'um pouco de lã', raw: 'S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Cubo de 1.5m' },
    damageSave: { attackType: 'utility' },
    description: 'Você cria um som ou a imagem de um objeto ao alcance que dura pela duração. A ilusão não pode criar som complexo nem sensação tátil. Um teste de Investigação (INT) contra sua CD de magia revela que se trata de uma ilusão.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'poison-spray',
    name: 'Borrão de Veneno (Poison Spray)',
    englishName: 'Poison Spray',
    level: 0,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '3 metros (10 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura a até 3m' },
    damageSave: { damageDice: '1d12', damageType: 'Veneno', saveStat: 'CON', saveEffect: 'negate', attackType: 'save' },
    description: 'Você estende a mão em direção a uma criatura e projeta um sopro de gás tóxico. O alvo deve passar num teste de resistência de Constituição ou sofrer 1d12 de dano de veneno.',
    classes: ['Druida', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'prestidigitation',
    name: 'Prestidigitação (Prestidigitation)',
    englishName: 'Prestidigitation',
    level: 0,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '3 metros (10 pés)',
    duration: 'Até 1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'cube', sizeValue: 0.3, sizeUnit: 'm', formatted: 'Efeito mágico menor' },
    damageSave: { attackType: 'utility' },
    description: 'Esta magia é um truque mágico menor usado por conjuradores novatos: crie faíscas, brisa, limpe/suje um objeto menor que 0.3m, esquente ou resfrie 1kg de matéria orgânica, ou crie uma ilusão inofensiva.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'ray-of-frost',
    name: 'Raio de Gelo (Ray of Frost)',
    englishName: 'Ray of Frost',
    level: 0,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura ao alcance' },
    damageSave: { damageDice: '1d8', damageType: 'Gelo', attackType: 'ranged_spell' },
    description: 'Um raio azul-esbranquiçado de frio gélido dispara em direção a uma criatura. Faça um ataque à distância com magia. Em um acerto, o alvo sofre 1d8 de dano de frio e seu deslocamento é reduzido em 3 metros até o início do seu próximo turno.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'resistance',
    name: 'Resistência (Resistance)',
    englishName: 'Resistance',
    level: 0,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma capa em miniatura', raw: 'V, S, M' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Uma criatura voluntária tocada' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura voluntária. Uma vez antes da magia terminar, o alvo pode rolar um d4 e adicionar o resultado a um teste de resistência de sua escolha.',
    classes: ['Clérigo', 'Druida']
  },
  {
    id: 'sacred-flame',
    name: 'Chama Sagrada (Sacred Flame)',
    englishName: 'Sacred Flame',
    level: 0,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura visível ao alcance' },
    damageSave: { damageDice: '1d8', damageType: 'Radiante', saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Brilho similar a fogo desce sobre uma criatura que você possa ver ao alcance. O alvo deve passar num teste de resistência de Destreza ou sofrer 1d8 de dano radiante. O alvo não ganha benefício de cobertura para este teste.',
    classes: ['Clérigo']
  },
  {
    id: 'shillelagh',
    name: 'Bordão Mágico (Shillelagh)',
    englishName: 'Shillelagh',
    level: 0,
    school: 'Transmutação',
    castingTime: '1 ação bônus',
    range: 'Toque',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'mistletoe e folha de trévo', raw: 'V, S, M' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Um bordão ou clava segurado' },
    damageSave: { damageDice: '1d8', damageType: 'Concussão', attackType: 'melee_spell' },
    description: 'A madeira de um bordão ou clava que você segura é imbuída com o poder da natureza. Pela duração, você usa sua habilidade de conjuração (Sabedoria) para jogadas de ataque e dano corpo a corpo com a arma, e o dado de dano se torna 1d8.',
    classes: ['Druida']
  },
  {
    id: 'shocking-grasp',
    name: 'Toque Chocante (Shocking Grasp)',
    englishName: 'Shocking Grasp',
    level: 0,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Uma criatura tocada' },
    damageSave: { damageDice: '1d8', damageType: 'Elétrico', attackType: 'melee_spell' },
    description: 'Eletricidade surge da sua mão para causar um choque numa criatura. Faça um ataque com magia corpo a corpo. Você tem vantagem na jogada se o alvo estiver vestindo armadura de metal. Em um acerto, sofre 1d8 de dano elétrico e não pode realizar reações até o início do próximo turno dele.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'spare-the-dying',
    name: 'Estabilizar (Spare the Dying)',
    englishName: 'Spare the Dying',
    level: 0,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Uma criatura viva com 0 PV' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura viva que esteja com 0 pontos de vida. A criatura se torna estável. Esta magia não afeta mortos-vivos ou constructos.',
    classes: ['Clérigo']
  },
  {
    id: 'thorn-whip',
    name: 'Chicote de Espinhos (Thorn Whip)',
    englishName: 'Thorn Whip',
    level: 0,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um caule de planta espinhosa', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura a até 9m' },
    damageSave: { damageDice: '1d6', damageType: 'Perfurante', attackType: 'melee_spell' },
    description: 'Você cria um chicote longo de vinhas com espinhos. Faça um ataque mágico corpo a corpo contra o alvo. Em caso de acerto, causa 1d6 de dano perfurante e, se o alvo for de tamanho Grande ou menor, você o puxa até 3 metros em sua direção.',
    classes: ['Druida']
  },
  {
    id: 'thaumaturgy',
    name: 'Taumaturgia (Thaumaturgy)',
    englishName: 'Thaumaturgy',
    level: 0,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 9, sizeUnit: 'm', formatted: 'Efeito miraculoso menor' },
    damageSave: { attackType: 'utility' },
    description: 'Você manifesta uma maravilha menor divina: sua voz retumba 3x mais alto, chamas tremulam ou mudam de cor, tremores no chão, som sobrenatural (trovão, corvos), ou abrir/fechar uma porta destrancada bruscamente.',
    classes: ['Clérigo']
  },
  {
    id: 'vicious-mockery',
    name: 'Zombaria Viciosa (Vicious Mockery)',
    englishName: 'Vicious Mockery',
    level: 0,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura que possa te ouvir' },
    damageSave: { damageDice: '1d4', damageType: 'Psíquico', saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Você profere insultos imbuídos com feitiçaria contra uma criatura ao alcance que possa ouvir você. Ela deve fazer um teste de resistência de Sabedoria. Em caso de falha, sofre 1d4 de dano psíquico e tem desvantagem na próxima jogada de ataque antes do final do próximo turno dela.',
    classes: ['Bardo']
  },

  // ── NÍVEL 1 ──
  {
    id: 'burning-hands',
    name: 'Mãos Flamejantes (Burning Hands)',
    englishName: 'Burning Hands',
    level: 1,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Pessoal (cone de 4.5m / 15 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'cone', sizeValue: 4.5, sizeUnit: 'm', formatted: 'Leque / Cone de 4.5m (15ft)' },
    damageSave: { damageDice: '3d6', damageType: 'Fogo', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Segurando seus polegares juntos e estendendo os dedos, um leque de chamas dispara dos seus dedos. Cada criatura num cone de 4,5 metros deve fazer um TR de Destreza. Falha: 3d6 de dano de fogo; Sucesso: metade.',
    higherLevels: 'Quando conjurada usando um espaço de 2º nível ou superior, o dano aumenta em 1d6 para cada nível acima do 1º.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'cure-wounds',
    name: 'Curar Ferimentos (Cure Wounds)',
    englishName: 'Cure Wounds',
    level: 1,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Uma criatura tocada' },
    damageSave: { damageDice: '1d8 + mod', damageType: 'Cura', attackType: 'utility' },
    description: 'Uma criatura que você tocar recupera um número de pontos de vida igual a 1d8 + seu modificador de habilidade de conjuração. Esta magia não tem efeito em mortos-vivos ou constructos.',
    higherLevels: 'Quando conjurada em níveis superiores, cura +1d8 adicional por nível de espaço acima do 1º.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Paladino', 'Patrulheiro']
  },
  {
    id: 'healing-word',
    name: 'Palavra Curativa (Healing Word)',
    englishName: 'Healing Word',
    level: 1,
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura visível ao alcance' },
    damageSave: { damageDice: '1d4 + mod', damageType: 'Cura', attackType: 'utility' },
    description: 'Uma criatura de sua escolha que você possa ver ao alcance recupera pontos de vida iguais a 1d4 + seu modificador de habilidade de conjuração.',
    higherLevels: 'Cura +1d4 adicional por nível acima do 1º.',
    classes: ['Bardo', 'Clérigo', 'Druida']
  },
  {
    id: 'magic-missile',
    name: 'Mísseis Mágicos (Magic Missile)',
    englishName: 'Magic Missile',
    level: 1,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: '3 dardos incandescentes a alvos ao alcance' },
    damageSave: { damageDice: '3d4 + 3', damageType: 'Força', attackType: 'utility' },
    description: 'Você cria três dardos brilhantes de força mágica. Cada dardo atinge uma criatura à sua escolha ao alcance automaticamente (sem teste de ataque ou salvaguarda), causando 1d4 + 1 de dano de força por dardo.',
    higherLevels: 'Cria 1 dardo adicional para cada nível de espaço acima do 1º.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'shield',
    name: 'Escudo Mágico (Shield)',
    englishName: 'Shield',
    level: 1,
    school: 'Abjuração',
    castingTime: '1 reação',
    range: 'Pessoal',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'self', formatted: 'Pessoal' },
    damageSave: { attackType: 'utility' },
    description: 'Uma barreira invisível de força surge quando você é atingido por um ataque ou alvo de Míssil Mágico. Você ganha um bônus de +5 na Classe de Armadura até o início do seu próximo turno e ignora todo dano de Mísseis Mágicos.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'thunderwave',
    name: 'Onda Trovão (Thunderwave)',
    englishName: 'Thunderwave',
    level: 1,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Pessoal (cubo de 4.5m / 15 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 4.5, sizeUnit: 'm', formatted: 'Cubo de 4.5m (15ft) originado em você' },
    damageSave: { damageDice: '2d8', damageType: 'Trovão', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Uma onda de força trovejante se projeta a partir de você. Cada criatura num cubo de 4,5m deve fazer um TR de Constituição. Falha: 2d8 de dano de trovão e é empurrada 3m para longe de você. Sucesso: metade do dano e não é empurrada.',
    higherLevels: 'O dano aumenta em 1d8 por nível acima do 1º.',
    classes: ['Bardo', 'Druida', 'Feiticeiro', 'Mago']
  },
  {
    id: 'bless',
    name: 'Bênção (Bless)',
    englishName: 'Bless',
    level: 1,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma borrifada de água benta', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 3 criaturas ao alcance' },
    damageSave: { attackType: 'utility' },
    description: 'Você abençoa até três criaturas à sua escolha ao alcance. Sempre que um alvo fizer uma jogada de ataque ou teste de resistência antes da magia terminar, o alvo pode rolar um d4 e adicionar o valor ao resultado.',
    higherLevels: 'Afeta +1 criatura adicional para cada nível acima do 1º.',
    classes: ['Clérigo', 'Paladino']
  },
  {
    id: 'command',
    name: 'Comando (Command)',
    englishName: 'Command',
    level: 1,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura ao alcance' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Você profere uma ordem de uma palavra a uma criatura visível ao alcance (ex: Pare, Caia, Fuga, Solte, Aproxime-se). O alvo deve passar num TR de Sabedoria ou obedecer ao comando no seu próximo turno.',
    classes: ['Clérigo', 'Paladino']
  },

  // ── NÍVEL 2 ──
  {
    id: 'misty-step',
    name: 'Passo Nebuloso (Misty Step)',
    englishName: 'Misty Step',
    level: 2,
    school: 'Conjuração',
    castingTime: '1 ação bônus',
    range: 'Pessoal',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'self', shape: 'self', formatted: 'Teletransporte pessoal de até 9m' },
    damageSave: { attackType: 'utility' },
    description: 'Brevemente cercado por uma névoa prateada, você se teleporta até 9 metros para um espaço desocupado que você possa ver.',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'scorching-ray',
    name: 'Raio de Ruína (Scorching Ray)',
    englishName: 'Scorching Ray',
    level: 2,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: '3 raios incandescentes a alvos ao alcance' },
    damageSave: { damageDice: '2d6', damageType: 'Fogo', attackType: 'ranged_spell' },
    description: 'Você cria três raios de fogo e os arremessa contra alvos ao alcance. Faça um ataque à distância com magia para cada raio. Cada acerto causa 2d6 de dano de fogo.',
    higherLevels: 'Cria 1 raio adicional para cada nível de espaço acima do 2º.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'hold-person',
    name: 'Imobilizar Pessoa (Hold Person)',
    englishName: 'Hold Person',
    level: 2,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pequeno pedaço de ferro reto', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Um humanoide visível' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Escolha um humanoide que você possa ver ao alcance. O alvo deve passar num teste de resistência de Sabedoria ou ficar Paralisado pela duração. No final de cada turno dele, o alvo pode fazer outro TR para encerrar o efeito.',
    higherLevels: 'Pode alvocar +1 humanoide adicional para cada nível acima do 2º.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'invisibility',
    name: 'Invisibilidade (Invisibility)',
    englishName: 'Invisibility',
    level: 2,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma pestana envolta em goma', raw: 'V, S, M' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Uma criatura voluntária tocada' },
    damageSave: { attackType: 'utility' },
    description: 'Uma criatura que você tocar fica invisível até a magia terminar. Qualquer item vestido ou carregado fica invisível. A magia termina se o alvo atacar ou conjurar uma magia.',
    higherLevels: 'Alvoca +1 criatura adicional por nível de espaço acima do 2º.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'shatter',
    name: 'Despedaçar (Shatter)',
    englishName: 'Shatter',
    level: 2,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma lasca de mica', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 3, sizeUnit: 'm', formatted: 'Esfera de 3m (10ft) de raio' },
    damageSave: { damageDice: '3d8', damageType: 'Trovão', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Um som agudo e ensurdecedor ressoa num ponto ao alcance. Criaturas numa esfera de 3m devem fazer TR de Constituição. Falha: 3d8 de dano de trovão; Sucesso: metade. Criaturas de pedra ou cristal têm desvantagem no TR.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },

  // ── NÍVEL 3 ──
  {
    id: 'fireball',
    name: 'Bola de Fogo (Fireball)',
    englishName: 'Fireball',
    level: 3,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '45 metros (150 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma bolinha de guano de morcego e enxofre', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 6, sizeUnit: 'm', formatted: 'Esfera / Baforada de 6m (20ft) de raio' },
    damageSave: { damageDice: '8d6', damageType: 'Fogo', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Um feixe brilhante dispara do seu indicador até um ponto e explode com um rugido numa esfera de 6 metros de raio. Criaturas na área devem fazer TR de Destreza. Falha: 8d6 de dano de fogo; Sucesso: metade. O fogo contorna cantos e incendeia objetos inflamáveis.',
    higherLevels: 'Dano aumenta em 1d6 para cada nível de espaço acima do 3º.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'lightning-bolt',
    name: 'Relâmpago (Lightning Bolt)',
    englishName: 'Lightning Bolt',
    level: 3,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Pessoal (linha de 30m / 100 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pedaço de fura-bolo e uma haste de vidro ou âmbar', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'line', sizeValue: 30, sizeUnit: 'm', formatted: 'Linha de 30m (100ft) de comprimento e 1.5m de largura' },
    damageSave: { damageDice: '8d6', damageType: 'Elétrico', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Um raio de eletricidade de 30 metros de comprimento e 1,5 metro de largura dispara a partir de você. Cada criatura na linha deve fazer um TR de Destreza. Falha: 8d6 de dano elétrico; Sucesso: metade.',
    higherLevels: 'O dano aumenta em 1d6 por nível de espaço acima do 3º.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'fly',
    name: 'Voo (Fly)',
    englishName: 'Fly',
    level: 3,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Concentração, até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma pena da asa de uma ave de rapina', raw: 'V, S, M' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Uma criatura voluntária tocada' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura voluntária. O alvo ganha um deslocamento de voo de 18 metros pela duração. Se a magia terminar enquanto o alvo estiver voando, ele cai se não tiver outro meio de flutuar.',
    higherLevels: 'Pode alvocar +1 criatura adicional para cada nível acima do 3º.',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'counterspell',
    name: 'Contramagia (Counterspell)',
    englishName: 'Counterspell',
    level: 3,
    school: 'Abjuração',
    castingTime: '1 reação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: false, somatic: true, material: false, raw: 'S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura conjurando uma magia a até 18m' },
    damageSave: { attackType: 'utility' },
    description: 'Você tenta interromper o processo de conjuração de uma magia. Se a magia for de 3º nível ou inferior, ela falha e não produz efeito. Se for de 4º nível ou superior, faça um teste de habilidade de conjuração (CD = 10 + nível da magia). Em um sucesso, a magia falha.',
    higherLevels: 'Se conjurada em nível igual ou superior à magia alvo, ela falha automaticamente sem teste.',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'dispel-magic',
    name: 'Dissipar Magia (Dispel Magic)',
    englishName: 'Dispel Magic',
    level: 3,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura, objeto ou efeito mágico ao alcance' },
    damageSave: { attackType: 'utility' },
    description: 'Escolha uma criatura, objeto ou efeito mágico ao alcance. Qualquer magia de 3º nível ou inferior no alvo termina. Para magias de nível superior, faça um teste de habilidade (CD = 10 + nível da magia).',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Paladino', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'revivify',
    name: 'Reviver (Revivify)',
    englishName: 'Revivify',
    level: 3,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'diamantes valendo 300 PO, consumidos pela magia', costly: true, consumed: true, raw: 'V, S, M (diamantes de 300 PO, consumidos)' },
    targetArea: { type: 'touch', shape: 'touch', formatted: 'Uma criatura morta há no máximo 1 minuto' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura que tenha morrido no último minuto. A criatura retorna à vida com 1 ponto de vida. Esta magia não recupera partes do corpo decepadas.',
    classes: ['Clérigo', 'Paladino']
  },

  // ── NÍVEL 4 ──
  {
    id: 'banishment',
    name: 'Banimento (Banishment)',
    englishName: 'Banishment',
    level: 4,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um item repugnante ao alvo', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura ao alcance' },
    damageSave: { saveStat: 'CHA', saveEffect: 'negate', attackType: 'save' },
    description: 'Você tenta banir uma criatura para outro plano de existência. O alvo deve fazer um TR de Carisma. Em falha, é banido. Se a magia durar o minuto inteiro e a criatura for nativa de outro plano, ela não retorna.',
    higherLevels: 'Pode alvocar +1 criatura por nível de espaço acima do 4º.',
    classes: ['Clérigo', 'Paladino', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'polymorph',
    name: 'Metamorfose (Polymorph)',
    englishName: 'Polymorph',
    level: 4,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Concentração, até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um capulo de lagarta', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura ao alcance' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Transforma uma criatura ao alcance numa nova forma de Besta. Uma criatura não voluntária deve fazer TR de Sabedoria para evitar o efeito. Suas estatísticas mudam para as da besta escolhida.',
    classes: ['Bardo', 'Druida', 'Feiticeiro', 'Mago']
  },
  {
    id: 'dimension-door',
    name: 'Porta Dimensional (Dimension Door)',
    englishName: 'Dimension Door',
    level: 4,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '150 metros (500 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'self', shape: 'self', formatted: 'Teletransporte pessoal + 1 companheiro até 150m' },
    damageSave: { attackType: 'utility' },
    description: 'Você se teletransporta para qualquer local dentro do alcance. Você pode levar consigo objetos e uma criatura voluntária do seu tamanho ou menor.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },

  // ── NÍVEL 5 ──
  {
    id: 'cone-of-cold',
    name: 'Cone de Frio (Cone of Cold)',
    englishName: 'Cone of Cold',
    level: 5,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Pessoal (cone de 18m / 60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pequeno cone de cristal ou vidro', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cone', sizeValue: 18, sizeUnit: 'm', formatted: 'Cone / Leque de 18m (60ft)' },
    damageSave: { damageDice: '8d8', damageType: 'Gelo', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Uma rajada de ar congelante dispara das suas mãos num cone de 18 metros. Cada criatura no cone deve fazer um TR de Constituição. Falha: 8d8 de dano de frio; Sucesso: metade.',
    higherLevels: 'O dano aumenta em 1d8 por nível de espaço acima do 5º.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'flame-strike',
    name: 'Golpe Flamejante (Flame Strike)',
    englishName: 'Flame Strike',
    level: 5,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pouco de enxofre em pó', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cylinder', sizeValue: 3, sizeUnit: 'm', formatted: 'Cilindro de 3m de raio e 12m de altura' },
    damageSave: { damageDice: '4d6 + 4d6', damageType: 'Fogo / Radiante', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Uma coluna vertical de fogo divino desce dos céus num raio de 3 metros e 12 metros de altura. Cada criatura na área deve fazer um TR de Destreza, sofrendo 4d6 de dano de fogo e 4d6 de dano radiante (metade num sucesso).',
    higherLevels: 'Aumenta 1d6 de dano (fogo ou radiante) por nível acima do 5º.',
    classes: ['Clérigo']
  },

  // ── NÍVEL 6 ──
  {
    id: 'disintegrate',
    name: 'Desintegrar (Disintegrate)',
    englishName: 'Disintegrate',
    level: 6,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'ímã e um pouco de poeira', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura ou objeto ao alcance' },
    damageSave: { damageDice: '10d6 + 40', damageType: 'Força', saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Um raio verde fino dispara da sua ponta dos dedos. O alvo deve fazer um TR de Destreza. Se falhar, sofre 10d6 + 40 de dano de força. Se este dano reduzir os PV do alvo a 0, ele é completamente reduzido a um monte de poeira cinzenta.',
    higherLevels: 'Dano aumenta em 3d6 para cada nível acima do 6º.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'heal',
    name: 'Cura Total (Heal)',
    englishName: 'Heal',
    level: 6,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura visível ao alcance' },
    damageSave: { damageDice: '70', damageType: 'Cura', attackType: 'utility' },
    description: 'Inunda uma criatura com energia positiva. O alvo recupera 70 pontos de vida imediatamente e cura todas as cegueiras, surdezes e doenças.',
    higherLevels: 'Recupera +10 PV adicionais por nível acima do 6º.',
    classes: ['Clérigo', 'Druida']
  },

  // ── NÍVEL 7 ──
  {
    id: 'finger-of-death',
    name: 'Dedo da Morte (Finger of Death)',
    englishName: 'Finger of Death',
    level: 7,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura visível' },
    damageSave: { damageDice: '7d8 + 30', damageType: 'Necrótico', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Envia energia necrótica através do seu indicador contra uma criatura. O alvo deve fazer TR de Constituição, sofrendo 7d8 + 30 de dano necrótico (metade num sucesso). Um humanoide morto por esta magia se ergue no seu próximo turno como um zumbi sob seu comando permanente.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'teleport',
    name: 'Teletransporte (Teleport)',
    englishName: 'Teleport',
    level: 7,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '3 metros (10 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 3, sizeUnit: 'm', formatted: 'Você + até 8 criaturas voluntárias' },
    damageSave: { attackType: 'utility' },
    description: 'Transporta você e até oito criaturas voluntárias para qualquer destino conhecido no mesmo plano de existência.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },

  // ── NÍVEL 8 ──
  {
    id: 'earthquake',
    name: 'Terremoto (Earthquake)',
    englishName: 'Earthquake',
    level: 8,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '150 metros (500 pés)',
    duration: 'Concentração, até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma lasca de rocha e um pouco de lama', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 30, sizeUnit: 'm', formatted: 'Esfera de 30m de raio no chão' },
    damageSave: { damageDice: '5d6', damageType: 'Concussão', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Você causa um tremor intenso no chão num raio de 30 metros. Criaturas na área devem fazer TR de Destreza para não caírem caídas e fissuras podem abrir no solo destruindo estruturas.',
    classes: ['Clérigo', 'Druida', 'Feiticeiro']
  },
  {
    id: 'sunburst',
    name: 'Explosão Solar (Sunburst)',
    englishName: 'Sunburst',
    level: 8,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '45 metros (150 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma lupa e sol de fogo', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 18, sizeUnit: 'm', formatted: 'Esfera de 18m (60ft) de raio' },
    damageSave: { damageDice: '12d6', damageType: 'Radiante', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Luz solar brilhante surge num raio de 18 metros. Criaturas na área devem fazer um TR de Constituição. Falha: 12d6 de dano radiante e fica cega por 1 minuto; Sucesso: metade do dano e não fica cega. Mortos-vivos e limos têm desvantagem no TR.',
    classes: ['Clérigo', 'Druida', 'Mago']
  },

  // ── NÍVEL 9 ──
  {
    id: 'meteor-swarm',
    name: 'Chuva de Meteoros (Meteor Swarm)',
    englishName: 'Meteor Swarm',
    level: 9,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '1.5 quilômetros (1 milha)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 12, sizeUnit: 'm', formatted: '4 esferas / baforadas de 12m (40ft) de raio' },
    damageSave: { damageDice: '20d6 + 20d6', damageType: 'Fogo / Concussão', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Orbes de fogo flamejantes caem na terra em quatro pontos à sua escolha ao alcance. Cada criatura numa esfera de 12 metros de raio centrada em cada ponto deve fazer um TR de Destreza. Falha: 20d6 de dano de fogo + 20d6 de dano concussivo; Sucesso: metade do dano.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'power-word-kill',
    name: 'Palavra de Poder: Matar (Power Word Kill)',
    englishName: 'Power Word Kill',
    level: 9,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Uma criatura ao alcance' },
    damageSave: { attackType: 'utility' },
    description: 'Você profere uma palavra de poder que pode forçar uma criatura a morrer instantaneamente. Se a criatura escolhida tiver 100 pontos de vida ou menos, ela morre imediatamente. Caso contrário, a magia não surte efeito.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'wish',
    name: 'Desejo (Wish)',
    englishName: 'Wish',
    level: 9,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'special', shape: 'special', formatted: 'Alteração suprema da realidade' },
    damageSave: { attackType: 'utility' },
    description: 'Desejo é a magia mortal mais poderosa que uma criatura arcana pode conjurar. Ao simplesmente falar alto, você pode alterar os próprios alicerces da realidade. O uso básico é duplicar qualquer outra magia de 8º nível ou inferior sem precisar cumprir requisitos.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'time-stop',
    name: 'Parar o Tempo (Time Stop)',
    englishName: 'Time Stop',
    level: 9,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'self', shape: 'self', formatted: 'Paralisação do tempo mundial' },
    damageSave: { attackType: 'utility' },
    description: 'Você para brevemente o fluxo do tempo para todos, exceto você mesmo. O tempo permanece parado por 1d4 + 1 rodadas, durante as quais você pode se mover e realizar ações normalmente.',
    classes: ['Feiticeiro', 'Mago']
  }
];

const RAW_ALL_SRD_SPELLS: SRDSpell[] = [
  ...BASE_SPELLS,
  ...BATCH_2_SPELLS,
  ...BATCH_3_SPELLS,
  ...BATCH_4_SPELLS,
  ...BATCH_5_SPELLS,
  ...BATCH_6_SPELLS,
  ...BATCH_7_SPELLS,
  ...BATCH_8_SPELLS,
  ...BATCH_9_SPELLS,
  ...BATCH_10_SPELLS
];

// Remover duplicados baseando no ID
export const ALL_SRD_SPELLS = RAW_ALL_SRD_SPELLS.filter(
  (spell, index, self) => index === self.findIndex((s) => s.id === spell.id)
);
