import { SRDItem } from './types';

export const BATCH_2_RINGS: SRDItem[] = [
  {
    id: 'ring-of-animal-influence',
    name: 'Anel de Influenciar Animais',
    englishName: 'Ring of Animal Influence',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Rara',
    attunement: false,
    description: 'Este anel tem 3 cargas e recupera 1d3 cargas gastas diariamente ao amanhecer. Enquanto o usar, você pode usar uma ação para gastar 1 carga e conjurar uma das seguintes magias: Amizade Animal, Medo (afeta apenas bestas com Inteligência 3 ou inferior) ou Falar com Animais.',
    value: '4.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-djinni-summoning',
    name: 'Anel de Invocação de Djinni',
    englishName: 'Ring of Djinni Summoning',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar este anel, você pode usar uma ação para falar sua palavra de comando e conjurar um djinni a partir do anel. O djinni aparece num espaço desocupado que você possa ver num raio de 36 metros de você. O djinni permanece por até 1 hora, agindo de forma amigável a você e aos seus companheiros. Ele obedece aos comandos verbais que você der. Após esse uso, o djinni não pode ser conjurado novamente até 1d6 dias terem se passado.',
    value: '50.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-elemental-command',
    name: 'Anel de Comando Elemental',
    englishName: 'Ring of Elemental Command',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Estes anéis estão ligados a um dos quatro Planos Elementais (Ar, Terra, Fogo, Água). Enquanto usar o anel, você tem vantagem em jogadas de ataque contra elementais daquele tipo, e eles têm desvantagem em ataques contra você. Você também pode conjurar magias específicas dependendo do elemento do anel. Se você ajudar a matar um elemental daquele tipo enquanto estiver sintonizado, o anel absorve a magia e libera poderes adicionais (como resistências, e magias mais fortes).',
    value: '50.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-evasion',
    name: 'Anel de Evasão',
    englishName: 'Ring of Evasion',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Este anel tem 3 cargas e recupera 1d3 cargas gastas diariamente ao amanhecer. Quando você falhar num teste de resistência de Destreza, pode usar sua reação e gastar 1 carga para ser bem-sucedido no teste.',
    value: '5.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-free-action',
    name: 'Anel de Movimentação Livre',
    englishName: 'Ring of Free Action',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar este anel, terreno difícil não custa movimento extra para você. Além disso, magia não pode reduzir seu deslocamento nem causar em você as condições Paralisado ou Restrito.',
    value: '4.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-jumping',
    name: 'Anel de Salto',
    englishName: 'Ring of Jumping',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar este anel, você pode conjurar a magia Salto (Jump) em si mesmo à vontade como uma ação bônus.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-mind-shielding',
    name: 'Anel de Proteção Mental',
    englishName: 'Ring of Mind Shielding',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar este anel, você é imune a magias que permitam ler seus pensamentos, determinem se você está mentindo ou descubram seu alinhamento. Magias não podem comunicar-se telepaticamente com você a menos que você permita. Você pode fazer o anel ficar invisível. Se você morrer enquanto usa o anel, sua alma entra nele (a menos que já abrigue outra alma) e você pode se comunicar telepaticamente com quem usá-lo.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-regeneration',
    name: 'Anel de Regeneração',
    englishName: 'Ring of Regeneration',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar este anel, você recupera 1d6 pontos de vida a cada 10 minutos, desde que você tenha pelo menos 1 ponto de vida. Se você perder uma parte do corpo, o anel faz ela voltar a crescer e estar totalmente recuperada após 1d6+1 dias, se você tiver ao menos 1 ponto de vida durante todo esse tempo.',
    value: '15.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance',
    name: 'Anel de Resistência',
    englishName: 'Ring of Resistance',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Você tem resistência a um tipo de dano enquanto usar este anel. A gema encrustada no anel indica o tipo: Ácido (Pérola), Congelante (Turmalina), Concussão (Opala), Elétrico (Safira), Fogo (Rubi), Força (Safira), Necrótico (Ônix), Perfurante (Granada), Psíquico (Jade), Radiante (Topázio), Trovejante (Espinélio) ou Venenoso (Ametista).',
    value: '4.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-shooting-stars',
    name: 'Anel das Estrelas Cadentes',
    englishName: 'Ring of Shooting Stars',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Este anel tem 6 cargas e recupera 1d6 cargas diariamente ao amanhecer. Você pode usar uma ação para conjurar Fogo das Fadas ou Luzes Dançantes à vontade. Gastando cargas, pode invocar raios elétricos, globos de relâmpagos esféricos ou uma chuva de estrelas cadentes numa área (danos variados de fogo e elétrico). Funciona plenamente apenas à noite a céu aberto.',
    value: '20.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-swimming',
    name: 'Anel de Natação',
    englishName: 'Ring of Swimming',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Incomum',
    attunement: false,
    description: 'Você tem um deslocamento de natação de 12 metros enquanto usar este anel.',
    value: '400 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-telekinesis',
    name: 'Anel de Telecinese',
    englishName: 'Ring of Telekinesis',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar este anel, você pode conjurar a magia Telecinese à vontade, mas ela afeta apenas objetos que não estejam sendo usados ou carregados.',
    value: '20.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-three-wishes',
    name: 'Anel dos Três Desejos',
    englishName: 'Ring of Three Wishes',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Lendária',
    attunement: false,
    description: 'Enquanto usar este anel, você pode usar uma ação para gastar 1 das suas 3 cargas e conjurar a magia Desejo (Wish). O anel perde sua magia e se torna mundano se você usar a última carga.',
    value: '50.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-warmth',
    name: 'Anel de Calor',
    englishName: 'Ring of Warmth',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar este anel, você tem resistência a dano congelante. Além disso, você e tudo que você usa sofrem nenhum dano proveniente de temperaturas frias extremas, permitindo suportar o frio confortavelmente sem roupas de inverno.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-water-walking',
    name: 'Anel de Andar na Água',
    englishName: 'Ring of Water Walking',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Incomum',
    attunement: false,
    description: 'Enquanto usar este anel, você pode permanecer de pé ou andar através de superfícies líquidas, se movendo como faria sobre solo sólido.',
    value: '400 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-x-ray-vision',
    name: 'Anel de Visão de Raios-X',
    englishName: 'Ring of X-Ray Vision',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Você pode usar uma ação para ver através de matéria sólida por 1 minuto num raio de 9 metros. A visão atravessa até 30cm de pedra, 2,5cm de metal comum ou até 90cm de madeira/terra. Usar mais de uma vez por descanso longo força você a um TR de Constituição CD 15, sofrendo um nível de exaustão em caso de falha.',
    value: '4.000 PO',
    weight: 0.1,
  }
];
