import { SRDSpell } from './types';

// O restante das magias utilitárias e de nicho para completar o SRD
export const BATCH_9_SPELLS: SRDSpell[] = [
  { id: 'light', name: 'Luz (Light)', englishName: 'Light', level: 0, school: 'Evocação', castingTime: '1 ação', range: 'Toque', duration: '1 hora', concentration: false, ritual: false, components: { verbal: true, somatic: false, material: true, raw: 'V, M' }, damageSave: { attackType: 'utility' }, description: 'Um objeto tocado brilha com luz radiante brilhante num raio de 6m.', classes: ['Bardo', 'Clérigo', 'Mago'] },
  { id: 'mage-armor', name: 'Armadura Arcana (Mage Armor)', englishName: 'Mage Armor', level: 1, school: 'Abjuração', castingTime: '1 ação', range: 'Toque', duration: '8 horas', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { attackType: 'utility' }, description: 'Alvo não blindado recebe CA base 13 + Modificador de Destreza.', classes: ['Mago', 'Feiticeiro'] },
  { id: 'magic-weapon', name: 'Arma Mágica (Magic Weapon)', englishName: 'Magic Weapon', level: 2, school: 'Transmutação', castingTime: '1 ação bônus', range: 'Toque', duration: 'Até 1 hora', concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false, raw: 'V, S' }, damageSave: { attackType: 'utility' }, description: 'Arma não mágica tocada se torna mágica ganhando +1 bônus em acertos e rolagens.', classes: ['Paladino', 'Mago'] },
  { id: 'nondetection', name: 'Indetectável (Nondetection)', englishName: 'Nondetection', level: 3, school: 'Abjuração', castingTime: '1 ação', range: 'Toque', duration: '8 horas', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { attackType: 'utility' }, description: 'Protege contra magias de adivinhação e de sensores de espionagem scrying.', classes: ['Bardo', 'Patrulheiro', 'Mago'] },
  { id: 'plant-growth', name: 'Crescimento de Plantas (Plant Growth)', englishName: 'Plant Growth', level: 3, school: 'Transmutação', castingTime: '1 ação', range: '45 metros (150 pés)', duration: 'Instantânea', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false, raw: 'V, S' }, damageSave: { attackType: 'utility' }, description: 'Plantas crescem criando um matagal pesado brutal (1m andado custa 4m). Alternativamente aumenta fazendas.', classes: ['Bardo', 'Druida', 'Patrulheiro'] },
  { id: 'protection-from-poison', name: 'Proteção contra Veneno (Protection from Poison)', englishName: 'Protection from Poison', level: 2, school: 'Abjuração', castingTime: '1 ação', range: 'Toque', duration: '1 hora', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false, raw: 'V, S' }, damageSave: { attackType: 'utility' }, description: 'Cura venenos presentes e confere Resistência e Vantagem contra novos venenos.', classes: ['Clérigo', 'Druida', 'Paladino'] },
  { id: 'purify-food-and-drink', name: 'Purificar Alimentos (Purify Food and Drink)', englishName: 'Purify Food and Drink', level: 1, school: 'Transmutação', castingTime: '1 ação', range: '3 metros (10 pés)', duration: 'Instantânea', concentration: false, ritual: true, components: { verbal: true, somatic: true, material: false, raw: 'V, S' }, damageSave: { attackType: 'utility' }, description: 'Limpa toda podridão e venenos de comida e água em raio de 1.5m.', classes: ['Clérigo', 'Druida', 'Paladino'] },
  { id: 'ray-of-enfeeblement', name: 'Raio do Enfraquecimento (Ray of Enfeeblement)', englishName: 'Ray of Enfeeblement', level: 2, school: 'Necromancia', castingTime: '1 ação', range: '18 metros (60 pés)', duration: 'Até 1 minuto', concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false, raw: 'V, S' }, damageSave: { saveStat: 'CON', saveEffect: 'negate', attackType: 'ranged_spell' }, description: 'Ataque mágico que acerta o alvo, fazendo-o causar só a metade do Dano com armas de Força (Corpo-a-Corpo) até passar no TR Constituição.', classes: ['Bruxo', 'Mago'] },
  { id: 'sanctuary', name: 'Santuário (Sanctuary)', englishName: 'Sanctuary', level: 1, school: 'Abjuração', castingTime: '1 ação bônus', range: '9 metros (30 pés)', duration: '1 minuto', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { attackType: 'utility' }, description: 'Inimigos precisam passar em TR Sabedoria antes de atacar a pessoa protegida, caso contrário perdem o golpe. Se a pessoa atacar, a proteção some.', classes: ['Clérigo'] },
  { id: 'sending', name: 'Mensagem (Sending)', englishName: 'Sending', level: 3, school: 'Evocação', castingTime: '1 ação', range: 'Ilimitado', duration: '1 rodada', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { attackType: 'utility' }, description: 'Envia mensagem mental de até 25 palavras para ser no mundo todo. Ele pode responder na mesma moeda. (5% de chance de erro se outro plano).', classes: ['Bardo', 'Clérigo', 'Mago'] },
  { id: 'shape-water', name: 'Moldar Água (Shape Water)', englishName: 'Shape Water', level: 0, school: 'Transmutação', castingTime: '1 ação', range: '9 metros (30 pés)', duration: 'Instantânea', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false, raw: 'V, S' }, damageSave: { attackType: 'utility' }, description: 'Você controla e molda formas em 1.5m de água num nível básico (congelar, animar formas fluidas, mudar de cor, mover).', classes: ['Druida', 'Feiticeiro', 'Mago'] },
  { id: 'shillelagh', name: 'Bordão Mágico (Shillelagh)', englishName: 'Shillelagh', level: 0, school: 'Transmutação', castingTime: '1 ação bônus', range: 'Toque', duration: '1 minuto', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { damageDice: '1d8', damageType: 'Arma', attackType: 'melee_spell' }, description: 'A madeira do bastão ou clava recebe a força da natureza e passa usar seu modificador de Conjuração nas rolagens de ataque, com dado virando D8 mágico.', classes: ['Druida'] },
  { id: 'slow', name: 'Lentidão (Slow)', englishName: 'Slow', level: 3, school: 'Transmutação', castingTime: '1 ação', range: '36 metros (120 pés)', duration: 'Até 1 minuto', concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' }, description: 'Até 6 criaturas ficam lentas (-2 na CA e Salvamentos destreza), perdem reações, agem restritas em ações e movimento reduzido pela metade.', classes: ['Bardo', 'Feiticeiro', 'Mago'] },
  { id: 'speak-with-animals', name: 'Falar com Animais (Speak with Animals)', englishName: 'Speak with Animals', level: 1, school: 'Adivinhação', castingTime: '1 ação', range: 'Pessoal', duration: '10 minutos', concentration: false, ritual: true, components: { verbal: true, somatic: true, material: false, raw: 'V, S' }, damageSave: { attackType: 'utility' }, description: 'Você passa a compreender rudimentarmente bestas pelo ambiente e ouvir conselhos e observações limitadas que eles presenciaram.', classes: ['Bardo', 'Druida', 'Patrulheiro'] },
  { id: 'speak-with-dead', name: 'Falar com os Mortos (Speak with Dead)', englishName: 'Speak with Dead', level: 3, school: 'Necromancia', castingTime: '1 ação', range: '3 metros (10 pés)', duration: '10 minutos', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { attackType: 'utility' }, description: 'Você dá ânimo parcial na cabeça do morto morto pra responder 5 (cinco) perguntas. Ele tem as mesmas memórias e falhas de quando era vivo (Pode omitir ou mentir se for hostil na vida).', classes: ['Bardo', 'Clérigo'] },
  { id: 'speak-with-plants', name: 'Falar com Plantas (Speak with Plants)', englishName: 'Speak with Plants', level: 3, school: 'Transmutação', castingTime: '1 ação', range: 'Pessoal (raio 9m)', duration: '10 minutos', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false, raw: 'V, S' }, damageSave: { attackType: 'utility' }, description: 'As plantas do raio recebem ânimo e sentidos pra responder às suas perguntas. Árvores liberam cipós do caminho para facilitar passagem, se pedido.', classes: ['Bardo', 'Druida', 'Patrulheiro'] },
  { id: 'stinking-cloud', name: 'Névoa Fétida (Stinking Cloud)', englishName: 'Stinking Cloud', level: 3, school: 'Conjuração', castingTime: '1 ação', range: '27 metros (90 pés)', duration: 'Até 1 minuto', concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { saveStat: 'CON', saveEffect: 'negate', attackType: 'save' }, description: 'Gás podre 6m obscurece pesadamente a região. Criatura (TR CONSTITUIÇÃO) que falhar não pode fazer nada no turno, gastando tossindo violentamente enjoada.', classes: ['Bardo', 'Mago'] },
  { id: 'tongues', name: 'Idiomas (Tongues)', englishName: 'Tongues', level: 3, school: 'Adivinhação', castingTime: '1 ação', range: 'Toque', duration: '1 hora', concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { attackType: 'utility' }, description: 'Criatura tocada fala fluentemente qualquer idioma que o ser na frente dele saiba (se o outro tiver linguagem) e as pessoas lhe compreendem de volta.', classes: ['Bardo', 'Clérigo', 'Feiticeiro', 'Bruxo', 'Mago'] },
  { id: 'vampiric-touch', name: 'Toque Vampírico (Vampiric Touch)', englishName: 'Vampiric Touch', level: 3, school: 'Necromancia', castingTime: '1 ação', range: 'Toque', duration: 'Até 1 minuto', concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false, raw: 'V, S' }, damageSave: { damageDice: '3d6', damageType: 'Necrótico', attackType: 'melee_spell' }, description: 'Bate num alvo perto pra causar 3d6 necróticos, E O CONJURADOR SE CURA 50% DA QUANTIDADE DADA. Enquanto concentrado, repita ataques bônus nos turnos para mais roubo.', classes: ['Bruxo', 'Mago'] },
  { id: 'water-breathing', name: 'Respiração Aquática (Water Breathing)', englishName: 'Water Breathing', level: 3, school: 'Transmutação', castingTime: '1 ação', range: '9 metros (30 pés)', duration: '24 horas', concentration: false, ritual: true, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { attackType: 'utility' }, description: 'Até dez (10) criaturas voluntárias ganham passivamente habilidade anfíbia total para respirar debaixo dágua (e manter falar fluente sem rolagens).', classes: ['Druida', 'Patrulheiro', 'Feiticeiro', 'Mago'] },
  { id: 'water-walk', name: 'Andar na Água (Water Walk)', englishName: 'Water Walk', level: 3, school: 'Transmutação', castingTime: '1 ação', range: '9 metros (30 pés)', duration: '1 hora', concentration: false, ritual: true, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { attackType: 'utility' }, description: 'Até 10 criaturas tocam o lago, lama, areia de osso ou líquido violento perigoso (lava - toma calor porem nao afunda) e correm sólido pela superfície por 1h.', classes: ['Clérigo', 'Druida', 'Patrulheiro'] },
  { id: 'wind-wall', name: 'Muralha de Vento (Wind Wall)', englishName: 'Wind Wall', level: 3, school: 'Evocação', castingTime: '1 ação', range: '36 metros (120 pés)', duration: 'Até 1 minuto', concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, raw: 'V, S, M' }, damageSave: { damageDice: '3d8', damageType: 'Contundente', saveStat: 'STR', saveEffect: 'half', attackType: 'save' }, description: 'Escudo em Muralha opressora 15m de vendaval. Anula gases, pássaros. E flechas NÃO MÁGICAS são defletidas 100% que passarem pelo tufão. (3d8 Dano aos que estão ali na conjuração inicial com TR Força).', classes: ['Druida', 'Patrulheiro'] }
];
