import { SRDItem } from './types';

export const BATCH_11_WONDROUS: SRDItem[] = [
  // Amuletos
  {
    id: 'amulet-of-health',
    name: 'Amuleto de Saúde',
    englishName: 'Amulet of Health',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Um colar mágico que eleva passivamente a robustez da sua biologia. Sua Constituição fixa-se brutalmente em 19. Ignora se sua saúde básica já for superior.',
    value: '4.000 PO',
    weight: 1,
  },
  {
    id: 'amulet-of-proof-against-detection-and-location',
    name: 'Amuleto de Proteção contra Detecção e Localização',
    englishName: 'Amulet of Proof against Detection and Location',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Colar furtivo contra mágicas de adivinhação. Enquanto usá-lo, feitiços espiões, de radar ou telepatia que tentem saber sua posição/identidade automática te ignoram e falham.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'amulet-of-the-planes',
    name: 'Amuleto dos Planos',
    englishName: 'Amulet of the Planes',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Permite lançar a complexa "Mudança Planar" ativa sem restrição cósmica (Ação). No entanto, testes perigosos rolam (Inteligência CD 15). Se o jogador não superar, o portal joga todos num ponto imprevisível cruel (aleatório) no próprio alvo planar ou de volta pra cá aleatoriamente em perigo.',
    value: '25.000 PO',
    weight: 1,
  },
  {
    id: 'apparatus-of-the-crab',
    name: 'Aparato do Caranguejo (Kwalish)',
    englishName: 'Apparatus of the Crab',
    type: 'Item Mágico (Veículo)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: false,
    description: 'Veículo barril metálico anfíbio gnomo/Artífice que vira um mech no formato caranguejo armadurado invulnerável nas garras, operado por níveis de alavancas internas imunes ao calor e ataques profundos aquáticos até altas 360m mar abissal abismos. CA gigantesca blindada base.',
    value: '85.000 PO',
    weight: 500,
  },
  // Bolsas Mágicas
  {
    id: 'bag-of-beans',
    name: 'Saco de Feijões',
    englishName: 'Bag of Beans',
    type: 'Item Mágico (Bolsa)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Saco mágico de lona suja e grossa pesada; se plantados nos solos férteis orgânicos, explodem com aleatoriedade absoluta arcana caótica 1 min depois produzindo aberrações incríveis: Pirâmides no chão, Monstros amigáveis letais e árvores que expelem fruta cega letal dependendo da pura sorte e rolagem 1d100 da semente atirada na terra com água.',
    value: '5.000 PO',
    weight: 1,
  },
  {
    id: 'bag-of-devouring',
    name: 'Mochila Devoradora',
    englishName: 'Bag of Devouring',
    type: 'Item Mágico (Bolsa Amaldiçoada)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Cópia ilusória e hostil dimensional simulada de Bag of holding; É literalmente um ser místico extra-planar na ponta engolidora faminta abissal disfarçado. Tem a alta tendência furtiva macabra diária de tragar a mão que a guarda, ou rasgar vivos metade criaturas aprisionadas/guardadas ou pessoas arremessadas ao fundo ácido para digestão em planos de puro escuro.',
    value: '10.000 PO',
    weight: 15,
  },
  {
    id: 'bag-of-holding',
    name: 'Mochila de Carga',
    englishName: 'Bag of Holding',
    type: 'Item Mágico (Bolsa)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Clássico D&D. Contém um mini semi-plano interno invisível expansivo para portar gigantescas até (225 KG absolutos puros, ou 1.8 Metros cúbicos puros volumétricos máximos da base no poço). Pesará para fora nas alças 7.5 Kg travados sem variar independentemente. Ser colocada dentro de qualquer buraco negro igual ou saco Místico rasga o tecido sugando em colapso planar perigoso 3 metros de área total num buraco interdimensional irreversível letal limpo absoluto de vazio.',
    value: '500 PO',
    weight: 15,
  },
  {
    id: 'bag-of-tricks',
    name: 'Saco de Truques (Sortido)',
    englishName: 'Bag of Tricks',
    type: 'Item Mágico (Bolsa)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Puxe uma "bola de pelúcia mágica" da bolsa misteriosa felpuda ao dia (Max 3 usos totais) atirando pra longe (6 metros base). Magicamente vira animais da tabela base cor correspondente (Urso gigante guerreiro/Ratos/leões) que duram toda a madrugada combatendo sendo leais e letais pelo grupo em turno isolado mágico passivo aliado vivo obediente.',
    value: '500 PO',
    weight: 1,
  },
  // Livros de Atributo Maximo
  {
    id: 'manual-of-bodily-health',
    name: 'Manual da Saúde Corporal',
    englishName: 'Manual of Bodily Health',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Passando 48 h estudando rigoroso sua leitura complexa alquímica mágica de base nutricional arcana no mês ativo, a magia se esvai absoluta fixando permanentemente p/ vida o leitor somando +2 inato final no puro status de Constituição base, E eleva os novos patamares também p/ base Teto Limite Máximo da CON do Herói.',
    value: '50.000 PO',
    weight: 5,
  },
  {
    id: 'manual-of-gainful-exercise',
    name: 'Manual do Exercício Benéfico',
    englishName: 'Manual of Gainful Exercise',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'A leitura das técnicas marciais supremas perdidas no tempo, se aplicada em 48h (Dedilhado físico + mente mágico) no ciclo. O leitor subitamente encarna força muscular absurda orgânica sem magia, garantindo um super permanente fixo sem elo extra de +2 no número final fixo da pura (Força bruta/STR) +2 também de expansão limite teto.',
    value: '50.000 PO',
    weight: 5,
  },
  {
    id: 'manual-of-quickness-of-action',
    name: 'Manual da Rapidez de Ação',
    englishName: 'Manual of Quickness of Action',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Um livro sobre os caminhos celestiais absolutos da fluidez motora pura mística corporal. Requer dias (48h densas totais) de estudo marcial sombrio ou iluminado pra consumir a aura do livro de vez sumindo na alma, ganhando eternamente +2 direto e absoluto mágico em Destreza (E expansão teto máximo permanente da Dex base tbm global +2 na ficha).',
    value: '50.000 PO',
    weight: 5,
  },
  {
    id: 'tome-of-clear-thought',
    name: 'Tomo do Pensamento Claro',
    englishName: 'Tome of Clear Thought',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Livro sagrado mental universal cheio das memórias perdidas matemáticas e místicas celestiais. Exige os densos totais turnos (48h completas puras lidas fixadas no prazo rotineiro) para assimilar a pura magia cerebral permanente imbuída da mente de +2 pontos puros totais fixos inquebráveis contínuos vitalícios de Inteligência base (E somados os tetos ampliando sua barra).',
    value: '50.000 PO',
    weight: 5,
  },
  {
    id: 'tome-of-leadership-and-influence',
    name: 'Tomo da Liderança e Influência',
    englishName: 'Tome of Leadership and Influence',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Tratado mítico de domínios psicológicos encantados reais da oratória, o tom perfeito no estudo divino focado mágico das (48h absolutas lidas totais esparsas ao longo semanal) te garante +2 contínuo, irrestrito mágico total puro vitalício pra vida no seu Carisma nobreza inato final e expandirá permanentemente a barra Teto max Charisma global +2.',
    value: '50.000 PO',
    weight: 5,
  },
  {
    id: 'tome-of-understanding',
    name: 'Tomo da Compreensão',
    englishName: 'Tome of Understanding',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Filosofias arcanas místicas druídicas divinas pesadas perdidas universais antigas para alcançar paz, ao consumir 48 horas intensas da magia da mente pura nos conhecimentos cósmicos celestes totais no texto místico. Recebe instantaneamente em vida global definitiva permanentemente um valor absoluto final inquebrável +2 direto sabedoria fixa + (Quebra no cap teto total).',
    value: '50.000 PO',
    weight: 5,
  },
  {
    id: 'manual-of-golems',
    name: 'Manual dos Golems',
    englishName: 'Manual of Golems',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Requer Magia. Contém rituais absurdos divinos supremos proibidos absolutos totais universais precisos fixos alquímicos puros construtores. Gastando tempo massivo e Ouro extremo mágico colossal no criador, você levanta Golem puro leal (Argila 65 dias/Pedra 90 dias/Ferro pesado blindado 120 dias) inanimado virando sentinela eterno submisso vivo absoluto em vida.',
    value: '30.000 PO',
    weight: 5,
  },
  // Bolas de Cristal e outros
  {
    id: 'crystal-ball',
    name: 'Bola de Cristal',
    englishName: 'Crystal Ball',
    type: 'Item Mágico (Bola de Cristal)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Uma esfera absoluta e clássica perfeita total de Quartzo ou rubi de observação arcana ilimitada clarividente. Conjure mágica pura observadora de clarividência total da "Vidência" com DC salvar difícil 17 mágica livre (Sem nenhum limite cast ou poeira gastos na vida).',
    value: '20.000 PO',
    weight: 3,
  },
  {
    id: 'crystal-ball-of-telepathy',
    name: 'Bola de Cristal de Telepatia',
    englishName: 'Crystal Ball of Telepathy',
    type: 'Item Mágico (Bola de Cristal)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Conjura Vidência à vontade. Enquanto usar ela pode se conectar com a criatura vista projetando telepatia, ou castar a intrusiva Sugestão letal psíquica pelo feixe canalizador através dos longos cosmos pelo globo telepata.',
    value: '50.000 PO',
    weight: 3,
  },
  {
    id: 'decanter-of-endless-water',
    name: 'Decantador de Água Infinita',
    englishName: 'Decanter of Endless Water',
    type: 'Item Mágico (Frasco)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Uma rolha mágica de garrafão clássico que se conecta no fundo ao plano elemental infinito total puro da água. Retire e exija a palavra da vazão absoluta atirando jatos totais imensos e fluxos rápidos: Bica (Fluxo lento), Fonte (15 litros doces) ou o formidável e fatal Geyser total hídrico (100 litros força extrema, CD 13 força para não empurrar bruscamente criaturas longes e dar nocaute destrutivo).',
    value: '500 PO',
    weight: 2,
  },
  {
    id: 'deck-of-many-things',
    name: 'Baralho de Muitas Coisas',
    englishName: 'Deck of Many Things',
    type: 'Item Mágico (Baralho)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: false,
    description: 'O artefato místico absoluto mais arriscado, caótico letal global perigoso fixo irrestrito mortal destruidor formidável puro caótico formidável místico celestial divino de todos puros. Tem 13/22 cartões supremos imprevisíveis universais: Declare quantas cartas divinas místicas ou letais demoníacas vai puxar nos próximos cegos instantes absolutos contínuos vitais (Consequências podem te sumir do plano, destruir tesouros totais, subir Níveis celestiais inteiros supremos fixos da XP total final e até conceder Desejos Onipotentes diretos puríssimos eternamente).',
    value: '250.000 PO',
    weight: 1,
  },
  {
    id: 'deck-of-illusions',
    name: 'Baralho das Ilusões',
    englishName: 'Deck of Illusions',
    type: 'Item Mágico (Baralho)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Um baralho total 34 cartas fidedignas pintadas misteriosas. Jogar as peças em combate proietta miragens 3D totais holográficas ilusórias mágicas inanimadas complexas ou em movimentos puros (Guerreiros, Gigantes totais, Red Dragon supremo mágico) baseados na Naipe sorteado vivo formidável, desaparecem só com a real interação de inteligência inimiga percebendo ser falso arcano. ',
    value: '500 PO',
    weight: 1,
  }
];
