import { SRDSpell } from './types';

export const BATCH_7_SPELLS: SRDSpell[] = [
  {
    id: 'demiplane',
    name: 'Semiplano (Demiplane)',
    englishName: 'Demiplane',
    level: 8,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'area', shape: 'wall', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Portal' },
    damageSave: { attackType: 'utility' },
    description: 'Cria uma porta sombria que leva a um semiplano particular fechado (um quarto estéril de madeira de 9x9m vazio). Útil para estocar itens imensos ou esconder exércitos. Acabando o feitiço, a porta cessa, mas conteúdo não some.',
    classes: ['Bruxo', 'Mago']
  },
  {
    id: 'detect-evil-and-good',
    name: 'Detectar o Bem e Mal (Detect Evil and Good)',
    englishName: 'Detect Evil and Good',
    level: 1,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 9, sizeUnit: 'm', formatted: 'Raio de 9m' },
    damageSave: { attackType: 'utility' },
    description: 'Detecta a localização exata de qualquer: Aberração, Celestial, Elemental, Fada, Infernal (Demônio/Diabo) ou Morto-Vivo num alcance de 9 metros (E sabe se há terra sagrada profanada num altar).',
    classes: ['Clérigo', 'Paladino']
  },
  {
    id: 'dispel-evil-and-good',
    name: 'Dissipar o Bem e Mal (Dispel Evil and Good)',
    englishName: 'Dispel Evil and Good',
    level: 5,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um sino pó sagrado', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Os seres listados em Detectar Mal/Bem recebem desvantagem atacando você. AÇÃO BÔNUS: quebrar o feitiço forçando banimento, batendo neles corpo-a-corpo: TR Carisma, falhou Banido no ato pro plano infernal. (Ou use pra dissipar charm destes seres em área aliados)',
    classes: ['Clérigo', 'Paladino']
  },
  {
    id: 'divination',
    name: 'Adivinhação (Divination)',
    englishName: 'Divination',
    level: 4,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'incenso oferta puros valendo 25 PO consumidos', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Mecânica ritual. Faça sua Pergunta para um Emissário da sua Deidade ou Força Divina a respeito de UM ÚNICO evento focado que ocorrerá no máximo até os próximos 7 dias no mundo, ganhando dicas verídicas, em enigma.',
    classes: ['Clérigo']
  },
  {
    id: 'divine-favor',
    name: 'Favor Divino (Divine Favor)',
    englishName: 'Divine Favor',
    level: 1,
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: 'Pessoal',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { damageDice: '1d4', damageType: 'Radiante', attackType: 'utility' },
    description: 'Sua prece divina engolfa a arma. Até acabar o feitiço, todos os seus acertos de armas mundanas somam brutais 1d4 Danos de energia Radiante (Puro).',
    classes: ['Paladino']
  },
  {
    id: 'dominate-beast',
    name: 'Dominar Besta (Dominate Beast)',
    englishName: 'Dominate Beast',
    level: 4,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Fera' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Você instaura poder sobre a criatura, dominando o intelecto da fera. Idêntica a Dominar Pessoa.',
    classes: ['Druida', 'Feiticeiro']
  },
  {
    id: 'dominate-monster',
    name: 'Dominar Monstro (Dominate Monster)',
    englishName: 'Dominate Monster',
    level: 8,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Qualquer Criatura' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Assume a mente de QUALQUER INIMIGO, até o dragão mais formidável do apocalipse se ele falhar TR Sabedoria. Telepatia plena, comandos totais para usar hálito de fogo, garras etc. Acaba se tomar um dano acidental e passar num novo teste re-feito!',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'enthrall',
    name: 'Cativar (Enthrall)',
    englishName: 'Enthrall',
    level: 2,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 18, sizeUnit: 'm', formatted: 'Raio de 18m' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Tece palavras enfeitiçantes focando TODOS ali no 18m para te prestarem total atenção cativada (Desvantagem no teste de percepção para notar aliados / coisas além do show) até acabar.',
    classes: ['Bardo', 'Bruxo']
  },
  {
    id: 'eyebite',
    name: 'Ataque Visual (Eyebite)',
    englishName: 'Eyebite',
    level: 6,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Pessoal (Visão 18m)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura por turno' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Teus olhos sangram fumaça mágica sombria negra. Todo turno você mira 1 inimigo (TR SAB): Amedrontado (corre p/ longe), Doente (desvantagem) ou Dormir (Sono místico até acordarem ele).',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'fabricate',
    name: 'Fabricar (Fabricate)',
    englishName: 'Fabricate',
    level: 4,
    school: 'Transmutação',
    castingTime: '10 minutos',
    range: '36 metros (120 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Móveis Armas (1.5m)' },
    damageSave: { attackType: 'utility' },
    description: 'Converte matéria bruta prima de árvores para uma Ponte gigantesca fina (Cubo de mat. 1,5m em geral vira produto manufaturado, sem magia imbutida). Se virar arma requere proficiência de ferreiro em armas.',
    classes: ['Mago']
  },
  {
    id: 'false-life',
    name: 'Vida Falsa (False Life)',
    englishName: 'False Life',
    level: 1,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pingo alcatrão', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Imbui você numa vitalidade rústica necromântica necrosada. Recebe 1d4 + 4 PONTOS DE VIDA TEMPORÁRIOS que duram por 1 hora agindo como escuto de dano preventivo inicial. ',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'find-steed',
    name: 'Encontrar Montaria (Find Steed)',
    englishName: 'Find Steed',
    level: 2,
    school: 'Conjuração',
    castingTime: '10 minutos',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Montaria (Corcel Mágico)' },
    damageSave: { attackType: 'utility' },
    description: 'Você conjura um corcel (Cavalo, Mastim, Alce) com ligação mental com você até 1,6 km de dist, 6 INT inteligência e falando seu idioma passivo divino leal combatente companheiro sem temer morte montável.',
    classes: ['Paladino']
  },
  {
    id: 'find-traps',
    name: 'Encontrar Armadilhas (Find Traps)',
    englishName: 'Find Traps',
    level: 2,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 36, sizeUnit: 'm', formatted: 'Visão Imediata (36m)' },
    damageSave: { attackType: 'utility' },
    description: 'Te dá consciência total se há algo arquitetado especificamente intencional pra ser Armadilha escondido, sabe onde está genérico sem dizer o efeito que faz a armadilha mas ciente e atento (não descobre efeitos naturais perigos climáticos não pensados para tal por humanos etc).',
    classes: ['Clérigo', 'Druida', 'Patrulheiro']
  },
  {
    id: 'flaming-sphere',
    name: 'Esfera Flamejante (Flaming Sphere)',
    englishName: 'Flaming Sphere',
    level: 2,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pó sebo carvão enxofre bosta', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Esfera (1.5m de raio)' },
    damageSave: { damageDice: '2d6', damageType: 'Fogo', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Surge uma bola de fogo em 18m. Quem bater / começar o turno adjacente toma TR Destreza ou 2d6 Fogo (Metade se sucesso). Como AÇÃO BÔNUS o conjurador pode empurrá-la 9m rolando contra as criaturas atropeladas punindo com 2d6 Fogo em TR!',
    classes: ['Druida', 'Mago']
  },
  {
    id: 'forbiddance',
    name: 'Proibição (Forbiddance)',
    englishName: 'Forbiddance',
    level: 6,
    school: 'Abjuração',
    castingTime: '10 minutos',
    range: 'Toque',
    duration: '1 dia',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'um pingo suco sangue de divindade de pó diamante 1.000 PO e rubi sagrado embutido chão', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 3600, sizeUnit: 'm', formatted: 'Área Colossal de 40.000 pés²' },
    damageSave: { damageDice: '5d10', damageType: 'Radiante', attackType: 'utility' },
    description: 'Bênção Suprema numa igreja gigante impedindo todo e qualquer Teletransporte / viagem dimensional local e ferindo Brutalmente 5d10 Dano Radiante pra qualquer diabo celestial maligno inimigo listado profano que pise na área do templo!',
    classes: ['Clérigo']
  }
];
