import { SRDSpell } from './types';

export const BATCH_2_SPELLS: SRDSpell[] = [
  // NÍVEL 1
  {
    id: 'alarm',
    name: 'Alarme (Alarm)',
    englishName: 'Alarm',
    level: 1,
    school: 'Abjuração',
    castingTime: '1 minuto',
    range: '9 metros (30 pés)',
    duration: '8 horas',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pequeno sino e um pedaço de fio de prata fino', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 6, sizeUnit: 'm', formatted: 'Cubo de 6m' },
    damageSave: { attackType: 'utility' },
    description: 'Você cria um alarme contra intrusos. Você escolhe uma porta, uma janela ou uma área dentro do alcance que não seja maior que um cubo de 6 metros. O alarme soará se uma criatura Miúda ou maior tocar ou entrar na área protegida sem falar a senha. O alarme pode ser mental (um silvo na sua mente) ou audível (um som de sino que pode ser ouvido a até 18 metros).',
    classes: ['Patrulheiro', 'Mago']
  },
  {
    id: 'comprehend-languages',
    name: 'Compreender Idiomas (Comprehend Languages)',
    englishName: 'Comprehend Languages',
    level: 1,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma pitada de fuligem e sal', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Pela duração, você compreende o significado literal de qualquer idioma falado que você ouvir. Você também compreende qualquer idioma escrito que vir, mas deve estar tocando a superfície onde as palavras estão escritas. Leva cerca de 1 minuto para ler uma página.',
    classes: ['Bardo', 'Bruxo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'detect-magic',
    name: 'Detectar Magia (Detect Magic)',
    englishName: 'Detect Magic',
    level: 1,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: true,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 9, sizeUnit: 'm', formatted: 'Esfera de 9m ao seu redor' },
    damageSave: { attackType: 'utility' },
    description: 'Pela duração, você percebe a presença de magia a até 9 metros de você. Se você sentir magia dessa forma, pode usar sua ação para ver uma aura fraca ao redor de qualquer criatura ou objeto visível na área que carrega magia, e você descobre sua escola de magia, se houver. A magia pode penetrar a maioria das barreiras, mas é bloqueada por 30 cm de pedra, 2,5 cm de metal comum, uma fina folha de chumbo ou 90 cm de madeira ou terra.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Feiticeiro', 'Paladino', 'Patrulheiro', 'Mago']
  },
  {
    id: 'detect-poison-and-disease',
    name: 'Detectar Veneno e Doença (Detect Poison and Disease)',
    englishName: 'Detect Poison and Disease',
    level: 1,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma folha de teixo', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 9, sizeUnit: 'm', formatted: 'Esfera de 9m ao seu redor' },
    damageSave: { attackType: 'utility' },
    description: 'Pela duração, você percebe a presença e a localização de venenos, criaturas venenosas e doenças a até 9 metros de você. Você também identifica o tipo de veneno, criatura venenosa ou doença em cada caso.',
    classes: ['Clérigo', 'Druida', 'Paladino', 'Patrulheiro']
  },
  {
    id: 'disguise-self',
    name: 'Disfarçar-se (Disguise Self)',
    englishName: 'Disguise Self',
    level: 1,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Você faz com que você mesmo – incluindo suas roupas, armaduras, armas e outros pertences em sua pessoa – pareça diferente até a magia acabar ou você usar sua ação para dispensá-la. Você pode parecer até 30 cm mais alto ou mais baixo, magro, gordo ou qualquer outra proporção. Você não pode alterar seu tipo corporal fundamental. As mudanças são apenas visuais; o disfarce falha ao toque.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'entangle',
    name: 'Constrição (Entangle)',
    englishName: 'Entangle',
    level: 1,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '27 metros (90 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'square', sizeValue: 6, sizeUnit: 'm', formatted: 'Quadrado de 6m' },
    damageSave: { saveStat: 'STR', saveEffect: 'negate', attackType: 'save' },
    description: 'Plantas que se enroscam brotam do chão em um quadrado de 6 metros no alcance. Para a duração, essas plantas transformam o chão na área em terreno difícil. Uma criatura que esteja na área quando a magia é conjurada deve passar num teste de resistência de Força ou ficará Presa (Restrained). A criatura pode usar sua ação para realizar um teste de Força contra a CD da magia para se soltar.',
    classes: ['Druida']
  },
  {
    id: 'expeditious-retreat',
    name: 'Recuo Acelerado (Expeditious Retreat)',
    englishName: 'Expeditious Retreat',
    level: 1,
    school: 'Transmutação',
    castingTime: '1 ação bônus',
    range: 'Pessoal',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Esta magia permite que você se mova a um ritmo incrível. Quando você a conjura e em cada um de seus turnos, até a magia acabar, você pode realizar a ação de Disparada como uma ação bônus.',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'faerie-fire',
    name: 'Fogo das Fadas (Faerie Fire)',
    englishName: 'Faerie Fire',
    level: 1,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 6, sizeUnit: 'm', formatted: 'Cubo de 6m' },
    damageSave: { saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Cada objeto em um cubo de 6 metros no alcance é delineado por luz azul, verde ou violeta (à sua escolha). Qualquer criatura na área quando a magia for conjurada também é delineada em luz se falhar num TR de Destreza. Pela duração, objetos e criaturas afetadas emitem penumbra num raio de 3 metros. Qualquer jogada de ataque contra uma criatura afetada tem Vantagem se o atacante puder ver o alvo, e a criatura não se beneficia de estar invisível.',
    classes: ['Bardo', 'Druida']
  },
  {
    id: 'feather-fall',
    name: 'Queda Suave (Feather Fall)',
    englishName: 'Feather Fall',
    level: 1,
    school: 'Transmutação',
    castingTime: '1 reação',
    range: '18 metros (60 pés)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: true, materialsDescription: 'uma pequena pena ou penugem', raw: 'V, M' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 5 criaturas caindo' },
    damageSave: { attackType: 'utility' },
    description: 'Conjure esta magia quando você ou uma criatura até 18 metros de você cair. Escolha até cinco criaturas caindo no alcance. A taxa de queda da criatura é reduzida para 18 metros por rodada até o fim da magia. Se a criatura aterrissar antes do fim da magia, ela não sofre dano de queda e pode aterrissar de pé.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'find-familiar',
    name: 'Encontrar Familiar (Find Familiar)',
    englishName: 'Find Familiar',
    level: 1,
    school: 'Conjuração',
    castingTime: '1 hora',
    range: '3 metros (10 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: '10 PO em carvão, incenso e ervas, que devem ser consumidos no fogo', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'special', formatted: '1 Familiar' },
    damageSave: { attackType: 'utility' },
    description: 'Você obtém o serviço de um familiar, um espírito que toma uma forma animal. Você pode fazer seu familiar ver, ouvir e se mover através do seu comando. Em combate, ele rola sua própria iniciativa, mas não pode atacar. Ele obedece a seus comandos e pode conjurar magias de Toque que você transmitir por ele.',
    classes: ['Mago']
  },
  {
    id: 'fog-cloud',
    name: 'Névoa Obscurecente (Fog Cloud)',
    englishName: 'Fog Cloud',
    level: 1,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 6, sizeUnit: 'm', formatted: 'Esfera de 6m de raio' },
    damageSave: { attackType: 'utility' },
    description: 'Você cria uma esfera de 6 metros de raio de névoa centrada em um ponto no alcance. A esfera se espalha dobrando cantos, e sua área é fortemente obscurecida. Ela dura pela duração ou até um vento de velocidade moderada ou maior (pelo menos 16 km/h) a dispersar.',
    higherLevels: 'Se conjurada com um espaço de magia de 2º nível ou superior, o raio da névoa aumenta em 6 metros para cada nível acima do 1º.',
    classes: ['Druida', 'Patrulheiro', 'Feiticeiro', 'Mago']
  },
  {
    id: 'grease',
    name: 'Área Escorregadia (Grease)',
    englishName: 'Grease',
    level: 1,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pouco de banha de porco ou manteiga', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'square', sizeValue: 3, sizeUnit: 'm', formatted: 'Quadrado de 3m' },
    damageSave: { saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Uma graxa escorregadia cobre o chão num quadrado de 3 metros centrado num ponto no alcance. O chão na área é terreno difícil. Quando a graxa surge, cada criatura de pé nela deve ser bem-sucedida num TR de Destreza ou cairá Prone (Caída). Uma criatura que entra ou termina seu turno na área também deve ser bem-sucedida no teste de resistência ou cai Caída.',
    classes: ['Mago']
  },
  {
    id: 'identify',
    name: 'Identificar (Identify)',
    englishName: 'Identify',
    level: 1,
    school: 'Adivinhação',
    castingTime: '1 minuto',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'uma pérola de no mínimo 100 PO e uma pena de coruja', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Objeto ou Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Você escolhe um objeto ou uma criatura durante a conjuração. Se for um item mágico, você aprende suas propriedades, como usá-las, se ele requer sintonia e quantas cargas ele tem, se aplicável. Você descobre se há magias afetando o item e quais são elas. Se o alvo for uma criatura, você descobre que magias estão a afetando atualmente, se houver.',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'jump',
    name: 'Salto (Jump)',
    englishName: 'Jump',
    level: 1,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma perna de gafanhoto traseira', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura. A distância dos saltos dela é triplicada até a magia acabar.',
    classes: ['Druida', 'Patrulheiro', 'Feiticeiro', 'Mago']
  },
  {
    id: 'longstrider',
    name: 'Passo Largo (Longstrider)',
    englishName: 'Longstrider',
    level: 1,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma pitada de terra', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura. O deslocamento do alvo aumenta em 3 metros até a magia acabar.',
    higherLevels: 'Se você conjurar usando um espaço de 2º nível ou superior, você pode mirar uma criatura adicional por nível acima do 1º.',
    classes: ['Bardo', 'Druida', 'Patrulheiro', 'Mago']
  },
  {
    id: 'protection-from-evil-and-good',
    name: 'Proteção contra o Bem e o Mal (Protection from Evil and Good)',
    englishName: 'Protection from Evil and Good',
    level: 1,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, consumed: true, materialsDescription: 'água benta ou prata em pó, que a magia consome', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Até a magia acabar, uma criatura voluntária que você toca é protegida contra certos tipos de criaturas: aberrações, celestiais, elementais, fadas, íncubos e mortos-vivos. A proteção garante: as criaturas não podem encantar, assustar ou possuir o alvo. Jogadas de ataque contra o alvo feitas por essas criaturas têm desvantagem.',
    classes: ['Clérigo', 'Paladino', 'Bruxo', 'Mago']
  },
  {
    id: 'ray-of-sickness',
    name: 'Raio Adoecente (Ray of Sickness)',
    englishName: 'Ray of Sickness',
    level: 1,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '2d8', damageType: 'Veneno', saveStat: 'CON', saveEffect: 'negate', attackType: 'ranged_spell' },
    description: 'Um raio de energia esverdeada nauseante dispara em direção a uma criatura. Faça um ataque com magia à distância contra o alvo. Num acerto, o alvo sofre 2d8 de dano de veneno e deve passar num TR de Constituição ou fica Envenenado (Poisoned) até o final de seu próximo turno.',
    higherLevels: 'Dano aumenta em 1d8 para cada nível do espaço acima do 1º.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'sanctuary',
    name: 'Santuário (Sanctuary)',
    englishName: 'Sanctuary',
    level: 1,
    school: 'Abjuração',
    castingTime: '1 ação bônus',
    range: '9 metros (30 pés)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pequeno espelho de prata', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'utility' },
    description: 'Você protege uma criatura dentro do alcance. Se alguém quiser atacar a criatura protegida diretamente, deve ser bem-sucedida num TR de Sabedoria. Numa falha, deve mirar em outro ou desperdiçar o ataque. A magia termina se o alvo atacar ou conjurar uma magia que afete inimigos.',
    classes: ['Clérigo']
  },
  {
    id: 'shield-of-faith',
    name: 'Escudo da Fé (Shield of Faith)',
    englishName: 'Shield of Faith',
    level: 1,
    school: 'Abjuração',
    castingTime: '1 ação bônus',
    range: '18 metros (60 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pequeno texto sagrado e um fio dourado', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Um campo cintilante mágico aparece e envolve uma criatura no alcance. Até o fim da magia, a CA do alvo recebe um bônus de +2.',
    classes: ['Clérigo', 'Paladino']
  },
  {
    id: 'sleep',
    name: 'Sono (Sleep)',
    englishName: 'Sleep',
    level: 1,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '27 metros (90 pés)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pouco de areia, pétalas de rosa ou grilos', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 6, sizeUnit: 'm', formatted: 'Esfera de 6m de raio' },
    damageSave: { damageDice: '5d8', damageType: 'HP Afetado', attackType: 'utility' },
    description: 'Magia afeta as criaturas em ordem crescente dos seus PV atuais (ignorando criaturas Inconscientes). Role 5d8; o total é quantos Pontos de Vida de criaturas a magia pode afetar. Criaturas afetadas ficam Inconscientes por 1 minuto. A magia não afeta mortos-vivos ou criaturas imunes a Encantamento.',
    higherLevels: 'Se usar um espaço de 2º nível ou superior, você rola 2d8 adicionais para cada nível acima do 1º.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  // NÍVEL 2
  {
    id: 'acid-arrow',
    name: 'Seta Ácida (Acid Arrow)',
    englishName: "Melf's Acid Arrow",
    level: 2,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '27 metros (90 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pó de folha de ruibarbo e um estômago de víbora', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '4d4', damageType: 'Ácido', attackType: 'ranged_spell' },
    description: 'Uma seta de ácido voa para um alvo no alcance. Numa jogada de ataque bem-sucedida, o alvo sofre 4d4 de dano de ácido imediatamente e mais 2d4 de dano de ácido no final de seu próximo turno. Num erro, recebe apenas metade do dano inicial e nenhum dano posterior.',
    higherLevels: 'O dano (tanto inicial quanto secundário) aumenta em 1d4 por nível acima do 2º.',
    classes: ['Mago']
  },
  {
    id: 'alter-self',
    name: 'Alterar-se (Alter Self)',
    englishName: 'Alter Self',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Você assume uma forma diferente. Escolha uma das seguintes opções: Adaptação Aquática (você respira embaixo d’água e recebe deslocamento de natação); Aparência Alterada (você altera como se parece visual e fisicamente); Armas Naturais (você cresce garras, presas ou chifres que são armas mágicas desarmadas com bônus de +1, causando 1d6 de dano).',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'blindness-deafness',
    name: 'Cegueira/Surdez (Blindness/Deafness)',
    englishName: 'Blindness/Deafness',
    level: 2,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { saveStat: 'CON', saveEffect: 'negate', attackType: 'save' },
    description: 'Você pode cegar ou ensurdecer um oponente. O alvo deve ser bem-sucedido num TR de Constituição ou ficará Cego ou Surdo (à sua escolha) pela duração. O alvo pode repetir o teste no final de cada um de seus turnos.',
    higherLevels: 'Você pode afetar 1 alvo adicional por nível acima do 2º.',
    classes: ['Bardo', 'Clérigo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'blur',
    name: 'Borrão (Blur)',
    englishName: 'Blur',
    level: 2,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Seu corpo se torna borrado e turvo. Pela duração, qualquer criatura tem Desvantagem nas jogadas de ataque contra você. Atacantes com visão verdadeira ou que não usam visão anulam esse efeito.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'continual-flame',
    name: 'Chama Contínua (Continual Flame)',
    englishName: 'Continual Flame',
    level: 2,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Permanente',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'pó de rubi valendo pelo menos 50 PO, que é consumido', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Objeto' },
    damageSave: { attackType: 'utility' },
    description: 'Uma chama mágica sem calor é gerada em um objeto, iluminando como uma tocha (luz plena 6m, penumbra 6m). O efeito parece chamas normais, mas não queima nem emite calor. A chama pode ser coberta.',
    classes: ['Clérigo', 'Mago']
  },
  {
    id: 'darkness',
    name: 'Escuridão (Darkness)',
    englishName: 'Darkness',
    level: 2,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: false, material: true, materialsDescription: 'pêlo de morcego ou piche', raw: 'V, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 4.5, sizeUnit: 'm', formatted: 'Esfera de 4,5m de raio' },
    damageSave: { attackType: 'utility' },
    description: 'Escuridão mágica preenche a área no alcance. Criaturas com visão no escuro não enxergam nessa escuridão, e chamas não a iluminam. Uma magia de luz de 2º nível ou inferior não pode iluminá-la (é anulada se cruzar).',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'darkvision',
    name: 'Visão no Escuro (Darkvision)',
    englishName: 'Darkvision',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pouco de cenoura ou uma ágata', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Uma criatura tocada ganha visão no escuro com alcance de 18 metros pela duração.',
    classes: ['Druida', 'Patrulheiro', 'Feiticeiro', 'Mago']
  },
  {
    id: 'detect-thoughts',
    name: 'Detectar Pensamentos (Detect Thoughts)',
    englishName: 'Detect Thoughts',
    level: 2,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma peça de cobre', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 9, sizeUnit: 'm', formatted: 'Esfera de 9m ao seu redor' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'utility' },
    description: 'Pela duração, você pode ler os pensamentos de certas criaturas. Concentre sua mente em uma criatura a até 9 metros. Se ela tiver Inteligência de 3 ou menos, a magia falha. Você inicialmente lê os pensamentos superficiais, mas como ação, você pode aprofundar; a criatura deve realizar um TR de Sabedoria ou terá os pensamentos profundos revelados (e descobrirá que estão sendo lidos).',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'enhance-ability',
    name: 'Aprimorar Habilidade (Enhance Ability)',
    englishName: 'Enhance Ability',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pêlo ou pena de uma fera', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura. Escolha um dos seguintes aprimoramentos para a duração: Vantagem em testes de Força (Força de Touro), Vantagem em testes de Destreza (Graça de Gato e não sofre dano caindo até 6m), Vantagem em testes de Constituição (Vigor de Urso e +2d6 PV Temp), Vantagem em testes de Inteligência (Astúcia de Raposa), Vantagem em testes de Sabedoria (Sabedoria de Coruja), Vantagem em testes de Carisma (Esplendor de Águia).',
    higherLevels: 'Você pode visar 1 criatura adicional para cada nível de magia acima do 2º.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Feiticeiro']
  },
  {
    id: 'enlarge-reduce',
    name: 'Aumentar/Reduzir (Enlarge/Reduce)',
    englishName: 'Enlarge/Reduce',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pó de ferro', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { saveStat: 'CON', saveEffect: 'negate', attackType: 'save' },
    description: 'Você causa um aumento ou redução mágica do tamanho de uma criatura ou objeto. Alvos não voluntários podem realizar TR de Constituição para resistir. Aumentar: dobra tamanho físico, multiplicando peso por 8. Ganha Vantagem em Força e ataques causam +1d4 de dano. Reduzir: diminui pela metade, peso é dividido por 8. Desvantagem em Força e ataques causam -1d4 de dano.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'find-steed',
    name: 'Encontrar Montaria (Find Steed)',
    englishName: 'Find Steed',
    level: 2,
    school: 'Conjuração',
    castingTime: '10 minutos',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'special', formatted: '1 Montaria' },
    damageSave: { attackType: 'utility' },
    description: 'Você convoca um espírito que assume a forma de uma montaria excepcionalmente forte (como um corcel de guerra, pônei, camelo ou alce). Ela possui as estatísticas da fera escolhida e você forja um vínculo telepático (alcance 1,5 km). Magias que você conjura e que miram só em você também afetam a montaria se ela estiver a 1,5m de você.',
    classes: ['Paladino']
  },
  {
    id: 'find-traps',
    name: 'Encontrar Armadilhas (Find Traps)',
    englishName: 'Find Traps',
    level: 2,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 36, sizeUnit: 'm', formatted: 'Esfera de 36m' },
    damageSave: { attackType: 'utility' },
    description: 'Você sente a presença de qualquer armadilha dentro do alcance. A magia penetra na maioria das coberturas, mas falha no limite do seu campo de visão normal.',
    classes: ['Clérigo', 'Druida', 'Patrulheiro']
  },
  {
    id: 'flaming-sphere',
    name: 'Esfera Flamejante (Flaming Sphere)',
    englishName: 'Flaming Sphere',
    level: 2,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pouco de sebo, fósforo e ferro pulverizado', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Esfera de 1,5m' },
    damageSave: { damageDice: '2d6', damageType: 'Fogo', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Uma esfera de fogo de 1,5m de diâmetro surge. Qualquer criatura que terminar o turno a 1,5m da esfera ou for atropelada por ela sofre 2d6 de dano de Fogo (TR de Destreza p/ metade). Como ação bônus, você move a esfera até 9 metros. Se ela golpear uma criatura no deslocamento, ela para de andar nesse turno.',
    higherLevels: 'O dano aumenta em 1d6 por nível acima do 2º.',
    classes: ['Druida', 'Mago']
  },
  {
    id: 'gentle-repose',
    name: 'Repouso Tranquilo (Gentle Repose)',
    englishName: 'Gentle Repose',
    level: 2,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '10 dias',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'duas moedas de cobre', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Cadáver' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca um cadáver e preserva-o contra a decomposição por 10 dias. O cadáver não pode se tornar um morto-vivo e o tempo da magia não conta contra o limite de tempo de magias como Reviver os Mortos.',
    classes: ['Clérigo', 'Mago']
  },
  {
    id: 'gust-of-wind',
    name: 'Lufada de Vento (Gust of Wind)',
    englishName: 'Gust of Wind',
    level: 2,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Pessoal (linha de 18m)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma semente', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'line', sizeValue: 18, sizeUnit: 'm', formatted: 'Linha de 18m de compr. e 3m de larg.' },
    damageSave: { saveStat: 'STR', saveEffect: 'negate', attackType: 'save' },
    description: 'Uma linha de vento forte de 18 metros de comprimento e 3 metros de largura. Cada criatura que começar o turno ou entrar nela deve passar num TR Força ou é empurrada 4,5 metros. Custa 2 metros para cada 1 metro avançado ao vento.',
    classes: ['Druida', 'Feiticeiro', 'Mago']
  },
  {
    id: 'knock',
    name: 'Arrombar (Knock)',
    englishName: 'Knock',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Objeto' },
    damageSave: { attackType: 'utility' },
    description: 'Escolha um objeto trancado ou barricado que você possa ver a até 18 metros. A magia o destranca automaticamente. Se houver múltiplos cadeados, apenas um é destrancado. Gera um barulho extremamente alto, um estrondo que ecoa até 90 metros de distância.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'levitate',
    name: 'Levitação (Levitate)',
    englishName: 'Levitate',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pequeno fio de couro ou espira dourada atada num copo minúsculo', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura ou Objeto' },
    damageSave: { saveStat: 'CON', saveEffect: 'negate', attackType: 'save' },
    description: 'Você faz uma criatura ou um objeto solto de até 250 kg levitar no ar até 6 metros de altura. Uma criatura não voluntária tem direito a um TR de Constituição. O alvo paira e só pode se mover puxando ou empurrando objetos fixos, movendo seu deslocamento.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'locate-object',
    name: 'Localizar Objeto (Locate Object)',
    englishName: 'Locate Object',
    level: 2,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um galho com a forma da letra Y', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 300, sizeUnit: 'm', formatted: 'Esfera de 300m' },
    damageSave: { attackType: 'utility' },
    description: 'Descreva ou nomeie um objeto específico que lhe seja familiar ou geral (como "anel", "roupas"). Você sabe o sentido da localização do objeto e pode se aproximar dele se estiver dentro do raio de 300 metros.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Paladino', 'Patrulheiro', 'Mago']
  },
  {
    id: 'magic-mouth',
    name: 'Boca Mágica (Magic Mouth)',
    englishName: 'Magic Mouth',
    level: 2,
    school: 'Ilusão',
    castingTime: '1 minuto',
    range: '9 metros (30 pés)',
    duration: 'Até dissipada',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'um favo de mel pequeno e 10 PO de pó de jade, consumido pela magia', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Objeto' },
    damageSave: { attackType: 'utility' },
    description: 'Você imbuí uma mensagem verbal de até 25 palavras num objeto. Escolha uma circunstância visual ou audível para dispará-la. Quando isso ocorrer, uma boca mística aparece no objeto, repetindo as palavras com a exata entonação que você falou.',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'magic-weapon',
    name: 'Arma Mágica (Magic Weapon)',
    englishName: 'Magic Weapon',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação bônus',
    range: 'Toque',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Arma não mágica' },
    damageSave: { attackType: 'utility' },
    description: 'Até a magia terminar, a arma tocada se torna uma arma mágica com bônus de +1 nas jogadas de ataque e dano.',
    higherLevels: 'Se usada com espaço de 4º ou 5º, bônus vira +2. Se 6º+, vira +3.',
    classes: ['Clérigo', 'Paladino', 'Mago']
  },
  {
    id: 'mirror-image',
    name: 'Reflexos (Mirror Image)',
    englishName: 'Mirror Image',
    level: 2,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Três duplicatas ilusórias suas surgem em seu espaço e o imitam. Cada duplicata tem CA igual a 10 + mod. Destreza. Quando você for atacado, você rola 1d20 para determinar se o ataque atinge uma das cópias em vez de você. Se a cópia for atingida e tomar dano que supera sua CA, ela é destruída. TRs e danos em área ignoram as imagens.',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'moonbeam',
    name: 'Raio de Lua (Moonbeam)',
    englishName: 'Moonbeam',
    level: 2,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'algumas sementes de planta lunar e um pouco de quartzo claro opalescente', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cylinder', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Cilindro de 1,5m de raio por 12m de altura' },
    damageSave: { damageDice: '2d10', damageType: 'Radiante', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Um raio prateado desce brilhante em um cilindro de 1,5m de raio e 12m de altura. Criaturas recebem 2d10 dano Radiante ao entrar ou terminar o turno no raio (TR Const para metade). Metamorfos tem desvantagem e revertem p/ a forma normal na falha. Com sua ação, você move o feixe em até 18m.',
    higherLevels: 'O dano aumenta em 1d10 por nível acima do 2º.',
    classes: ['Druida']
  },
  {
    id: 'pass-without-trace',
    name: 'Passos sem Pegadas (Pass without Trace)',
    englishName: 'Pass without Trace',
    level: 2,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'cinzas de uma folha queimada de azevinho e visco', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 9, sizeUnit: 'm', formatted: 'Esfera de 9m ao seu redor' },
    damageSave: { attackType: 'utility' },
    description: 'Um véu de sombras e silêncio irradia de você. Para a duração, cada criatura de sua escolha a 9 metros ganha um bônus de +10 nos testes de Furtividade e não podem ser rastreadas senão por meios mágicos (não deixam pegadas nem rastros).',
    classes: ['Druida', 'Patrulheiro']
  },
  {
    id: 'prayer-of-healing',
    name: 'Oração Curativa (Prayer of Healing)',
    englishName: 'Prayer of Healing',
    level: 2,
    school: 'Evocação',
    castingTime: '10 minutos',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 6 criaturas' },
    damageSave: { damageDice: '2d8 + mod', damageType: 'Cura', attackType: 'utility' },
    description: 'Até 6 criaturas de sua escolha a 9 metros de você recuperam 2d8 + mod. Carisma pontos de vida. A magia não surte efeito em mortos-vivos ou constructos.',
    higherLevels: 'O curar aumenta em 1d8 por nível acima do 2º.',
    classes: ['Clérigo']
  },
  {
    id: 'rope-trick',
    name: 'Truque da Corda (Rope Trick)',
    englishName: 'Rope Trick',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pó de extrato de milho e um cordão de no máximo 18 metros de comprimento', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Corda' },
    damageSave: { attackType: 'utility' },
    description: 'Uma corda sobe magicamente no ar. O topo da corda abre acesso a um espaço extradimensional temporário que suporta até 8 criaturas Média ou menor. Criaturas dentro não podem ser atacadas nem detectadas, mas podem observar através do portal invisível no ar. Ao término, os ocupantes caem sem dano.',
    classes: ['Mago']
  },
  {
    id: 'see-invisibility',
    name: 'Ver o Invisível (See Invisibility)',
    englishName: 'See Invisibility',
    level: 2,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um chumaço de talco e pó de prata solto pelo ar', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Pela duração da magia, você enxerga criaturas e objetos invisíveis como se fossem visíveis, e percebe portais interdimensionais na Etérea como sombras tênues.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'spider-climb',
    name: 'Patas de Aranha (Spider Climb)',
    englishName: 'Spider Climb',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma gota de betume e uma aranha', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Pela duração, a criatura tocada ganha a habilidade de mover-se verticalmente em superfícies ou através de tetos enquanto estiver com as mãos livres para auxiliar no movimento, ganhando velocidade de escalada equivalente à sua velocidade terrestre.',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'spike-growth',
    name: 'Crescer Espinhos (Spike Growth)',
    englishName: 'Spike Growth',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '45 metros (150 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um espinho ou pequeno pedaço pontudo de madeira', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 6, sizeUnit: 'm', formatted: 'Raio de 6m' },
    damageSave: { damageDice: '2d4', damageType: 'Perfurante', attackType: 'utility' },
    description: 'O chão num raio de 6 metros se retorce numa cama de farpas rígidas e espinhos que perfuram a armadura e carne. A área se torna terreno difícil. Uma criatura movendo-se por essa área toma 2d4 de dano perfurante para cada 1,5m que ela viaja nela.',
    classes: ['Druida', 'Patrulheiro']
  },
  {
    id: 'spiritual-weapon',
    name: 'Arma Espiritual (Spiritual Weapon)',
    englishName: 'Spiritual Weapon',
    level: 2,
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: '18 metros (60 pés)',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Arma Mágica' },
    damageSave: { damageDice: '1d8 + mod', damageType: 'Força', attackType: 'melee_spell' },
    description: 'Você cria uma arma espectral que surge no alcance. Você pode fazer um ataque mágico corpo-a-corpo contra uma criatura dentro de 1,5m da arma. No acerto, toma 1d8 + modificador dano de força. Como ação bônus, nos próximos turnos, você pode mover a arma até 6 metros e atacar de novo.',
    higherLevels: 'Aumenta dano em 1d8 para cada nível acima do 2º.',
    classes: ['Clérigo']
  },
  {
    id: 'suggestion',
    name: 'Sugestão (Suggestion)',
    englishName: 'Suggestion',
    level: 2,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 8 horas',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: false, material: true, materialsDescription: 'uma gota de óleo doce misturada, uma cobra de um tipo ou de outro', raw: 'V, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Sugere magicamente um curso de ação em até duas sentenças. O pedido deve parecer razoável. A criatura faz um TR de Sabedoria; se falhar, persegue esse curso o melhor que puder até a ação terminar ou a duração expirar. Se ela tomar dano por você ou seus aliados, a magia termina.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'web',
    name: 'Teia (Web)',
    englishName: 'Web',
    level: 2,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma teia de aranha, pedaço de teia do diabo, etc', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 6, sizeUnit: 'm', formatted: 'Cubo de 6m' },
    damageSave: { saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Você conjura uma massa de teias viscosas em um cubo de 6 metros. O espaço se torna terreno difícil e obscurecido. Criaturas ali fazem TR de Destreza ou são Presas. Uma criatura Restringida (Presa) faz teste de Força para escapar (ação normal). As teias são vulneráveis a chamas.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'zone-of-truth',
    name: 'Zona da Verdade (Zone of Truth)',
    englishName: 'Zone of Truth',
    level: 2,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: '10 minutos',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 4.5, sizeUnit: 'm', formatted: 'Esfera de 4,5m de raio' },
    damageSave: { saveStat: 'CHA', saveEffect: 'negate', attackType: 'save' },
    description: 'Cria uma zona mágica de esfera (raio 4,5m). Uma criatura nela deve passar num TR Carisma ou não poderá dizer mentiras deliberadas. Você sabe se cada criatura passou ou falhou.',
    classes: ['Bardo', 'Clérigo', 'Paladino']
  },
  // NÍVEL 3
  {
    id: 'animate-dead',
    name: 'Animar Mortos (Animate Dead)',
    englishName: 'Animate Dead',
    level: 3,
    school: 'Necromancia',
    castingTime: '1 minuto',
    range: '3 metros (10 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma gota de sangue, um pedaço de carne e pó de osso', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: 'Ossos ou Cadáver' },
    damageSave: { attackType: 'utility' },
    description: 'Esta magia cria um servo morto-vivo. Escolha uma pilha de ossos ou um corpo (Esqueleto ou Zumbi). Você pode dar comandos mentais a eles até 18 metros. Você controla eles por 24 horas; reconjure para estender (afeta até 4 mortos-vivos para reassertar).',
    higherLevels: 'Acima do nível 3, você levanta (ou reafirma) 2 mortos-vivos adicionais por nível.',
    classes: ['Clérigo', 'Mago']
  },
  {
    id: 'beacon-of-hope',
    name: 'Sinal de Esperança (Beacon of Hope)',
    englishName: 'Beacon of Hope',
    level: 3,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Qualquer nº criaturas' },
    damageSave: { attackType: 'utility' },
    description: 'Concede aura divina. Aliados a sua escolha a até 9m têm vantagem em testes de Sabedoria e Salvaguardas contra a morte, e sempre que curados por magia, recebem a quantidade máxima possível de cura dos dados.',
    classes: ['Clérigo', 'Paladino']
  },
  {
    id: 'blink',
    name: 'Piscar (Blink)',
    englishName: 'Blink',
    level: 3,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '1 minuto',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Você rola um d20 ao fim do seu turno. Com um 11 ou maior, você sume do plano material e vai para o Plano Etéreo (e fica intocável aqui) e retorna no começo de seu próximo turno a até 3m do espaço original.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'call-lightning',
    name: 'Convocar Relâmpagos (Call Lightning)',
    englishName: 'Call Lightning',
    level: 3,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'cylinder', sizeValue: 18, sizeUnit: 'm', formatted: 'Cilindro raio 18m altura 3m' },
    damageSave: { damageDice: '3d10', damageType: 'Elétrico', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Nuvem tempestuosa é criada. Dispare um raio num ponto. Todas as criaturas em raio de 1,5m desse ponto (TR Destreza) sofre 3d10 Eletricidade, ou metade disso se sucesso. Como ação, enquanto concentra-se você atira novamente. (Na chuva forte original o raio sofre 4d10)',
    higherLevels: 'O dano aumenta 1d10 por nível superior acima de 3.',
    classes: ['Druida']
  },
  {
    id: 'clairvoyance',
    name: 'Clarividência (Clairvoyance)',
    englishName: 'Clairvoyance',
    level: 3,
    school: 'Adivinhação',
    castingTime: '10 minutos',
    range: '1.5 quilômetros',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'foco vale 100 po: chifre para som, olho de vidro para ver', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'single_target', formatted: '1 Sensor Invisível' },
    damageSave: { attackType: 'utility' },
    description: 'Você cria um sensor num local familiar dentro do alcance. Você pode usar uma ação de ver OU ouvir do sensor. Você pode alternar por ação.',
    classes: ['Bardo', 'Clérigo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'daylight',
    name: 'Luz do Dia (Daylight)',
    englishName: 'Daylight',
    level: 3,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 18, sizeUnit: 'm', formatted: 'Luz brilhante de 18m' },
    damageSave: { attackType: 'utility' },
    description: 'Gera luz brilhante raio de 18m. Dispersa mágicas de Escuridão nível 3 ou inferior (se no raio).',
    classes: ['Clérigo', 'Druida', 'Paladino', 'Patrulheiro', 'Feiticeiro']
  },
  {
    id: 'fear',
    name: 'Medo (Fear)',
    englishName: 'Fear',
    level: 3,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: 'Pessoal (Cone de 9m)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pena de galinha ou ovo', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cone', sizeValue: 9, sizeUnit: 'm', formatted: 'Cone de 9m' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Ilusão fantasmagórica do que os alvos mais temem surge num cone de 9m. Falha em TR Sabedoria, criaturas no cone caem em Assustadas, deixam cair o que tem nas mãos e correm o máximo longe na rodada (Ação de Disparada obrigatoria). Só pode testar se perder o conunjurador de vista.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'feign-death',
    name: 'Fingir Morte (Feign Death)',
    englishName: 'Feign Death',
    level: 3,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma pitada de terra', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura Voluntária' },
    damageSave: { attackType: 'utility' },
    description: 'Pela duração, a criatura entra num sono cataléptico idêntico à morte. Recebe resistência contra todos os danos exceto psíquico, tem doença/venenos suspensos (sem avanço). Fica cega e inconsciente.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Mago']
  },
  {
    id: 'gaseous-form',
    name: 'Forma Gasosa (Gaseous Form)',
    englishName: 'Gaseous Form',
    level: 3,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'gaze embebida em fumaça', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura Voluntária' },
    damageSave: { attackType: 'utility' },
    description: 'Você transforma criatura voluntária numa nuvem turva. Resistencia a dano não-mágico. Deslocamento de 3m voo. Pode se mover por pequenas frestas/ar. Não fala, não conjura magias nem interage no físico (nem ataques armados/queda livre).',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'glyph-of-warding',
    name: 'Glifo de Vigilância (Glyph of Warding)',
    englishName: 'Glyph of Warding',
    level: 3,
    school: 'Abjuração',
    castingTime: '1 hora',
    range: 'Toque',
    duration: 'Até dissipada/ativada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'pó de rubi de 200 po', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Objeto de Superfície' },
    damageSave: { damageDice: '5d8', damageType: 'Ácido, Frio, Fogo, Eletricidade ou Trovejante', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Insere mágico explosivo com condição exata num lugar, que vai estourar. Escolher Glifo Explosivo: 5d8 em 6m de raio de um tipo elemental, TR de Destreza pra 1/2. OU Glifo de Magia, pra invocar magia estocada (alvo: no ser da explosão).',
    higherLevels: '+1d8 dano por nível ao glifo explosivo, e magia nivelada ao slot superior ao glifo de magia.',
    classes: ['Bardo', 'Clérigo', 'Mago']
  },
  {
    id: 'haste',
    name: 'Velocidade (Haste)',
    englishName: 'Haste',
    level: 3,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pouco de raiz de alcaçuz', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura Voluntária' },
    damageSave: { attackType: 'utility' },
    description: 'Escolha um aliado. Ele dobra seu deslocamento terrestre, tem +2 CA, e Advantage p/ TR Destreza, e recebe uma "Ação Adicional". Ação p/ Atacar (1 golpe só), Disparada, Desengajar, Esconder, Usar Objeto. Ao fim, o alvo tem inércia, perde o turno 1 rodada e não se move.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'hypnotic-pattern',
    name: 'Padrão Hipnótico (Hypnotic Pattern)',
    englishName: 'Hypnotic Pattern',
    level: 3,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pó de besouro escuro e espelho', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 9, sizeUnit: 'm', formatted: 'Cubo de 9m' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Gera redemoinho brilhante p/ o hipnotizar no cubo. Se vir o padrão, criatura rola TR de Sabedoria ou fica Enfeitiçada. Enquanto no estado, não pode mover (Vel 0), não pode fazer ações e fica em estupor hipnótico. Dano rompe; alguém balançando tira.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'leomunds-tiny-hut',
    name: 'Pequena Cabana de Leomund (Leomunds Tiny Hut)',
    englishName: "Leomund's Tiny Hut",
    level: 3,
    school: 'Evocação',
    castingTime: '1 minuto',
    range: 'Pessoal (domo de 3m)',
    duration: '8 horas',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma bolinha de argila com fragmento cristal', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 3, sizeUnit: 'm', formatted: 'Domo de 3m' },
    damageSave: { attackType: 'utility' },
    description: 'Surge um domo cúpula impermeável (9 pessoas) da cor opaca que você escolher. O clima (chuva/vento/calor) é mantido bom, bloqueia magias e flechas que passem por ele por fora. Só passam pessoas que estavam no cast com você. Você não pode sair da área, se não ela some.',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'major-image',
    name: 'Imagem Maior (Major Image)',
    englishName: 'Major Image',
    level: 3,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pêlo de ovelha (um chumaço)', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 6, sizeUnit: 'm', formatted: 'Cubo de 6m' },
    damageSave: { saveStat: 'INT', saveEffect: 'negate', attackType: 'utility' },
    description: 'Você cria a ilusão realista completa num cubo 6m de raio de uma figura/fenômeno audível, térmico e olfativo vívido, se comportando. Você pode translocar/animar com sua ação pra seguir reagindo de forma muito viva. Investigar vira Ilusão no toque físico.',
    higherLevels: 'Com espaço 6º+, tem duração "Até dissipada", s/ Concentração.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'mass-healing-word',
    name: 'Palavra Curativa em Massa (Mass Healing Word)',
    englishName: 'Mass Healing Word',
    level: 3,
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 6 criaturas' },
    damageSave: { damageDice: '1d4 + mod', damageType: 'Cura', attackType: 'utility' },
    description: 'Você profere uma palavra mágica restauradora curando até seis criaturas que pode visualizar 18 metros ganhando cada uma a magia curada de vida em 1d4 + Habilidade do conjurador. Imune morto vivo.',
    higherLevels: '+1d4 nos PV, curados por level extra acima de 3º.',
    classes: ['Clérigo']
  },
  {
    id: 'meld-into-stone',
    name: 'Mesclar-se às Rochas (Meld into Stone)',
    englishName: 'Meld into Stone',
    level: 3,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '8 horas',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'touch', formatted: 'Para si a rocha' },
    damageSave: { attackType: 'utility' },
    description: 'Enfiar a si mesmo dentro de um grande objeto de rocha e se fechar de vista ao mundo exterior por 8h. Nada de ataque e mobilidade ali. É invisível dentro, e fica apenas com a audiência atordoada do mundo.',
    classes: ['Clérigo', 'Druida']
  },
  {
    id: 'phantom-steed',
    name: 'Corcel Fantasmagórico (Phantom Steed)',
    englishName: 'Phantom Steed',
    level: 3,
    school: 'Ilusão',
    castingTime: '1 minuto',
    range: '9 metros (30 pés)',
    duration: '1 hora',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'special', formatted: '1 Corcel Maior Ilusório' },
    damageSave: { attackType: 'utility' },
    description: 'Convoca um cavalo Ilusório Fantasma. Esse pégaso não possui combates. Deslocamento muito alto (Velocidade 30m e pode usar Desengajar) para viajar. Recebe um hit que o destrói 1 minuto pós bater.',
    classes: ['Mago']
  },
  {
    id: 'remove-curse',
    name: 'Remover Maldição (Remove Curse)',
    englishName: 'Remove Curse',
    level: 3,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Alvo Amaldiçoado' },
    damageSave: { attackType: 'utility' },
    description: 'No toque da benção, todos efeitos mágicos que o infligiram, somem. E ele também destrói sintonias amaldiçoadas forçadas em armas e armaduras no toque da mão, liberando a pessoa de ter o objeto pra si.',
    classes: ['Clérigo', 'Paladino', 'Bruxo', 'Mago']
  }
];
