import { SRDItem } from './types';

export const BATCH_10_COLLECTIONS: SRDItem[] = [
  // Cintos de Força
  {
    id: 'belt-of-giant-strength-hill',
    name: 'Cinto de Força do Gigante da Colina',
    englishName: 'Belt of Hill Giant Strength',
    type: 'Item Mágico (Cinto)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Aumenta sua Força absoluta para o valor fixo de 21 enquanto as vestir (Mod. +5). Ignora o efeito se base for maior.',
    value: '4.000 PO',
    weight: 1,
  },
  {
    id: 'belt-of-giant-strength-frost',
    name: 'Cinto de Força do Gigante do Gelo/Pedra',
    englishName: 'Belt of Frost/Stone Giant Strength',
    type: 'Item Mágico (Cinto)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Aumenta sua Força absoluta para o valor mágico elevado de 23 enquanto o usar (Mod. +6). A força das montanhas nas mãos.',
    value: '12.000 PO',
    weight: 1,
  },
  {
    id: 'belt-of-giant-strength-fire',
    name: 'Cinto de Força do Gigante do Fogo',
    englishName: 'Belt of Fire Giant Strength',
    type: 'Item Mágico (Cinto)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Eleva a Força base formidavelmente do personagem para 25 (Mod. +7) imitando o calor implacável brutal de um Golias infernal.',
    value: '18.000 PO',
    weight: 1,
  },
  {
    id: 'belt-of-giant-strength-cloud',
    name: 'Cinto de Força do Gigante das Nuvens',
    englishName: 'Belt of Cloud Giant Strength',
    type: 'Item Mágico (Cinto)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Eleva sua capacidade orgânica e física para a força extrema limite absurda para o valor monstruoso lendário de 27 (Mod. +8).',
    value: '50.000 PO',
    weight: 1,
  },
  {
    id: 'belt-of-giant-strength-storm',
    name: 'Cinto de Força do Gigante da Tempestade',
    englishName: 'Belt of Storm Giant Strength',
    type: 'Item Mágico (Cinto)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'A joia máxima das fortalezas D&D (Poderoso Deus do Trovão gigante). Garante o limite supremo e absoluto impiedoso de 29 fixado permanentemente na base (Mod. +9 destrutivo por soco).',
    value: '75.000 PO',
    weight: 1,
  },
  // Pedras de Ioun 
  {
    id: 'ioun-stone-agility',
    name: 'Pedra de Ioun (Agilidade)',
    englishName: 'Ioun Stone of Agility',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Um cristal orbita livremente sua cabeça sem peso. Concede os exatos +2 contínuos de bônus fixo superior na sua Destreza global (O limite máximo mortal para essa pedra quebra o 20 subindo a barra de 22 máximos de status da ficha).',
    value: '15.000 PO',
    weight: 0,
  },
  {
    id: 'ioun-stone-fortitude',
    name: 'Pedra de Ioun (Fortitude)',
    englishName: 'Ioun Stone of Fortitude',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Um cristal rosa reluzente orbita ao redor da sua cabeça. Concede +2 bônus permanente de magia na sua Constituição base final e amplia os seus patamares de vida máxima (Max stats cap: 22 absoluto).',
    value: '15.000 PO',
    weight: 0,
  },
  {
    id: 'ioun-stone-insight',
    name: 'Pedra de Ioun (Intuição)',
    englishName: 'Ioun Stone of Insight',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Cristal azul divino. Concede o forte salto passivo/ativo de feitiço no atributo Sabedoria (+2 Wisdom inato mágico bônus) e ultrapassa com louvor regras da ficha quebrando pros limites a 22 global.',
    value: '15.000 PO',
    weight: 0,
  },
  {
    id: 'ioun-stone-intellect',
    name: 'Pedra de Ioun (Intelecto)',
    englishName: 'Ioun Stone of Intellect',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Esfera marmorizada orbita com rastro vermelho e azul cerebral. Garante ao Mago/Artifice genialidade de expansão maciça de (+2 Inteligência fixada contínua Arcana) e barra Max sobe pros limites 22.',
    value: '15.000 PO',
    weight: 0,
  },
  {
    id: 'ioun-stone-leadership',
    name: 'Pedra de Ioun (Liderança)',
    englishName: 'Ioun Stone of Leadership',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Orbe marmorizado rosa e verde exótico. Impulsiona a confiança, influência mágica passiva no seu Carisma nobres divinos com aumentos globais em (+2 contínuos de base) e limites expandindo de volta aos patamares de 22.',
    value: '15.000 PO',
    weight: 0,
  },
  {
    id: 'ioun-stone-strength',
    name: 'Pedra de Ioun (Força)',
    englishName: 'Ioun Stone of Strength',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Cristal azul pálido orbitante rústico forte. Ativa e estica veias dos músculos pesados garantindo um status bônus de mais puro acréscimo (+2 base Strength/Força contínua) com tetos e limites 22 expandidos sobre D&D natural.',
    value: '15.000 PO',
    weight: 0,
  },
  {
    id: 'ioun-stone-mastery',
    name: 'Pedra de Ioun (Maestria)',
    englishName: 'Ioun Stone of Mastery',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Cristal verde vibrante e polido milenarmente mágico supremo orbitando e seguindo sua presença mestre. O mais potente cristal mágico, aumenta integralmente todos os seus atributos que dependem indiretamente de Maestrias somando o global: +1 de "Proficiency Bonus" mágico para todas salvaguardas, DC passivos e acertos brutais da vida.',
    value: '50.000 PO',
    weight: 0,
  },
  {
    id: 'ioun-stone-reserve',
    name: 'Pedra de Ioun (Reserva)',
    englishName: 'Ioun Stone of Reserve',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Prisma flutuante mágico arcano de armazenamento. Funciona como banco e baú arcano sugando ate si (três espaços passivos limites nível magic=3 slots contínuos somados do grupo tocados pro Cristal armazenar pra explodir as descargas de volta via Ações no dia místico).',
    value: '6.000 PO',
    weight: 0,
  },
  {
    id: 'ioun-stone-absorption',
    name: 'Pedra de Ioun (Absorção)',
    englishName: 'Ioun Stone of Absorption',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Até que fique saturada e rachada perdendo sua aura ela blindará cancelando passivamente (intercepta 20 níveis arcanos de mágias até Nível máximo 4 perigosos jogados contra você diretamente absorvidos pro buraco negro ileso mágico interno).',
    value: '15.000 PO',
    weight: 0,
  },
  {
    id: 'ioun-stone-greater-absorption',
    name: 'Pedra de Ioun (Absorção Maior)',
    englishName: 'Ioun Stone of Greater Absorption',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Até que fique saturada, cega absorvendo interceptações em feitiços contra você de limites esmagadores imensos arcano 8 (50 totais Slot Níveis mágicos estocáveis) interceptando mísseis letais pro cosmo da pedra vazia de vida mágica.',
    value: '40.000 PO',
    weight: 0,
  },
  // Figurines
  {
    id: 'figurine-of-wondrous-power-obsidian-steed',
    name: 'Estatueta (Corcel de Obsidiana)',
    englishName: 'Figurine of Wondrous Power (Obsidian Steed)',
    type: 'Item Mágico (Estatueta)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Estátua de corcel cavalo infernal (Nightmare - Demônio cavalaria negra de magma vivo) sob palavra comando dura até 24h a cada longo hiato celestial (5 dias repouso). Voo brutal. Tem uma Maldição passiva de Planar sem o Bom no carater para locais de fogo pavoroso sombrios da morte se não for alinhado puramente ao mal verdadeiro.',
    value: '22.000 PO',
    weight: 1,
  },
  {
    id: 'figurine-of-wondrous-power-onyx-dog',
    name: 'Estatueta (Cão de Ônix)',
    englishName: 'Figurine of Wondrous Power (Onyx Dog)',
    type: 'Item Mágico (Estatueta)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Vira um formidável grande Mastim canino rochoso imponente de caça vivo (Darkvision e faro para os invisíveis). Permanece na dimensão até longo 6h. Repousa inerte recuperando 7 Dias para usar.',
    value: '6.000 PO',
    weight: 1,
  },
  {
    id: 'figurine-of-wondrous-power-ebony-fly',
    name: 'Estatueta (Mosca de Ébano)',
    englishName: 'Figurine of Wondrous Power (Ebony Fly)',
    type: 'Item Mágico (Estatueta)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Um inseto (Mosca Equina Giga Mágica Voadora e de montaria aérea viva). Atende e pode levar vôo passivo veloz 60 ft por horas. Descansa passivos dois (2) dias integrais ao findar seu elo (dura exatas e maravilhosas 12 h voadoras ininterruptas).',
    value: '4.000 PO',
    weight: 1,
  },
  {
    id: 'figurine-of-wondrous-power-bronze-griffon',
    name: 'Estatueta (Grifo de Bronze)',
    englishName: 'Figurine of Wondrous Power (Bronze Griffon)',
    type: 'Item Mágico (Estatueta)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Estatueta de 5 cm ganha aura e incha transformando se com grito feroz selvagem mágico no Grifo predador majestoso de batalha feroz e locomoção do céu alada. A criatura dura os contínuos instantes (duração máx de 6 horas) precisando recuperar as magias descansando inertemente em bronze sólido os longos e custosos 5 longos dias divinos.',
    value: '6.000 PO',
    weight: 1,
  },
  {
    id: 'figurine-of-wondrous-power-golden-lions',
    name: 'Estatueta (Leões de Ouro)',
    englishName: 'Figurine of Wondrous Power (Golden Lions)',
    type: 'Item Mágico (Estatueta)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Vem no par felino. Estatuetas minúsculas reluzentes conjuradas (podem ser 1 ou os 2 de vez); Animam para a estatística feroz dos Leões rugidores caçadores (Animais) leais puros, de até breves horas de campo sangrento (Maximo = apenas pura 1 h antes da retração). Recupera passivos na sacola 1 Dia/7 dias longo descanso contínuo recupera seu pacto total.',
    value: '6.000 PO',
    weight: 2,
  },
  {
    id: 'figurine-of-wondrous-power-ivory-goats',
    name: 'Estatueta (Bodes de Marfim)',
    englishName: 'Figurine of Wondrous Power (Ivory Goats)',
    type: 'Item Mágico (Estatueta)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'O trio das raras cabras rústicas divinas esculpidas: O "Bode do Desespero", que emite Medo gigante nas lutas em zona (CD 15 sáb/1 hora de uso/recarrega a magia pra sempre num mês integral longo contínuo arcano/15 dias) - E "Bode das Travessias" divinas celestes voadoras (3h), E O furioso destrutivo mágico "Bode da Carnificina" pesado violento (Dura meia hora 3x).',
    value: '9.000 PO',
    weight: 3,
  }
];
