import { SRDItem } from './types';

export const BATCH_4_WEAPONS: SRDItem[] = [
  {
    id: 'berserker-axe',
    name: 'Machado do Furioso',
    englishName: 'Berserker Axe',
    type: 'Arma Mágica (Qualquer Machado)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: '+1 nos ataques e danos. Você ganha +1 PV máximo por nível de personagem. Este item carrega uma Maldição da Fúria: sempre que um inimigo der dano a você e estiver próximo, você entra em um estado incontrolável de furor letal e ataca quem estiver perto até esgotar todos os inimigos.',
    value: '4.500 PO',
    weight: 3,
  },
  {
    id: 'dagger-of-venom',
    name: 'Adaga de Veneno',
    englishName: 'Dagger of Venom',
    type: 'Arma Mágica (Adaga)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: '+1 de bônus nas jogadas de ataque e dano. Uma vez por dia você pode banhar a lâmina num lodo negro letal. O alvo atingido pelo próximo ataque com a lâmina antes de 1 min precisa fazer um TR de Const CD 15, senão sofre 2d10 dano de veneno e é envenenado.',
    value: '3.500 PO',
    weight: 1,
  },
  {
    id: 'dancing-sword',
    name: 'Espada Dançarina',
    englishName: 'Dancing Sword',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Como uma ação bônus você solta a espada que passa a levitar lutando ao seu lado (pode fazer ataques até 9m de distância). Ela voa e ataca usando seus atributos, lutando por até 4 ataques e depois retorna para as suas mãos.',
    value: '12.000 PO',
    weight: 3,
  },
  {
    id: 'defender',
    name: 'Espada Defensora',
    englishName: 'Defender',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: '+3 de bônus em jogadas de ataque e dano. Na primeira vez de cada um de seus turnos, você pode transferir pontos desse bônus (de +1 a +3) para sua Classe de Armadura, reduzindo o bônus de ataque e dano mas ganhando uma proteção até o começo do seu próximo turno.',
    value: '45.000 PO',
    weight: 3,
  },
  {
    id: 'dragon-slayer',
    name: 'Matadora de Dragões',
    englishName: 'Dragon Slayer',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: false,
    description: '+1 de bônus nas jogadas de ataque e dano. Quando atingir um dragão com essa arma, o dragão sofre +3d6 de dano perfurante/cortante extra.',
    value: '5.000 PO',
    weight: 3,
  },
  {
    id: 'dwarven-thrower',
    name: 'Arremessador Anão',
    englishName: 'Dwarven Thrower',
    type: 'Arma Mágica (Martelo de Guerra)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização por Anão',
    description: '+3 de bônus nos ataques e danos. Possui a propriedade de arremesso (Alcance 6/18) e sempre volta para as suas mãos. Ao acerto arremessado, causa +1d8 de dano extra (+2d8 dano extra no total caso atinja gigantes).',
    value: '22.000 PO',
    weight: 2,
  },
  {
    id: 'giant-slayer',
    name: 'Matadora de Gigantes',
    englishName: 'Giant Slayer',
    type: 'Arma Mágica (Qualquer Machado/Espada)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: false,
    description: '+1 de bônus nos ataques e danos. Ao acertar uma criatura Gigante com a arma, ela sofre +2d6 de dano e deve passar num TR CD 15 de Força ou caírá no chão (Caída).',
    value: '6.000 PO',
    weight: 3,
  },
  {
    id: 'mace-of-disruption',
    name: 'Maça de Ruptura',
    englishName: 'Mace of Disruption',
    type: 'Arma Mágica (Maça)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Quando atinge Corruptores (Demônios/Diabos) ou Mortos-Vivos ela causa +2d6 dano Radiante extra. Se o monstro cair para menos de 25 PV pós este ataque, deverá passar em TR de Sabedoria CD 15 ou é destruído instantaneamente. A arma emite luz radiante sagrada.',
    value: '8.000 PO',
    weight: 4,
  },
  {
    id: 'mace-of-smiting',
    name: 'Maça da Destruição',
    englishName: 'Mace of Smiting',
    type: 'Arma Mágica (Maça)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: false,
    description: '+1 em ataques e danos. Em um acerto crítico, adiciona +1d6 extra nos danos. Contra Construtos mecânicos, o bônus de dano de um ataque normal aumenta para +2d6, e um 20 natural destrói o construto no mesmo turno caso reduza a 25 PVs ou menos (adicionando +4d6 de dano massivo).',
    value: '6.000 PO',
    weight: 4,
  },
  {
    id: 'mace-of-terror',
    name: 'Maça do Terror',
    englishName: 'Mace of Terror',
    type: 'Arma Mágica (Maça)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui 3 cargas. Gaste uma ação para consumir 1 carga que emite uma onda de terror psíquico; toda criatura até 9 metros faz TR de Sabedoria CD 15. Numa falha a criatura fica amedrontada por 1 min, só podendo gastar suas ações (Dash) para fugir o máximo possível.',
    value: '5.500 PO',
    weight: 4,
  },
  {
    id: 'nine-lives-stealer',
    name: 'Rouba-Vidas de Nove Vidas',
    englishName: 'Nine Lives Stealer',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: '+2 bônus ataque/dano. Ao você conquistar um crítico natural de 20 e a criatura alvejada possuir menos que 100 PV máximos no total, ela é forçada num TR Constituição 15. Numa falha, a arma arranca uma de suas vidas, executando a criatura instantaneamente. Tem limite de 1d8+1 cargas fatais antes de perder esta propriedade fatal.',
    value: '18.000 PO',
    weight: 3,
  },
  {
    id: 'oathbow',
    name: 'Arco do Juramento',
    englishName: 'Oathbow',
    type: 'Arma Mágica (Arco Longo)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Você pode jurar inimizade mortal (juramento caçador) ao seu inimigo. Atirar no seu Inimigo Jurado concede Vantagem (anulando desvantagem de distância e ignorando meia e três-quartos de cobertura). Além disso, causa +3d6 de dano extra. Porém, se você atacar outra criatura que não o Inimigo Jurado, tem Desvantagem.',
    value: '15.000 PO',
    weight: 2,
  },
  {
    id: 'scimitar-of-speed',
    name: 'Cimitarra da Velocidade',
    englishName: 'Scimitar of Speed',
    type: 'Arma Mágica (Cimitarra)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: '+2 bônus em ataque/dano. Além disso, você pode usar uma Ação Bônus em seu turno para fazer um ataque com esta espada mágica ágil.',
    value: '22.000 PO',
    weight: 3,
  },
  {
    id: 'sword-of-life-stealing',
    name: 'Espada Drenadora de Vida',
    englishName: 'Sword of Life Stealing',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Se sua rolagem de ataque for um acerto crítico natural (20), o alvo sofre 10 de dano Necrótico extra, e você ganha 10 Pontos de Vida Temporários, se o alvo não for construto ou morto-vivo.',
    value: '6.500 PO',
    weight: 3,
  },
  {
    id: 'sword-of-sharpness',
    name: 'Espada Afiada',
    englishName: 'Sword of Sharpness',
    type: 'Arma Mágica (Espada Cortante)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Quando você atinge um objeto, o dano é maximizado. Quando sua jogada de ataque rola um 20 natural, o alvo sofre 14 de dano cortante extra. Após isso, você rola mais um d20. Se der outro 20 natural, a espada arranca um de seus membros.',
    value: '20.000 PO',
    weight: 3,
  },
  {
    id: 'sword-of-wounding',
    name: 'Espada do Sangramento',
    englishName: 'Sword of Wounding',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Feridas feitas não podem ser curadas por meios mágicos menores. Cada vez que atinge, a espada impõe o estado de ferido (Acumulativo). O alvo sofre 1d4 dano necrótico no início de seu turno para cada ferida. O alvo pode usar uma ação para fazer um TR Constituição CD 15 (encerra o efeito).',
    value: '9.000 PO',
    weight: 3,
  },
  {
    id: 'trident-of-fish-command',
    name: 'Tridente de Comandar Peixes',
    englishName: 'Trident of Fish Command',
    type: 'Arma Mágica (Tridente)',
    category: 'Arma',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Possui 3 cargas (recupera 1d3 por dia). Você pode gastar uma ação para gastar 1 carga e lançar a magia Dominar Fera (Dominate Beast), limitando-se apenas a criaturas ou feras com deslocamento de natação nativo (CD 15 de Sabedoria).',
    value: '500 PO',
    weight: 4,
  },
  {
    id: 'vicious-weapon',
    name: 'Arma Viciosa',
    englishName: 'Vicious Weapon',
    type: 'Arma Mágica (Qualquer)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: false,
    description: 'Sempre que você obtiver um crítico (20 natural) numa jogada de ataque com esta arma contra uma criatura, o dano aumenta maciçamente e ela sofre +7 pontos de dano cortante extra.',
    value: '1.500 PO',
    weight: 3,
  },
  {
    id: 'weapon-of-warning',
    name: 'Arma de Alerta',
    englishName: 'Weapon of Warning',
    type: 'Arma Mágica (Qualquer)',
    category: 'Arma',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Esta arma mágica alerta você para perigo eminente. Concede vantagem nas jogadas de iniciativa e previne você e aliados até 9m de serem surpreendidos a qualquer momento. Acorda vocês de forma mágica instantaneamente em caso de perigo sorrateiro enquanto dormem.',
    value: '600 PO',
    weight: 3,
  }
];
