import { SRDSpell } from './types';

export const BATCH_4_SPELLS: SRDSpell[] = [
  // NÍVEL 7
  {
    id: 'conjure-celestial',
    name: 'Conjurar Celestial (Conjure Celestial)',
    englishName: 'Conjure Celestial',
    level: 7,
    school: 'Conjuração',
    castingTime: '1 minuto',
    range: '27 metros (90 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Celestial ND 4 ou menor' },
    damageSave: { attackType: 'utility' },
    description: 'Invoca celestial de ND 4 ou menor, que te obedece. Age independentemente obedecendo comandos verbais para defender você sem custo de ação.',
    classes: ['Clérigo']
  },
  {
    id: 'delayed-blast-fireball',
    name: 'Bola de Fogo Controlável (Delayed Blast Fireball)',
    englishName: 'Delayed Blast Fireball',
    level: 7,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '45 metros (150 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma bolinha de guano e enxofre', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 6, sizeUnit: 'm', formatted: 'Esfera 6m de raio' },
    damageSave: { damageDice: '12d6', damageType: 'Fogo', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Bolinha brilha. Termina quando a concentração acabar (ou voluntário). Quando ela explode, toda a esfera TR Destreza leva 12d6 Fogo (Metade no sucesso). Por cada turno completo que a bolinha ficou ativa intocada concentrando, o DANO BASE SOFRIDO SOBE EM 1d6 a mais!',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'divine-word',
    name: 'Palavra Divina (Divine Word)',
    englishName: 'Divine Word',
    level: 7,
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 9, sizeUnit: 'm', formatted: 'Esfera (Todas a Escolha)' },
    damageSave: { saveStat: 'CHA', saveEffect: 'negate', attackType: 'save' },
    description: 'Você exala poder sagrado em Palavra. Aqueles com TR de CARISMA sofrem penas dependendo dos PVs ATUAIS: (50 PV: Surdo / 40 PV: Surdo+Cego / 30 PV: Surdo,Cego,Atordoado 1hora / 20PV: MORTO INSTANTÂNEAMENTE). Também bane fadas elementais celestiais corruptos etc p plano natural deles.',
    classes: ['Clérigo']
  },
  {
    id: 'etherealness',
    name: 'Forma Etérea (Etherealness)',
    englishName: 'Etherealness',
    level: 7,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 8 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Entra e permanece no Plano Etéreo por todo o tempo, enxergando contornos nebulosos em 18m. Você atravessa TUDO (chão move para os lados) no plano normal. Terminar o feitiço materializando num espaço ocupado toma 4d6 de Dano Força sendo jogado para um bloco livre adjacente.',
    classes: ['Bardo', 'Clérigo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'finger-of-death',
    name: 'Dedo da Morte (Finger of Death)',
    englishName: 'Finger of Death',
    level: 7,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '7d8 + 30', damageType: 'Necrótico', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Você aponta letalmente para um corpo: Oponente (TR Constituição), Sofre maciço 7d8 + 30 Dano Necrótico (Ou Metade). Se o humanoide MORRER pela magia, ele se ERGUE no seu próximo turno sob seu controle COMO ZUMBI MÁGICO fiel permanente para toda vida.',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'forcecage',
    name: 'Prisão de Energia (Forcecage)',
    englishName: 'Forcecage',
    level: 7,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '30 metros (100 pés)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'pó de rubi puro em 1500 PO', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 6, sizeUnit: 'm', formatted: 'Gaiola (6m) ou Cubo Fechado (3m)' },
    damageSave: { attackType: 'utility' },
    description: 'Constrói na área ou Gaiola de grade visível 6x6m, ou Cubo fechado Sólido 3x3m, prendendo criatura SEM TR inicial se caber. Feitiços normais não atravessam (Cubo sólido). Para fugir TELEPORTANDO / viagem planar, devem rolar um TR DE CARISMA pra não falhar de usar a própria magia de teleporte aprisionada.',
    classes: ['Bardo', 'Bruxo', 'Mago']
  },
  {
    id: 'mirage-arcane',
    name: 'Miragem (Mirage Arcane)',
    englishName: 'Mirage Arcane',
    level: 7,
    school: 'Ilusão',
    castingTime: '10 minutos',
    range: 'Visão',
    duration: '10 dias',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Cubo de 1.6 KM (1 Milha)' },
    damageSave: { attackType: 'utility' },
    description: 'Muda terreno VISUAL E TÁTIL em 1 Milha Quadrada inteira de campo longo! Ele vira sólido para os viajantes ilusoriamente (Gelo escorregadio, pontes causam quedas se tiradas), você molda toda a infraestrutura base natural (mas não seres, só arvores galhos clima) ativamente.',
    classes: ['Bardo', 'Druida', 'Mago']
  },
  {
    id: 'mordenkainens-magnificent-mansion',
    name: 'Mansão Magnífica (Magnificent Mansion)',
    englishName: "Mordenkainen's Magnificent Mansion",
    level: 7,
    school: 'Conjuração',
    castingTime: '1 minuto',
    range: '90 metros (300 pés)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'portal marfim marchetado, e prata luxuosa 15 PO', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Mansão Extradimensional' },
    damageSave: { attackType: 'utility' },
    description: 'Invoca porta invisível (para quem você não permitir). Lá dentro há mansão extradimensional 50 quartos luxuosos com lautos banquetes e criados servos invisíveis servindo tudo à gosto por 24 horas.',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'mordenkainens-sword',
    name: 'Espada de Mordenkainen (Mordenkainen’s Sword)',
    englishName: "Mordenkainen's Sword",
    level: 7,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'espada plana pequena 250 PO miniatura platina zinco', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Espada Flutuante' },
    damageSave: { damageDice: '3d10', damageType: 'Energia', attackType: 'melee_spell' },
    description: 'Arma mágica invocada faz um 1 Ataque de Magia seu numa criatura à até 1.5m, dando 3d10 Dano Energia ao invocar. E Todo Turno (AÇÃO BONUS) voar 6 metros para repetir mais golpes livres.',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'plane-shift',
    name: 'Viagem Planar (Plane Shift)',
    englishName: 'Plane Shift',
    level: 7,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'um garfo sintonizador divino puro minucioso 250PO', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'touch', formatted: '8 criaturas juntas dadas as mãos, ou 1 Inimigo Banish' },
    damageSave: { attackType: 'utility' },
    description: 'Teleporta instantâneo a todos do grupo em mãos dadas para outro Plano (Elysium, Gehenna, Plano Elemental do Fogo, etc) em localização generalizada aproximada. SE USADO AGRESSIVO EM INIMIGO, requer ataque magico corpo a corpo + TR DE CARISMA pra não mandar o pobre alvo ser arremessado banido pro inferno planar perenemente.',
    classes: ['Clérigo', 'Druida', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'regenerate',
    name: 'Regeneração (Regenerate)',
    englishName: 'Regenerate',
    level: 7,
    school: 'Transmutação',
    castingTime: '1 minuto',
    range: 'Toque',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'oração campal com chocalhos da santa paz', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { damageDice: '4d8 + 15', damageType: 'Cura', attackType: 'utility' },
    description: 'Alvo recebe 4d8+15 PV curados de imediato, MAIS 1 Ponto de Vida de CURA A CADA INÍCIO DO TURNO DELA (por 1 hora, são 600 turnos curando 1 na veia automática) e Membros físicos CORTADOS RECRESCEM MILAGROSAMENTE devolta em 2 minutos!',
    classes: ['Bardo', 'Clérigo', 'Druida']
  },
  {
    id: 'resurrection',
    name: 'Ressurreição (Resurrection)',
    englishName: 'Resurrection',
    level: 7,
    school: 'Necromancia',
    castingTime: '1 hora',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'diamantes no valor total de 1.000 PO', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Cadáver' },
    damageSave: { attackType: 'utility' },
    description: 'Revive uma alma tocando no morto falecido por no máximo um SÉCULO 100 ANOS (sem ser morto vivo, e tendo a morte sendo algo n-velhice). Alvo neutraliza feitiços letais nele. Aplica os -4 na tabela universal de punição de exaustão do regresso.',
    classes: ['Bardo', 'Clérigo']
  },
  {
    id: 'reverse-gravity',
    name: 'Inverter a Gravidade (Reverse Gravity)',
    englishName: 'Reverse Gravity',
    level: 7,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '30 metros (100 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pedra preciosa e espinho', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cylinder', sizeValue: 15, sizeUnit: 'm', formatted: 'Cilindro 15m de raio 30m alt' },
    damageSave: { saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Ao invocar o raio cilindrico a gravidade da area INVERTE PUXANDO TODOS PARA O TETO EM CIMA (ou teto da altura limite da area se tiver teto, com DANO DE QUEDA DE CIMA normal!). TR Destreza pra se pendurar e segurar algo no chao. Fim do feitiço devolve todos ao chao caindo pra baixo pra tomar mais dano de queda!',
    classes: ['Druida', 'Feiticeiro', 'Mago']
  },
  {
    id: 'simulacrum',
    name: 'Simulacro (Simulacrum)',
    englishName: 'Simulacrum',
    level: 7,
    school: 'Ilusão',
    castingTime: '12 horas',
    range: 'Toque',
    duration: 'Até dissipada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'gelo / boneco de neve esculpido usando pó de rubi valendo 1.500 PO (consumidos) e os fios da vítima originais', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Fera ou Humanóide e 1 Clone' },
    damageSave: { attackType: 'utility' },
    description: 'Copie 100% dos poderes status da vítima. Tem HP máximo dividido pela METADE, nunca recupera espaço de magia curas passivas de descansos mas faz tudo do alvo leal a você. Somente um clone ativo por conjurador por vez, caso seja re-castado, anterior quebra.',
    classes: ['Mago']
  },
  {
    id: 'symbol',
    name: 'Símbolo (Symbol)',
    englishName: 'Symbol',
    level: 7,
    school: 'Abjuração',
    castingTime: '1 minuto',
    range: 'Toque',
    duration: 'Até dissipada / Até engatilhada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'pó de diamante valendo 1.000 PO consumido e desenhando o glifo', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Objeto' },
    damageSave: { saveStat: 'CON', saveEffect: 'negate', attackType: 'save' },
    description: 'Faz um mega Símbolo oculto. Condição de disparo customizável (Ao ler/Passar etc). Aplica efeito MÁGICO SUPREMO escolhido (Dor 10d10 Necrótico num raio 18m, Insanidade, Sono 10min num grupo, Medo, Morte letal etc etc).',
    classes: ['Bardo', 'Clérigo', 'Mago']
  },
  {
    id: 'teleport',
    name: 'Teletransporte (Teleport)',
    englishName: 'Teleport',
    level: 7,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '3 metros (10 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 3, sizeUnit: 'm', formatted: 'Até 8 Criaturas e Objetos' },
    damageSave: { attackType: 'utility' },
    description: 'Teleporta você + 8 criaturas juntas instantaneamente por qualquer lugar num MESMO PLANO (Mesmo Mundo) sem limitação. Há ROLAGEM DE ACIDENTE D100, variando conforme seu nível de Conhecimento/Familiaridade com o local pretendido: (Círculo Perm, Visto antes, Visto Nunca). Pode cair no limbo e causar 3d10 Danos Força antes de se chocar no destino correto.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },

  // NÍVEL 8
  {
    id: 'antimagic-field',
    name: 'Campo Antimagia (Antimagic Field)',
    englishName: 'Antimagic Field',
    level: 8,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Pessoal (Esfera 3m)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pouco de poeira de ferro de imã', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 3, sizeUnit: 'm', formatted: 'Esfera 3m no conjurador' },
    damageSave: { attackType: 'utility' },
    description: 'Invulnerabilidade. Esfera irradia você com nulificação pesada da Trama: Magias NÃO SURTEM EFEITO aí dentro. Sumonados somem se entrarem, Itens Mágicos desligam ficando não-mágicos, Portais desativam etc (Não afeta Feitiços criados pelas divindades em divindades).',
    classes: ['Clérigo', 'Mago']
  },
  {
    id: 'clone',
    name: 'Clone (Clone)',
    englishName: 'Clone',
    level: 8,
    school: 'Necromancia',
    castingTime: '1 hora',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'diamante de 1000 PO e recipiente vaso gigantesco de cristal 2.000 PO e um cm cúbico da carne sangue da vítima', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Corpo' },
    damageSave: { attackType: 'utility' },
    description: 'Um feitiço imortal. O clone em formol cresce e MADURA EM 120 DIAS na urna. Se a pessoa original morrer, de onde for, sua ALMA TRANSCENDE e possui de imediato o Clone lá na base nascida, vivo inteiro (Opcionalmente mais jovem se escolher).',
    classes: ['Mago']
  },
  {
    id: 'control-weather',
    name: 'Controlar o Clima (Control Weather)',
    englishName: 'Control Weather',
    level: 8,
    school: 'Transmutação',
    castingTime: '10 minutos',
    range: 'Visão (Raio de 8 km)',
    duration: 'Até 8 horas',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pó e vapor incenso dágua', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 8000, sizeUnit: 'm', formatted: 'Esfera de 8 Kilômetros' },
    damageSave: { attackType: 'utility' },
    description: 'Assume domínio divino do céu num raio imenso (8 KM, ou 5 Milhas). Muda condições atuais passo a passo pela escala tabela climática (Limpo, Nuvens, Tempestade Furacão / Calor Infernal Ártico etc). Leva 1d4x10 min p cada alteração da fase atuar de vez.',
    classes: ['Clérigo', 'Druida', 'Mago']
  },
  {
    id: 'earthquake',
    name: 'Terremoto (Earthquake)',
    englishName: 'Earthquake',
    level: 8,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '150 metros (500 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pedaços poeira do chão da terra ou pedrinhas esmagadas', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 30, sizeUnit: 'm', formatted: 'Esfera Tremor 30m de Raio' },
    damageSave: { saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Treme área violentamente de 30m. Chão rasga fendas engolindo. TR Destreza todo turno para não cair de costas Caído e/ou ser engolido ou ter Concentração magia 100% cancelada no tranco. Construções rústicas ou castelos colapsam cedendo 50 de DANO ESTRUTURAL base POR TURNO (podendo cagar 5d6 de pedra letal destreza em quem fica abaixo ou na varanda de estruturas)! ',
    classes: ['Clérigo', 'Druida', 'Feiticeiro']
  },
  {
    id: 'feeblemind',
    name: 'Enfraquecer o Intelecto (Feeblemind)',
    englishName: 'Feeblemind',
    level: 8,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '45 metros (150 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'punhado de casca esfregar argila', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '4d6', damageType: 'Psíquico', saveStat: 'INT', saveEffect: 'negate', attackType: 'save' },
    description: 'Rasga, atrofia as engrenagens mentais do inimigo para um neandertal. Sofre TR de INTELIGÊNCIA: Se falhar leva 4d6 de Dano Psíquico e a sua Inteligência e seu Carisma FICAM COM VALOR 1 (UM). Alvo nunca mais conjura nada, nunca mais ativa itens, nunca entende idioma coerente mas apenas protege aliados fisicamente primitivo. TR NOVO SÓ PODE SER REPETIDO A CADA 30 DIAS!!!.',
    classes: ['Bardo', 'Druida', 'Bruxo', 'Mago']
  }
];
