import { SRDItem } from './types';

export const BATCH_3_WANDS_STAVES_RODS: SRDItem[] = [
  // Wands
  {
    id: 'wand-of-binding',
    name: 'Varinha de Prisão',
    englishName: 'Wand of Binding',
    type: 'Varinha Mágico',
    category: 'Varinha',
    rarity: 'Rara',
    attunement: 'Requer Sintonização por um Conjurador',
    description: 'Possui 7 cargas (recupera 1d6+1 diárias). Pode conjurar Imobilizar Pessoa (Hold Person) gastando 2 cargas ou Imobilizar Monstro (Hold Monster) gastando 5 cargas. CD de Resistência é 17.',
    value: '4.000 PO',
    weight: 1,
  },
  {
    id: 'wand-of-enemy-detection',
    name: 'Varinha de Detecção de Inimigos',
    englishName: 'Wand of Enemy Detection',
    type: 'Varinha Mágico',
    category: 'Varinha',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui 7 cargas (recupera 1d6+1 diárias). Gastando 1 carga você sente a direção de qualquer criatura hostil num raio de 18 metros. Ativa por 1 minuto.',
    value: '3.000 PO',
    weight: 1,
  },
  {
    id: 'wand-of-fear',
    name: 'Varinha de Medo',
    englishName: 'Wand of Fear',
    type: 'Varinha Mágico',
    category: 'Varinha',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui 7 cargas (recupera 1d6+1 diárias). Permite conjurar a magia Comandar (Command) ou um cone de Medo de 18 metros (CD 15 de Sabedoria).',
    value: '5.000 PO',
    weight: 1,
  },
  {
    id: 'wand-of-magic-detection',
    name: 'Varinha de Detectar Magia',
    englishName: 'Wand of Magic Detection',
    type: 'Varinha Mágico',
    category: 'Varinha',
    rarity: 'Incomum',
    attunement: false,
    description: 'Possui 3 cargas (recupera 1d3 diárias). Gastando 1 carga você conjura Detectar Magia.',
    value: '300 PO',
    weight: 1,
  },
  {
    id: 'wand-of-paralysis',
    name: 'Varinha de Paralisia',
    englishName: 'Wand of Paralysis',
    type: 'Varinha Mágico',
    category: 'Varinha',
    rarity: 'Rara',
    attunement: 'Requer Sintonização por um Conjurador',
    description: 'Possui 7 cargas. Com uma ação gasta 1 carga para paralisar um alvo visível a até 18 metros. Ele deve ser bem sucedido num TR de Constituição CD 15 ou ficar Paralisado por 1 minuto (TR adicional a cada turno do alvo).',
    value: '4.500 PO',
    weight: 1,
  },
  {
    id: 'wand-of-polymorph',
    name: 'Varinha de Metamorfose',
    englishName: 'Wand of Polymorph',
    type: 'Varinha Mágico',
    category: 'Varinha',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização por um Conjurador',
    description: 'Possui 7 cargas. Gastando 1 carga você conjura Metamorfose (Polymorph) com CD 15 de Sabedoria.',
    value: '15.000 PO',
    weight: 1,
  },
  {
    id: 'wand-of-secrets',
    name: 'Varinha de Segredos',
    englishName: 'Wand of Secrets',
    type: 'Varinha Mágico',
    category: 'Varinha',
    rarity: 'Incomum',
    attunement: false,
    description: 'Possui 3 cargas (recupera 1d3 ao amanhecer). Gastando 1 carga revela portas secretas ou armadilhas num raio de 9 metros.',
    value: '200 PO',
    weight: 1,
  },
  {
    id: 'wand-of-web',
    name: 'Varinha de Teias',
    englishName: 'Wand of Web',
    type: 'Varinha Mágico',
    category: 'Varinha',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização por um Conjurador',
    description: 'Possui 7 cargas. Gastando 1 carga você conjura Teia (Web) com CD 15 de Destreza.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'wand-of-wonder',
    name: 'Varinha das Maravilhas',
    englishName: 'Wand of Wonder',
    type: 'Varinha Mágico',
    category: 'Varinha',
    rarity: 'Rara',
    attunement: 'Requer Sintonização por um Conjurador',
    description: 'Possui 7 cargas. Quando você usa uma carga, escolhe um alvo e rola 1d100 numa tabela de efeitos aleatórios que pode causar de uma tempestade de borboletas até uma bola de fogo ou invisibilidade.',
    value: '6.000 PO',
    weight: 1,
  },
  // Staves
  {
    id: 'staff-of-charming',
    name: 'Cajado do Encantamento',
    englishName: 'Staff of Charming',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Rara',
    attunement: 'Requer Sintonização por Bardo, Bruxo, Clérigo, Druida, Feiticeiro ou Mago',
    description: 'Possui 10 cargas. Permite conjurar Enfeitiçar Pessoa (Charm Person), Comandar (Command) ou Compreender Idiomas (Comprehend Languages). Se for alvo de magia de encantamento e passar no teste, pode refletir a magia no atacante.',
    value: '5.000 PO',
    weight: 4,
  },
  {
    id: 'staff-of-fire',
    name: 'Cajado do Fogo',
    englishName: 'Staff of Fire',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização por Druida, Feiticeiro, Bruxo ou Mago',
    description: 'Você tem resistência a dano de fogo enquanto usar o cajado. Ele tem 10 cargas e permite conjurar Mãos Flamejantes (Burning Hands), Bola de Fogo (Fireball) e Muralha de Fogo (Wall of Fire).',
    value: '18.000 PO',
    weight: 4,
  },
  {
    id: 'staff-of-frost',
    name: 'Cajado do Gelo',
    englishName: 'Staff of Frost',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização por Druida, Feiticeiro, Bruxo ou Mago',
    description: 'Você tem resistência a dano de frio. Ele tem 10 cargas e permite conjurar Cone de Frio (Cone of Cold), Névoa Obscurecente (Fog Cloud), Tempestade de Gelo (Ice Storm) e Muralha de Gelo (Wall of Ice).',
    value: '18.000 PO',
    weight: 4,
  },
  {
    id: 'staff-of-healing',
    name: 'Cajado de Cura',
    englishName: 'Staff of Healing',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Rara',
    attunement: 'Requer Sintonização por Bardo, Clérigo ou Druida',
    description: 'Tem 10 cargas. Você pode conjurar Curar Ferimentos (Cure Wounds), Restauração Menor (Lesser Restoration) ou Curar Ferimentos em Massa (Mass Cure Wounds).',
    value: '7.500 PO',
    weight: 4,
  },
  {
    id: 'staff-of-striking',
    name: 'Cajado de Ataque',
    englishName: 'Staff of Striking',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Garante +3 de bônus em jogadas de ataque e dano corpo a corpo. Tem 10 cargas e você pode gastar até 3 cargas num acerto para adicionar 1d6 de dano de energia (força) extra por carga gasta.',
    value: '12.000 PO',
    weight: 4,
  },
  {
    id: 'staff-of-swarming-insects',
    name: 'Cajado do Enxame de Insetos',
    englishName: 'Staff of Swarming Insects',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Rara',
    attunement: 'Requer Sintonização por Bardo, Clérigo, Druida, Feiticeiro, Bruxo ou Mago',
    description: 'Tem 10 cargas. Você pode conjurar Insetos Gigantes (Giant Insect) ou Praga de Insetos (Insect Plague), ou invocar uma nuvem densa de insetos inofensivos em torno de você causando escuridão densa para os outros mas não para você.',
    value: '6.000 PO',
    weight: 4,
  },
  {
    id: 'staff-of-the-adder',
    name: 'Cajado da Víbora',
    englishName: 'Staff of the Adder',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização por Clérigo, Druida ou Bruxo',
    description: 'A cabeça do cajado pode se transformar na de uma cobra venenosa. Tem bônus nas jogadas e causa 1d6 perfurante extra. O alvo deve fazer TR de Const CD 15 ou sofrer 3d6 dano de veneno.',
    value: '1.000 PO',
    weight: 4,
  },
  {
    id: 'staff-of-the-magi',
    name: 'Cajado dos Magos',
    englishName: 'Staff of the Magi',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização por Feiticeiro, Bruxo ou Mago',
    description: 'Concede +2 para ataque mágico e CA/TRs. Pode absorver magias que focam em você para recarregar o cajado. Possui 50 cargas para conjurar um arsenal imenso de feitiços de alto nível. Pode ser quebrado para gerar o Retribuição Golpe, uma explosão destrutiva.',
    value: '75.000 PO',
    weight: 4,
  },
  {
    id: 'staff-of-the-python',
    name: 'Cajado da Píton',
    englishName: 'Staff of the Python',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização por Clérigo, Druida ou Bruxo',
    description: 'Pode se transformar numa cobra constritora gigante amigável que segue seus comandos. Se ela morrer, o cajado é destruído.',
    value: '800 PO',
    weight: 4,
  },
  {
    id: 'staff-of-the-woodlands',
    name: 'Cajado das Florestas',
    englishName: 'Staff of the Woodlands',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Rara',
    attunement: 'Requer Sintonização por Druida',
    description: '+2 bônus ataque/dano. Tem 10 cargas. Você pode conjurar Amizade Animal, Despertar, Pele de Árvore, Encontrar o Caminho, Falar com Plantas e Passos sem Pegadas (gratuitamente), Parede de Espinhos, etc. Pode também assumir a forma de uma árvore imensa.',
    value: '8.000 PO',
    weight: 4,
  },
  {
    id: 'staff-of-thunder-and-lightning',
    name: 'Cajado do Trovão e Relâmpago',
    englishName: 'Staff of Thunder and Lightning',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: '+2 bônus ataque/dano corpo a corpo. Possui 5 habilidades elétricas ou trovejantes potentes, cada uma usável 1 vez por dia (Trovão ensurdecedor, Relâmpago de 9m, Trovoada e Eletricidade ao golpear).',
    value: '15.000 PO',
    weight: 4,
  },
  {
    id: 'staff-of-withering',
    name: 'Cajado da Murchidão',
    englishName: 'Staff of Withering',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Rara',
    attunement: 'Requer Sintonização por Clérigo, Druida ou Bruxo',
    description: 'Cajado agourento. Ao acerto corpo a corpo, você pode gastar de suas 3 cargas diárias para causar 2d10 dano necrótico e impor Desvantagem nos testes de Força e Const do alvo.',
    value: '6.000 PO',
    weight: 4,
  },
  // Rods
  {
    id: 'rod-of-absorption',
    name: 'Bastão da Absorção',
    englishName: 'Rod of Absorption',
    type: 'Bastão Mágico',
    category: 'Bastão',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Pode absorver magias das quais você seja alvo e usá-las para recarregar seus próprios espaços de magia. O bastão tem um máximo de 50 níveis de magia. Depois, ele perde sua mágica e se torna não-mágico.',
    value: '25.000 PO',
    weight: 2,
  },
  {
    id: 'rod-of-alertness',
    name: 'Bastão do Alerta',
    englishName: 'Rod of Alertness',
    type: 'Bastão Mágico',
    category: 'Bastão',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Garante Vantagem em Testes de Iniciativa e Percepção. Consegue emitir luz brilhante num raio de 18m. Você pode usar ações para conjurar Detectar Bem e Mal, Detectar Magia, Ver o Invisível, ou usá-lo para criar uma zona sagrada inerte de proteção no solo.',
    value: '18.000 PO',
    weight: 2,
  },
  {
    id: 'rod-of-lordly-might',
    name: 'Bastão do Poder Senhorial',
    englishName: 'Rod of Lordly Might',
    type: 'Bastão Mágico',
    category: 'Bastão',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Um artefato polivalente de formato cilíndrico, que pode, pressionando botões divinos, se transformar magicamente em Espada Flamejante, Machado de Batalha (Força/Trovão), Lança (15 metros) ou Gancho de Escalada mágico, Mastro Longo inquebrável, etc. Pode causar Efeitos Diários (Medo e Roubo de Vida).',
    value: '60.000 PO',
    weight: 2,
  },
  {
    id: 'rod-of-rulership',
    name: 'Bastão da Governança',
    englishName: 'Rod of Rulership',
    type: 'Bastão Mágico',
    category: 'Bastão',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Uma vez ao dia, ao brandir, criaturas em um raio de 36m que você consiga ver fazem TR de Sabedoria CD 15. Aqueles que falharem tornam-se encantados durante 8 horas e o consideram seu líder de total confiança (termina se você prejudicar).',
    value: '8.000 PO',
    weight: 2,
  },
  {
    id: 'rod-of-security',
    name: 'Bastão de Segurança',
    englishName: 'Rod of Security',
    type: 'Bastão Mágico',
    category: 'Bastão',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Uma vez cada 10 dias, transporte até 199 outras criaturas amigáveis para um paraíso extradimensional inofensivo. Podem ficar até 200 dias (dividido pelo número de seres no local), retornando purificadas (sem doenças/venenos e recobradas).',
    value: '30.000 PO',
    weight: 2,
  }
];
