import { SRDItem } from './types';

export const BATCH_6_WONDROUS_A_I: SRDItem[] = [
  {
    id: 'alchemy-jug',
    name: 'Jarro de Alquimia',
    englishName: 'Alchemy Jug',
    type: 'Item Mágico (Jarro)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Este jarro pode produzir fluidos ao gastar uma ação (ex: 30L Água, 1L Ácido, 10L Cerveja, ou até Maionese). Tem um limite de carga para cada fluído, e recarrega ao amanhecer.',
    value: '400 PO',
    weight: 6,
  },
  {
    id: 'amulet-of-proof-against-detection',
    name: 'Amuleto de Prova contra Detecção',
    englishName: 'Amulet of Proof against Detection and Location',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Você ficará intocável a adivinhações. Escondido ativamente à localização por magias divinatórias ou cristais videntes.',
    value: '600 PO',
    weight: 1,
  },
  {
    id: 'amulet-of-the-planes',
    name: 'Amuleto dos Planos',
    englishName: 'Amulet of the Planes',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Permite lançar Transição Planar (Plane Shift) com um teste de Inteligência CD 15 para acessar o destino em segurança. Falhar arremessa todos num plano aleatório.',
    value: '30.000 PO',
    weight: 1,
  },
  {
    id: 'bag-of-beans',
    name: 'Saco de Feijões',
    englishName: 'Bag of Beans',
    type: 'Item Mágico (Bolsa)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Contém 3d4 feijões que causam efeitos aleatórios imprevisíveis ao serem plantados na terra, de nascer estátuas que cospem fogo até criar pirâmides.',
    value: '6.000 PO',
    weight: 0.5,
  },
  {
    id: 'bag-of-tricks',
    name: 'Saco de Truques',
    englishName: 'Bag of Tricks',
    type: 'Item Mágico (Bolsa)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Esta bolsa possui 3 pílulas em forma de pelúcia (retorna diariamente) que, atiradas no solo, viram feras protetoras. Uma bola puxada se tornará um aliado vivo.',
    value: '500 PO',
    weight: 0.5,
  },
  {
    id: 'belt-of-dwarvenkind',
    name: 'Cinto dos Anões',
    englishName: 'Belt of Dwarvenkind',
    type: 'Item Mágico (Cinto)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: '+2 Mod. Constituição (Max 20), você ganha 18 m de visão no escuro, resistência a veneno e faz brotar em você uma barba rústica, independente da raça.',
    value: '4.000 PO',
    weight: 4,
  },
  {
    id: 'broom-of-flying',
    name: 'Vassoura Voadora',
    englishName: 'Broom of Flying',
    type: 'Item Mágico (Montaria)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'A vassoura levita podendo carregar até 100kg a 15m de deslocamento voo ou 9m (até 200kg) e pode ser enviada a lugares via comandos falados num raio de 9 metros.',
    value: '500 PO',
    weight: 3,
  },
  {
    id: 'cape-of-the-mountebank',
    name: 'Capa do Charlatão',
    englishName: 'Cape of the Mountebank',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Ao ser utilizada 1 vez ao dia garante uma fuga ilusionista invocando a magia "Porta Dimensional", onde você some envolto numa densa fumaça de enxofre.',
    value: '5.000 PO',
    weight: 3,
  },
  {
    id: 'carpet-of-flying',
    name: 'Tapete Voador',
    englishName: 'Carpet of Flying',
    type: 'Item Mágico (Montaria)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Voa pelo céu atendendo comandos de voz. Seus tamanhos diferem: 0.9x1.5m a 1.8x2.7m com cargas variando entre 100 até 400kg e velocidades de 24m para 12m.',
    value: '22.000 PO',
    weight: 15,
  },
  {
    id: 'cube-of-force',
    name: 'Cubo de Força',
    englishName: 'Cube of Force',
    type: 'Item Mágico (Cubo)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui 36 cargas máximas, gastando cargas botões ativam diferentes forças de barreira de 4.5m x 4.5m - 1: Gás não cruza; 2: Matéria não cruza; 3: Seres vivos; 4: Magia bloqueada; 5: Tudo bloqueado.',
    value: '10.000 PO',
    weight: 0.5,
  },
  {
    id: 'cubic-gate',
    name: 'Portão Cúbico',
    englishName: 'Cubic Gate',
    type: 'Item Mágico (Cubo)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: false,
    description: 'Cada uma das seis faces conecta a um Plano diferente. Usar abre o portão para outro mundo e ele fica fixado ali durante 1 minuto como uma passagem livre mística.',
    value: '50.000 PO',
    weight: 1,
  },
  {
    id: 'decanter-of-endless-water',
    name: 'Decantador de Água Infinita',
    englishName: 'Decanter of Endless Water',
    type: 'Item Mágico (Cantil)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Retirando a tampa deste cantil ele expele água potável sob comando. Fluxos: Escorrer(4 litros); Chafariz(20L em 1,5m); e Géiser explosivo de empurrão mecânico (115 Litros a 9 metros de distância).',
    value: '500 PO',
    weight: 2,
  },
  {
    id: 'dimensional-shackles',
    name: 'Algemas Dimensionais',
    englishName: 'Dimensional Shackles',
    type: 'Item Mágico (Ferramenta)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Podem ser presas à criatura incapacitada. Impedem a fuga por magia da criatura agrilhoada (Evita forma gasosa, etéreo, blink, portal). TR de Força para arrebentar CD de 30 (testes 1x a cada 30 dias).',
    value: '4.500 PO',
    weight: 5,
  },
  {
    id: 'folding-boat',
    name: 'Barco Dobrável',
    englishName: 'Folding Boat',
    type: 'Item Mágico (Transporte)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Caixinha de madeira que, ao recitar as palavras, se transforma em um barquinho longo ou num Barco à vela/Bote largo (carrega 15 vivos + Remos automáticos).',
    value: '4.000 PO',
    weight: 4,
  },
  {
    id: 'gem-of-seeing',
    name: 'Gema de Visão',
    englishName: 'Gem of Seeing',
    type: 'Item Mágico (Gema)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Esta gema garante truesight (Visão Verdadeira perfeita num raio de 36 Metros), possui as 3 cargas (cada uma durando 10 mins) diárias.',
    value: '5.000 PO',
    weight: 0.1,
  },
  {
    id: 'gloves-of-missile-snaring',
    name: 'Luvas de Pegar Projéteis',
    englishName: 'Gloves of Missile Snaring',
    type: 'Item Mágico (Luvas)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Usando Reação, se for alvo de armas a distância (flechas, etc.), reduz do dano = 1d10 + seu Mod de Destreza. Se reduzir o dano a zero e ter uma mão livre, agarra o projétil no ar.',
    value: '600 PO',
    weight: 1,
  },
  {
    id: 'gloves-of-swimming-and-climbing',
    name: 'Luvas de Escalar e Nadar',
    englishName: 'Gloves of Swimming and Climbing',
    type: 'Item Mágico (Luvas)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Garante passivamente Vantagem em Atletismo (+5 para escalar e nadar passivamente). Recebendo Deslocamentos equivalentes nestes terrenos sem quaisquer lentidões.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'gloves-of-thievery',
    name: 'Luvas de Ladinagem',
    englishName: 'Gloves of Thievery',
    type: 'Item Mágico (Luvas)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Estas luvas invisíveis quando vestidas dão a você +5 num bônus extra nas Rolagens de (Prestidigitação e Arrombamentos de Fechaduras) furtivos e rápidos.',
    value: '650 PO',
    weight: 1,
  },
  {
    id: 'horn-of-blasting',
    name: 'Berrante do Estrondo',
    englishName: 'Horn of Blasting',
    type: 'Item Mágico (Chifre)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Ao ser soprado ele emite um cone de 9 Metros (CD Constituição 15) causando 5d6 de dano Trovejante. O berrante tem 20% de chance de estourar retribuindo dano catastrófico ao usuário se usado muitas vezes.',
    value: '4.500 PO',
    weight: 2,
  },
  {
    id: 'instrument-of-the-bards',
    name: 'Instrumentos dos Bardos',
    englishName: 'Instrument of the Bards',
    type: 'Item Mágico (Instrumento Musical)',
    category: 'Item Maravilhoso',
    rarity: 'Varia',
    attunement: 'Requer Sintonização por um Bardo',
    description: 'Propiciam desvantagem a inimigos que tentem resistir aos seus feitiços de Encantamento de canções. Você ganha acesso a lançar magias exclusivas como Voar ou Invisibilidade diárias.',
    value: '10.000 PO',
    weight: 3,
  },
  {
    id: 'ioun-stone',
    name: 'Pedra de Ioun',
    englishName: 'Ioun Stone',
    type: 'Item Mágico (Cristal / Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Varia',
    attunement: 'Requer Sintonização',
    description: 'Lançada no ar, ela circunda a cabeça do usuário. Concede potentes buff passivos como (+2 em atributos) (dependendo de sua raridade / cor mística gerada pelo Mestre).',
    value: '20.000 PO',
    weight: 0,
  }
];
