import { SRDItem } from './types';

export const BATCH_13_VARIANTS: SRDItem[] = [
  {
    id: 'dragon-scale-mail-black',
    name: 'Armadura de Escamas de Dragão (Preto)',
    englishName: 'Dragon Scale Mail (black)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'dragon-scale-mail-blue',
    name: 'Armadura de Escamas de Dragão (Azul)',
    englishName: 'Dragon Scale Mail (blue)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'dragon-scale-mail-brass',
    name: 'Armadura de Escamas de Dragão (Latão)',
    englishName: 'Dragon Scale Mail (brass)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'dragon-scale-mail-bronze',
    name: 'Armadura de Escamas de Dragão (Bronze)',
    englishName: 'Dragon Scale Mail (bronze)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'dragon-scale-mail-copper',
    name: 'Armadura de Escamas de Dragão (Cobre)',
    englishName: 'Dragon Scale Mail (copper)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'dragon-scale-mail-gold',
    name: 'Armadura de Escamas de Dragão (Ouro)',
    englishName: 'Dragon Scale Mail (gold)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'dragon-scale-mail-green',
    name: 'Armadura de Escamas de Dragão (Verde)',
    englishName: 'Dragon Scale Mail (green)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'dragon-scale-mail-red',
    name: 'Armadura de Escamas de Dragão (Vermelho)',
    englishName: 'Dragon Scale Mail (red)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'dragon-scale-mail-silver',
    name: 'Armadura de Escamas de Dragão (Prata)',
    englishName: 'Dragon Scale Mail (silver)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'dragon-scale-mail-white',
    name: 'Armadura de Escamas de Dragão (Branco)',
    englishName: 'Dragon Scale Mail (white)',
    type: 'Item Mágico (Armadura de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede Vantagem contra a Frightful Presence de dragões e Resistência a dano dependendo do tipo do dragão associado à escama. Além disso, uma vez por dia, você pode usar uma ação para sentir magicamente a direção e distância do dragão mais próximo do tipo desta armadura a até 48 km.',
    value: '10.000 PO',
    weight: 22,
  },
  {
    id: 'potion-of-resistance-acid',
    name: 'Poção de Resistência (Ácido)',
    englishName: 'Potion of Resistance (Ácido)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Ácido pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance-cold',
    name: 'Poção de Resistência (Frio)',
    englishName: 'Potion of Resistance (Frio)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Frio pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance-fire',
    name: 'Poção de Resistência (Fogo)',
    englishName: 'Potion of Resistance (Fogo)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Fogo pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance-force',
    name: 'Poção de Resistência (Energia)',
    englishName: 'Potion of Resistance (Energia)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Energia pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance-lightning',
    name: 'Poção de Resistência (Eletricidade)',
    englishName: 'Potion of Resistance (Eletricidade)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Eletricidade pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance-necrotic',
    name: 'Poção de Resistência (Necrótico)',
    englishName: 'Potion of Resistance (Necrótico)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Necrótico pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance-poison',
    name: 'Poção de Resistência (Veneno)',
    englishName: 'Potion of Resistance (Veneno)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Veneno pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance-psychic',
    name: 'Poção de Resistência (Psíquico)',
    englishName: 'Potion of Resistance (Psíquico)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Psíquico pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance-radiant',
    name: 'Poção de Resistência (Radiante)',
    englishName: 'Potion of Resistance (Radiante)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Radiante pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance-thunder',
    name: 'Poção de Resistência (Trovejante)',
    englishName: 'Potion of Resistance (Trovejante)',
    type: 'Item Mágico (Poção)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando você bebe esta poção mágica brilhante, você ganha Resistência absoluta a dano do tipo Trovejante pelo período total ininterrupto de 1 Hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'ring-of-resistance-acid',
    name: 'Anel de Resistência (Ácido)',
    englishName: 'Ring of Resistance (Ácido)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Ácido enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance-cold',
    name: 'Anel de Resistência (Frio)',
    englishName: 'Ring of Resistance (Frio)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Frio enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance-fire',
    name: 'Anel de Resistência (Fogo)',
    englishName: 'Ring of Resistance (Fogo)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Fogo enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance-force',
    name: 'Anel de Resistência (Energia)',
    englishName: 'Ring of Resistance (Energia)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Energia enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance-lightning',
    name: 'Anel de Resistência (Eletricidade)',
    englishName: 'Ring of Resistance (Eletricidade)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Eletricidade enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance-necrotic',
    name: 'Anel de Resistência (Necrótico)',
    englishName: 'Ring of Resistance (Necrótico)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Necrótico enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance-poison',
    name: 'Anel de Resistência (Veneno)',
    englishName: 'Ring of Resistance (Veneno)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Veneno enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance-psychic',
    name: 'Anel de Resistência (Psíquico)',
    englishName: 'Ring of Resistance (Psíquico)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Psíquico enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance-radiant',
    name: 'Anel de Resistência (Radiante)',
    englishName: 'Ring of Resistance (Radiante)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Radiante enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-resistance-thunder',
    name: 'Anel de Resistência (Trovejante)',
    englishName: 'Ring of Resistance (Trovejante)',
    type: 'Item Mágico (Anel)',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui uma joia mística elementar embutida no aro forjado de ouro que confere a você contínua Resistência elemental/vital a dano do tipo Trovejante enquanto o anel estiver vestido e sintonizado.',
    value: '6.000 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-cantrip',
    name: 'Pergaminho de Magia (Truque Círculo)',
    englishName: 'Spell Scroll (cantrip)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Comum',
    attunement: false,
    description: 'Um feitiço puro de Truque Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '50 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-1st',
    name: 'Pergaminho de Magia (1º Círculo)',
    englishName: 'Spell Scroll (1st)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Comum',
    attunement: false,
    description: 'Um feitiço puro de 1º Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '50 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-2nd',
    name: 'Pergaminho de Magia (2º Círculo)',
    englishName: 'Spell Scroll (2nd)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Incomum',
    attunement: false,
    description: 'Um feitiço puro de 2º Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '250 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-3rd',
    name: 'Pergaminho de Magia (3º Círculo)',
    englishName: 'Spell Scroll (3rd)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Incomum',
    attunement: false,
    description: 'Um feitiço puro de 3º Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '250 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-4th',
    name: 'Pergaminho de Magia (4º Círculo)',
    englishName: 'Spell Scroll (4th)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Rara',
    attunement: false,
    description: 'Um feitiço puro de 4º Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '5.000 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-5th',
    name: 'Pergaminho de Magia (5º Círculo)',
    englishName: 'Spell Scroll (5th)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Rara',
    attunement: false,
    description: 'Um feitiço puro de 5º Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '5.000 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-6th',
    name: 'Pergaminho de Magia (6º Círculo)',
    englishName: 'Spell Scroll (6th)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Um feitiço puro de 6º Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '25.000 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-7th',
    name: 'Pergaminho de Magia (7º Círculo)',
    englishName: 'Spell Scroll (7th)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Um feitiço puro de 7º Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '25.000 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-8th',
    name: 'Pergaminho de Magia (8º Círculo)',
    englishName: 'Spell Scroll (8th)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Lendária',
    attunement: false,
    description: 'Um feitiço puro de 8º Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '50.000 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-9th',
    name: 'Pergaminho de Magia (9º Círculo)',
    englishName: 'Spell Scroll (9th)',
    type: 'Item Mágico (Pergaminho)',
    category: 'Pergaminho',
    rarity: 'Lendária',
    attunement: false,
    description: 'Um feitiço puro de 9º Círculo preso num papel mágico ritualístico selado. Se o feitiço constar na lista de magias da sua classe pura, você gasta ação e pode invocar e queimar este papel manifestando toda força sem gastar seu próprio Espaço de Magia.',
    value: '50.000 PO',
    weight: 0.1,
  },
  {
    id: 'elemental-gem-air',
    name: 'Gema Elemental (Ar)',
    englishName: 'Elemental Gem (Ar)',
    type: 'Item Mágico (Joia)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Ao usar Ação para esmagar esta joia com as mãos, ela conjura instantaneamente a magia "Conjurar Elemental" (Conjure Elemental) sem necessidade de concentração livre chamando aliado Elemental do Ar.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'elemental-gem-earth',
    name: 'Gema Elemental (Terra)',
    englishName: 'Elemental Gem (Terra)',
    type: 'Item Mágico (Joia)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Ao usar Ação para esmagar esta joia com as mãos, ela conjura instantaneamente a magia "Conjurar Elemental" (Conjure Elemental) sem necessidade de concentração livre chamando aliado Elemental do Terra.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'elemental-gem-fire',
    name: 'Gema Elemental (Fogo)',
    englishName: 'Elemental Gem (Fogo)',
    type: 'Item Mágico (Joia)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Ao usar Ação para esmagar esta joia com as mãos, ela conjura instantaneamente a magia "Conjurar Elemental" (Conjure Elemental) sem necessidade de concentração livre chamando aliado Elemental do Fogo.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'elemental-gem-water',
    name: 'Gema Elemental (Água)',
    englishName: 'Elemental Gem (Água)',
    type: 'Item Mágico (Joia)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Ao usar Ação para esmagar esta joia com as mãos, ela conjura instantaneamente a magia "Conjurar Elemental" (Conjure Elemental) sem necessidade de concentração livre chamando aliado Elemental do Água.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'feather-token-anchor',
    name: 'Ficha de Pena (Âncora)',
    englishName: 'Feather Token (Âncora)',
    type: 'Item Mágico (Ficha)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Uma pena arcana encantada que ao ser consumida magicamente executa um grande milagre temático associado (Âncora). Exemplos incluem fazer surgir instantaneamente um barco salva-vidas, crescer um formidável carvalho alto mágico instantaneamente no solo ou virar um pássaro mensageiro veloz.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'feather-token-bird',
    name: 'Ficha de Pena (Pássaro)',
    englishName: 'Feather Token (Pássaro)',
    type: 'Item Mágico (Ficha)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Uma pena arcana encantada que ao ser consumida magicamente executa um grande milagre temático associado (Pássaro). Exemplos incluem fazer surgir instantaneamente um barco salva-vidas, crescer um formidável carvalho alto mágico instantaneamente no solo ou virar um pássaro mensageiro veloz.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'feather-token-fan',
    name: 'Ficha de Pena (Leque)',
    englishName: 'Feather Token (Leque)',
    type: 'Item Mágico (Ficha)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Uma pena arcana encantada que ao ser consumida magicamente executa um grande milagre temático associado (Leque). Exemplos incluem fazer surgir instantaneamente um barco salva-vidas, crescer um formidável carvalho alto mágico instantaneamente no solo ou virar um pássaro mensageiro veloz.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'feather-token-swan-boat',
    name: 'Ficha de Pena (Barco Cisne)',
    englishName: 'Feather Token (Barco Cisne)',
    type: 'Item Mágico (Ficha)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Uma pena arcana encantada que ao ser consumida magicamente executa um grande milagre temático associado (Barco Cisne). Exemplos incluem fazer surgir instantaneamente um barco salva-vidas, crescer um formidável carvalho alto mágico instantaneamente no solo ou virar um pássaro mensageiro veloz.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'feather-token-tree',
    name: 'Ficha de Pena (Árvore)',
    englishName: 'Feather Token (Árvore)',
    type: 'Item Mágico (Ficha)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Uma pena arcana encantada que ao ser consumida magicamente executa um grande milagre temático associado (Árvore). Exemplos incluem fazer surgir instantaneamente um barco salva-vidas, crescer um formidável carvalho alto mágico instantaneamente no solo ou virar um pássaro mensageiro veloz.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'feather-token-whip',
    name: 'Ficha de Pena (Chicote)',
    englishName: 'Feather Token (Chicote)',
    type: 'Item Mágico (Ficha)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Uma pena arcana encantada que ao ser consumida magicamente executa um grande milagre temático associado (Chicote). Exemplos incluem fazer surgir instantaneamente um barco salva-vidas, crescer um formidável carvalho alto mágico instantaneamente no solo ou virar um pássaro mensageiro veloz.',
    value: '500 PO',
    weight: 0.1,
  },
  {
    id: 'horn-of-valhalla-brass',
    name: 'Berrante de Valhalla (Latão)',
    englishName: 'Horn of Valhalla (Latão)',
    type: 'Item Mágico (Berrante)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Berrante sagrado nórdico místico de guerra de Latão. Usando ação para soá-lo convoca destemidos Berserkers espectrais guerreiros ferozes bárbaros pra combater do seu lado (A quantidade de guerreiros e o tipo exato varia da tabela pela raridade material deste berrante). Podendo soá-lo de 7 em 7 dias puros.',
    value: '6.000 PO',
    weight: 2,
  },
  {
    id: 'horn-of-valhalla-bronze',
    name: 'Berrante de Valhalla (Bronze)',
    englishName: 'Horn of Valhalla (Bronze)',
    type: 'Item Mágico (Berrante)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Berrante sagrado nórdico místico de guerra de Bronze. Usando ação para soá-lo convoca destemidos Berserkers espectrais guerreiros ferozes bárbaros pra combater do seu lado (A quantidade de guerreiros e o tipo exato varia da tabela pela raridade material deste berrante). Podendo soá-lo de 7 em 7 dias puros.',
    value: '20.000 PO',
    weight: 2,
  },
  {
    id: 'horn-of-valhalla-iron',
    name: 'Berrante de Valhalla (Ferro)',
    englishName: 'Horn of Valhalla (Ferro)',
    type: 'Item Mágico (Berrante)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: false,
    description: 'Berrante sagrado nórdico místico de guerra de Ferro. Usando ação para soá-lo convoca destemidos Berserkers espectrais guerreiros ferozes bárbaros pra combater do seu lado (A quantidade de guerreiros e o tipo exato varia da tabela pela raridade material deste berrante). Podendo soá-lo de 7 em 7 dias puros.',
    value: '50.000 PO',
    weight: 2,
  },
  {
    id: 'horn-of-valhalla-silver',
    name: 'Berrante de Valhalla (Prata)',
    englishName: 'Horn of Valhalla (Prata)',
    type: 'Item Mágico (Berrante)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: false,
    description: 'Berrante sagrado nórdico místico de guerra de Prata. Usando ação para soá-lo convoca destemidos Berserkers espectrais guerreiros ferozes bárbaros pra combater do seu lado (A quantidade de guerreiros e o tipo exato varia da tabela pela raridade material deste berrante). Podendo soá-lo de 7 em 7 dias puros.',
    value: '50.000 PO',
    weight: 2,
  },
  {
    id: 'wand-of-the-war-mage-1',
    name: 'Varinha do Mago de Guerra +1',
    englishName: 'Wand of the War Mage, +1',
    type: 'Item Mágico (Varinha)',
    category: 'Varinha',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Focador de batalha para arcanos marciais combatentes absolutos que concede passivamente Vantagens fixas concedendo ininterrupto bônus de +1 mágico direto somado nas Jogadas puras exatas dos seus Ataques de Magias disparadas contra inimigos. (Também faz você ignorar meias coberturas de obstáculos).',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'wand-of-the-war-mage-2',
    name: 'Varinha do Mago de Guerra +2',
    englishName: 'Wand of the War Mage, +2',
    type: 'Item Mágico (Varinha)',
    category: 'Varinha',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Focador de batalha para arcanos marciais combatentes absolutos que concede passivamente Vantagens fixas concedendo ininterrupto bônus de +2 mágico direto somado nas Jogadas puras exatas dos seus Ataques de Magias disparadas contra inimigos. (Também faz você ignorar meias coberturas de obstáculos).',
    value: '5.000 PO',
    weight: 1,
  },
  {
    id: 'wand-of-the-war-mage-3',
    name: 'Varinha do Mago de Guerra +3',
    englishName: 'Wand of the War Mage, +3',
    type: 'Item Mágico (Varinha)',
    category: 'Varinha',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Focador de batalha para arcanos marciais combatentes absolutos que concede passivamente Vantagens fixas concedendo ininterrupto bônus de +3 mágico direto somado nas Jogadas puras exatas dos seus Ataques de Magias disparadas contra inimigos. (Também faz você ignorar meias coberturas de obstáculos).',
    value: '15.000 PO',
    weight: 1,
  },
];
