import { SRDItem } from './types';

export const BATCH_9_WEARABLES: SRDItem[] = [
  {
    id: 'boots-of-elvenkind',
    name: 'Botas Élficas',
    englishName: 'Boots of Elvenkind',
    type: 'Item Mágico (Botas)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Enquanto você usar estas botas, seus passos não fazem som, independentemente da superfície na qual você está andando. Você tem vantagem em testes de Destreza (Furtividade) que dependam de se mover silenciosamente.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'boots-of-levitation',
    name: 'Botas de Levitação',
    englishName: 'Boots of Levitation',
    type: 'Item Mágico (Botas)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar estas botas, você pode usar uma ação para conjurar a magia Levitar (Levitate) sobre si mesmo à vontade.',
    value: '4.000 PO',
    weight: 1,
  },
  {
    id: 'boots-of-speed',
    name: 'Botas de Velocidade',
    englishName: 'Boots of Speed',
    type: 'Item Mágico (Botas)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Você pode usar uma ação bônus para clicar os calcanhares das botas. Fazer isso duplica o seu deslocamento e ataques de oportunidade contra você tem desvantagem. O efeito dura 10 minutos diários (pode ser dividido) e recupera pós descanso longo.',
    value: '5.000 PO',
    weight: 1,
  },
  {
    id: 'boots-of-striding-and-springing',
    name: 'Botas de Caminhar e Saltar',
    englishName: 'Boots of Striding and Springing',
    type: 'Item Mágico (Botas)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Seu deslocamento de caminhada não pode ser reduzido abaixo de 9 metros. Além disso, a distância mágica impulsionada dos seus saltos é inteiramente triplicada.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'boots-of-the-winterlands',
    name: 'Botas das Terras Invernais',
    englishName: 'Boots of the Winterlands',
    type: 'Item Mágico (Botas)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Concede resistência a dano de frio. Você ignora terreno difícil criado por gelo/neve e pode tolerar frios extremos.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'bracers-of-archery',
    name: 'Braçadeiras do Arqueiro',
    englishName: 'Bracers of Archery',
    type: 'Item Mágico (Braçadeiras)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Garante proficiência inata e mágica na utilização com Arco Longo e Arco Curto (para classes que não possuam). Garante ainda um fixo +2 a mais nas rolagens contínuas de dano puro nessas armas de flechas.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'bracers-of-defense',
    name: 'Braçadeiras de Defesa',
    englishName: 'Bracers of Defense',
    type: 'Item Mágico (Braçadeiras)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Focado em proteger magos, bárbaros e monges ágeis. Lhe garantem escudo místico defensivo que aumenta somando +2 de CA contínuo enquanto o lutador manter-se perfeitamente sem vestir nenhuma proteção armadura vestida e o braço sem escudo metal.',
    value: '6.000 PO',
    weight: 1,
  },
  {
    id: 'cloak-of-arachnida',
    name: 'Manto do Aracnídeo',
    englishName: 'Cloak of Arachnida',
    type: 'Item Mágico (Capa)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Feita de teia negra sedosa. Concede resistência massiva a Venenos, você também pode subir em teto/paredes como homem-aranha com vel igual de andada sem ocupar mãos. Capa anula ficar colado em teias da magia de monstros, possuindo limite para conjurar 1 magia (Teia) por amanhecer atirada à área em alcance mágico.',
    value: '20.000 PO',
    weight: 1,
  },
  {
    id: 'cloak-of-displacement',
    name: 'Manto do Deslocamento',
    englishName: 'Cloak of Displacement',
    type: 'Item Mágico (Capa)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Possui mágica ilusória protetora da vida, refletindo sempre uma silhueta sua que distorce visualmente a exata 10 cm sua, impondo ativamente penalidade letal de Desvantagem imediata a todas os testes de inimigos te golpeando na rodada inteira. Tomar um simples dano corta o brilho, interrompe as vantagens apenas praquela rodada até a seguinte reiniciar as defesas ativas.',
    value: '6.000 PO',
    weight: 1,
  },
  {
    id: 'cloak-of-elvenkind',
    name: 'Manto Élfico',
    englishName: 'Cloak of Elvenkind',
    type: 'Item Mágico (Capa)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'A cor da capa se adapta ao ambiente (Camuflagem Mágica) com a vegetação ou local rochoso próximo, e encobre-o no silêncio e nas trevas visuais, recebendo Vantagem absoluta de esconder e inimigos adquirem desvantagem aguda passiva num raio (Wisdom Perception) se te buscarem ativamente ali oculto.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'cloak-of-protection',
    name: 'Manto de Proteção',
    englishName: 'Cloak of Protection',
    type: 'Item Mágico (Capa)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Enquanto vestir magicamente envolto e fechado (o manto do mago escudeiro básico), você somará inalteradamente com exímio ganho defensivo de +1 na Classe de armadura final e também ganha os fortes reforços bônus no somatório final de todos Testes de Resistências.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'cloak-of-the-bat',
    name: 'Manto do Morcego',
    englishName: 'Cloak of the Bat',
    type: 'Item Mágico (Capa)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Capa sombria gótica que requer total Trevas ou a noitinha pura no céu. Você ganha Vantagem ativa no esconder furtivo se as usar em escuro, e sob penumbras agarradas nelas (Com As Mãos nas Bordas) te permite planar (vel voo 12m) por toda a caverna; Você também tem magia de encolher mutante a um simples Morcego normal sem itens.',
    value: '6.000 PO',
    weight: 1,
  },
  {
    id: 'cloak-of-the-manta-ray',
    name: 'Manto da Arraia',
    englishName: 'Cloak of the Manta Ray',
    type: 'Item Mágico (Capa)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Ao imergir no mar com esse pano abotoado envolto nas pernas as costas expandem com cartilagens nadadoras em formato raia idêntico; Você ganha brânquias para extrair todo folego d\'água livre, vel. natação passará aos estrondosos 18m subaquáticos rápidos.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'gauntlets-of-ogre-power',
    name: 'Manoplas de Força Ogra',
    englishName: 'Gauntlets of Ogre Power',
    type: 'Item Mágico (Manoplas)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Transformam milagrosamente punhos franzinos. Sua Força bruta orgânica sobe instantaneamente pelo encanto arcano subindo pro exato valor numérico travado absoluto (Força/STR = 19 fixo mágico). Ignorará caso sua já seja superior.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'headband-of-intellect',
    name: 'Tiara do Intelecto',
    englishName: 'Headband of Intellect',
    type: 'Item Mágico (Tiara)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Uma joia cerebral usada na fronte da mente. Subirá brutal e magicamente sem demora seu valor mental arcano e investigativo (Inteligência fixa cravada em 19). Anula se já possuir maior.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'helm-of-brilliance',
    name: 'Elmo do Brilho',
    englishName: 'Helm of Brilliance',
    type: 'Item Mágico (Elmo)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Revestido de safiras, rubis letais mágicos cravados aos punhados nele. (10 diamantes guardam Luz de Dia, 20 Rubis armazenam Muralha chamas, 30 de Bola Fogo explosiva); Eles geram perigos letais se puxados para alvejar mortais longe gastando ação. Ele encanata espadas nobres com +1d6 e destrói (queimaduras mágicas) os mortos-vivos (mortais ou fortes) no mero olhar/presença iluminada.',
    value: '40.000 PO',
    weight: 2,
  },
  {
    id: 'helm-of-comprehending-languages',
    name: 'Elmo da Compreensão de Idiomas',
    englishName: 'Helm of Comprehending Languages',
    type: 'Item Mágico (Elmo)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Concede perfeitamente as bases tradutoras alienígenas ativas. Com sua Action de mente concentrada você decifra e evoca os fluxos (magia divina base de entender idiomas ilimitados).',
    value: '500 PO',
    weight: 2,
  },
  {
    id: 'helm-of-telepathy',
    name: 'Elmo da Telepatia',
    englishName: 'Helm of Telepathy',
    type: 'Item Mágico (Elmo)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Capacete que concede ao usuário o fluxo de (Detectar e bisbilhotar cabeças invisível à vontade). Permite fala neural para qualquer cérebro livre com alcance razoável. O elmo pode enviar "Comandos e sugestões hipnóticas psíquicas" ativas (Wis 13 Save) aos invadidos na rede mística.',
    value: '500 PO',
    weight: 2,
  },
  {
    id: 'helm-of-teleportation',
    name: 'Elmo de Teletransporte',
    englishName: 'Helm of Teleportation',
    type: 'Item Mágico (Elmo)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Elmo dourado dimensional de espaço (Possui 3 Cargas). Gaste (Ação) consumindo o selo cristalino pra pular à magia de transição perigosa extrema "Teleporte (Mago)". Reposiciona você com risco padrão de erro e 1d3 usos mágicos refeitos as manhãs.',
    value: '8.000 PO',
    weight: 2,
  },
  {
    id: 'mantle-of-spell-resistance',
    name: 'Manto de Resistência a Magia',
    englishName: 'Mantle of Spell Resistance',
    type: 'Item Mágico (Capa)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Vestimenta negra arcana blindada. Se focado, te confere pura e direta a massiva imunidade relativa protetora: Vantagem contínua fixa e passiva absoluta (rolará Dados Duplos nas provações) salvando nas rolagens contra efeitos mortais, ilusões e magias letais lançadas em você.',
    value: '5.000 PO',
    weight: 1,
  },
  {
    id: 'winged-boots',
    name: 'Botas Aladas',
    englishName: 'Winged Boots',
    type: 'Item Mágico (Botas)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'As famosas botas celestiais do deus ágil. Pequenas asas de pombo mágico alçam o pé ao espaço por exatas (4 Horas longas voadoras celestes seguidas ou parceladas no dia com base no seu uso voador de caminhada vel normal). Ao cair descem lentas passivas mitigando os danos.',
    value: '500 PO',
    weight: 1,
  }
];
