import { SRDItem } from './types';

export const BATCH_5_ARMORS: SRDItem[] = [
  {
    id: 'adamantine-armor',
    name: 'Armadura de Adamante',
    englishName: 'Adamantine Armor',
    type: 'Armadura Mágica (Qualquer Média ou Pesada)',
    category: 'Armadura',
    rarity: 'Incomum',
    attunement: false,
    description: 'Esta armadura é reforçada com adamante, um dos metais mais duros existentes. Enquanto você estiver usando-a, qualquer acerto crítico contra você se torna um acerto normal.',
    value: '500 PO',
    weight: 20,
  },
  {
    id: 'armor-of-invulnerability',
    name: 'Armadura da Invulnerabilidade',
    englishName: 'Armor of Invulnerability',
    type: 'Armadura Mágica (Placas)',
    category: 'Armadura',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Você ganha resistência a dano não mágico enquanto usar esta armadura. Adicionalmente, você pode usar uma ação para se tornar imune a dano não mágico por 10 minutos ou até não vestir mais a armadura. Após este uso, não pode usá-lo novamente até o próximo amanhecer.',
    value: '50.000 PO',
    weight: 65,
  },
  {
    id: 'armor-of-resistance',
    name: 'Armadura de Resistência',
    englishName: 'Armor of Resistance',
    type: 'Armadura Mágica (Leve, Média ou Pesada)',
    category: 'Armadura',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Você tem resistência a um tipo específico de dano enquanto usar esta armadura (Ácido, Congelante, Concussão, Elétrico, Fogo, Força, Necrótico, Perfurante, Psíquico, Radiante, Trovejante ou Venenoso). O Mestre escolhe o tipo ou determina aleatoriamente.',
    value: '4.000 PO',
    weight: 20,
  },
  {
    id: 'armor-of-vulnerability',
    name: 'Armadura da Vulnerabilidade',
    englishName: 'Armor of Vulnerability',
    type: 'Armadura Mágica (Placas)',
    category: 'Armadura',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto estiver usando esta armadura, você tem resistência a um tipo específico de dano (Concussão, Perfurante ou Cortante). O Mestre escolhe o tipo. Maldição: A armadura também torna você vulnerável aos outros dois tipos. Se for Remover Maldição, só desfaz a sintonização.',
    value: '3.000 PO',
    weight: 65,
  },
  {
    id: 'demon-armor',
    name: 'Armadura Demoníaca',
    englishName: 'Demon Armor',
    type: 'Armadura Mágica (Placas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto estiver usando esta armadura incrustada de garras e chifres, você recebe +1 na CA e pode compreender Abissal. As manoplas são armas mágicas com +1 e causam 1d8 dano cortante. Maldição: Você tem desvantagem em testes de resistência de Sabedoria contra feitiços lançados por corruptores (fiends).',
    value: '18.000 PO',
    weight: 65,
  },
  {
    id: 'dragon-scale-mail',
    name: 'Cota de Escamas de Dragão',
    englishName: 'Dragon Scale Mail',
    type: 'Armadura Mágica (Cota de Escamas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Concede +1 na CA, vantagem em TR contra Sopro de Dragão e Presença Aterradora. Dá resistência a um tipo de dano que o dragão original tinha (ex: Fogo). Uma vez por dia você percebe telepaticamente a localização de dragões daquela espécie até 48 km.',
    value: '20.000 PO',
    weight: 45,
  },
  {
    id: 'dwarven-plate',
    name: 'Placas Anãs',
    englishName: 'Dwarven Plate',
    type: 'Armadura Mágica (Placas)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Concede +2 de bônus na CA. Se um efeito te empurrar para trás (e não for um ataque corpo a corpo), o efeito só te empurra metade se for menos de 3m, mas ignora repulsão de até 3m perfeitamente.',
    value: '15.000 PO',
    weight: 65,
  },
  {
    id: 'efreeti-chain',
    name: 'Malha de Efreeti',
    englishName: 'Efreeti Chain',
    type: 'Armadura Mágica (Cota de Malha)',
    category: 'Armadura',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Concede +3 na CA, resistência ao fogo e você pode falar o idioma Primordial. Você consegue andar sob superfícies ardentes ileso e pode ignorar o frio extremo mágico e não mágico.',
    value: '50.000 PO',
    weight: 55,
  },
  {
    id: 'elven-chain',
    name: 'Malha Élfica',
    englishName: 'Elven Chain',
    type: 'Armadura Mágica (Camisão de Cota de Malha)',
    category: 'Armadura',
    rarity: 'Incomum',
    attunement: false,
    description: 'Garante +1 na CA. Adicionalmente, você é considerado proficiente com a armadura, mesmo que você não possua proficiência com armaduras médias. Perfeita para magos.',
    value: '4.000 PO',
    weight: 20,
  },
  {
    id: 'glamoured-studded-leather',
    name: 'Couro Batido Glamour',
    englishName: 'Glamoured Studded Leather',
    type: 'Armadura Mágica (Couro Batido)',
    category: 'Armadura',
    rarity: 'Rara',
    attunement: false,
    description: '+1 de bônus na CA. Usando uma ação bônus você cria a ilusão que a transforma visualmente em roupas comuns civis ou uniformes para observadores desavisados.',
    value: '5.000 PO',
    weight: 13,
  },
  {
    id: 'mariners-armor',
    name: 'Armadura de Marinheiro',
    englishName: "Mariner's Armor",
    type: 'Armadura Mágica (Qualquer Média ou Leve)',
    category: 'Armadura',
    rarity: 'Incomum',
    attunement: false,
    description: 'Dá deslocamento de natação equivalente ao de caminhada. Você subirá magicamente (bóia rumo à superfície) a 18 metros/rodada automaticamente se chegar a 0 PV submerso.',
    value: '1.500 PO',
    weight: 13,
  },
  {
    id: 'mithral-armor',
    name: 'Armadura de Mitral',
    englishName: 'Mithral Armor',
    type: 'Armadura Mágica (Qualquer Média/Pesada que não use Couro)',
    category: 'Armadura',
    rarity: 'Incomum',
    attunement: false,
    description: 'Super leve e resistente, esta armadura ignora a necessidade mínima de força caso seja Pesada, e não impõe desvantagem em testes de Furtividade.',
    value: '800 PO',
    weight: 20,
  },
  {
    id: 'plate-armor-of-etherealness',
    name: 'Armadura de Placas Etérea',
    englishName: 'Plate Armor of Etherealness',
    type: 'Armadura Mágica (Placas)',
    category: 'Armadura',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Uma vez por dia sob a pronúncia da palavra de comando (Ação), você recebe os benefícios irrestritos da magia Forma Etérea (Etherealness) durante exatos 10 minutos seguidos.',
    value: '40.000 PO',
    weight: 65,
  },
  {
    id: 'sentinel-shield',
    name: 'Escudo da Sentinela',
    englishName: 'Sentinel Shield',
    type: 'Escudo Mágico',
    category: 'Armadura',
    rarity: 'Incomum',
    attunement: false,
    description: 'Enquanto estiver empunhando este escudo decorado com um olho mágico, você tem Vantagem contínua nos testes de Iniciativa e nos testes de Sabedoria (Percepção).',
    value: '600 PO',
    weight: 6,
  },
  {
    id: 'shield-of-missile-attraction',
    name: 'Escudo de Atração de Projéteis',
    englishName: 'Shield of Missile Attraction',
    type: 'Escudo Mágico',
    category: 'Armadura',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto empunha este escudo, ataques à distância que visem criaturas a até 3m de você mudam o alvo e focam em você, mas em compensação ele garante Resistência ativa contra armas de ataque à distância.',
    value: '3.000 PO',
    weight: 6,
  },
  {
    id: 'spellguard-shield',
    name: 'Escudo do Guardião de Magia',
    englishName: 'Spellguard Shield',
    type: 'Escudo Mágico',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto você o empunha, você recebe Vantagem nos seus testes de resistência contra magias e outros efeitos mágicos, e jogadas de ataque mágico feitas contra você tem Desvantagem.',
    value: '22.000 PO',
    weight: 6,
  }
];
