import { SRDSpell } from './types';

export const BATCH_3_SPELLS: SRDSpell[] = [
  // NÍVEL 4
  {
    id: 'arcane-eye',
    name: 'Olho Arcano (Arcane Eye)',
    englishName: 'Arcane Eye',
    level: 4,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pouco de pelo de morcego', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'single_target', formatted: '1 Sensor Mágico Invisível' },
    damageSave: { attackType: 'utility' },
    description: 'Você cria um olho mágico invisível no alcance que flutua. O olho possui visão normal e visão no escuro de 9 metros. Como uma ação, você pode mover o olho até 9 metros. O olho pode se esgueirar por aberturas pequenas de 2,5 cm.',
    classes: ['Mago']
  },
  {
    id: 'confusion',
    name: 'Confusão (Confusion)',
    englishName: 'Confusion',
    level: 4,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '27 metros (90 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'três cascas de nozes', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 3, sizeUnit: 'm', formatted: 'Esfera de 3m' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Criaturas em uma esfera de 3m de raio devem passar num TR Sabedoria ou ficarão confusas. Uma criatura afetada não pode reagir e rola 1d10 todo turno para decidir o que fará: 1=Não se move, 2-6=Não age e move em direção aleatória, 7-8=Ataca corpo a corpo alvo aleatório, 9-10=Age normalmente.',
    classes: ['Bardo', 'Druida', 'Feiticeiro', 'Mago']
  },
  {
    id: 'conjure-minor-elementals',
    name: 'Conjurar Elementais Menores (Conjure Minor Elementals)',
    englishName: 'Conjure Minor Elementals',
    level: 4,
    school: 'Conjuração',
    castingTime: '1 minuto',
    range: '27 metros (90 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Elementais' },
    damageSave: { attackType: 'utility' },
    description: 'Você invoca elementais que aparecem num espaço desocupado. Você escolhe uma das opções: 1 elemental de ND 2, 2 elementais de ND 1, 4 de ND 1/2 ou 8 de ND 1/4. Eles somem quando caem a 0 PV ou a magia acabar. Eles são aliados e obedecem seus comandos verbais. Role iniciativa por grupo.',
    classes: ['Druida', 'Mago']
  },
  {
    id: 'conjure-woodland-beings',
    name: 'Conjurar Seres da Floresta (Conjure Woodland Beings)',
    englishName: 'Conjure Woodland Beings',
    level: 4,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma baga de azevinho', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Fadas' },
    damageSave: { attackType: 'utility' },
    description: 'Você invoca fadas. Escolha: 1 fada de ND 2, 2 de ND 1, 4 de ND 1/2, ou 8 de ND 1/4. Elas obedecem ordens verbais suas e são amigáveis. Desaparecem a 0 PV ou ao fim da magia.',
    classes: ['Druida', 'Patrulheiro']
  },
  {
    id: 'control-water',
    name: 'Controlar a Água (Control Water)',
    englishName: 'Control Water',
    level: 4,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '90 metros (300 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma gota de água e pó', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 30, sizeUnit: 'm', formatted: 'Cubo de 30m' },
    damageSave: { attackType: 'utility' },
    description: 'Até a magia acabar, você controla água em área de 30 metros. Ações disponíveis no seu turno: Enchente (eleva em 6m), Afastar a Água (cria uma trincheira sem água), Redirecionar Fluxo (muda direção da correnteza) ou Redemoinho (puxa criaturas, TR Força ou dano contundente de 2d8).',
    classes: ['Clérigo', 'Druida', 'Mago']
  },
  {
    id: 'death-ward',
    name: 'Proteção contra a Morte (Death Ward)',
    englishName: 'Death Ward',
    level: 4,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura. A primeira vez que ela cairia a 0 PV através de dano, ela cai para 1 PV em vez disso, e a magia se encerra. Se alvo estivesse sofrendo efeito que mate instantaneamente sem dar dano, a magia anula o efeito e também encerra.',
    classes: ['Clérigo', 'Paladino']
  },
  {
    id: 'evards-black-tentacles',
    name: 'Tentáculos Negros (Black Tentacles)',
    englishName: "Evard's Black Tentacles",
    level: 4,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '27 metros (90 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pedaço de tentáculo de polvo/lula gigante', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'square', sizeValue: 6, sizeUnit: 'm', formatted: 'Quadrado de 6m' },
    damageSave: { damageDice: '3d6', damageType: 'Contundente', saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Tentáculos de borracha negros preenchem um quadrado de 6 metros. O terreno é difícil. Quando criatura entra ou começa turno lá: TR Destreza ou 3d6 dano contundente + Presa (Restrained). Criatura presa sofre 3d6 no início de seu turno. Teste de Força ou Destreza (CD Magia) para fugir.',
    classes: ['Mago']
  },
  {
    id: 'fire-shield',
    name: 'Escudo de Fogo (Fire Shield)',
    englishName: 'Fire Shield',
    level: 4,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '10 minutos',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pedaço de fósforo ou de vaga-lume', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { damageDice: '2d8', damageType: 'Fogo/Frio', attackType: 'utility' },
    description: 'Chamas finas lhe cobrem. Escolha Escudo Cálido (você resiste a Frio, quem bater a 1,5m em você com corpo a corpo sofre 2d8 de dano de Fogo) ou Escudo Gélido (você resiste a Fogo, e causa 2d8 dano de Frio aos que lhe batem). O fogo emite luz num raio de 3m/6m.',
    classes: ['Mago']
  },
  {
    id: 'freedom-of-movement',
    name: 'Movimentação Livre (Freedom of Movement)',
    englishName: 'Freedom of Movement',
    level: 4,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'tira de couro amarrada ao pulso', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura voluntária. Pela duração, o alvo imune a penalidades de Terreno Difícil e não pode ficar Paralisado ou Preso magicamente. Pode usar 1.5m mov pra escapar de agarres não-mágicos, sem rolar. Sem penalidade lutar submerso.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Patrulheiro']
  },
  {
    id: 'greater-invisibility',
    name: 'Invisibilidade Maior (Greater Invisibility)',
    englishName: 'Greater Invisibility',
    level: 4,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Você ou uma criatura tocada ficam completamente invisíveis, e todo equipamento/vestimenta dela também. A magia não quebra caso o alvo ataque ou conjure outras magias.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'guardian-of-faith',
    name: 'Guardião da Fé (Guardian of Faith)',
    englishName: 'Guardian of Faith',
    level: 4,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'area', shape: 'single_target', formatted: 'Guardião Espectral Grande' },
    damageSave: { damageDice: '20', damageType: 'Radiante', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Um guardião espectral paira. Criatura hostil que mover a até 3m dele rola TR Destreza, levando 20 dano radiante na falha e 10 sucesso. Ele dissipa-se ao aplicar um total de 60 de dano nas criaturas inimigas.',
    classes: ['Clérigo']
  },
  {
    id: 'hallucinatory-terrain',
    name: 'Terreno Alucinatório (Hallucinatory Terrain)',
    englishName: 'Hallucinatory Terrain',
    level: 4,
    school: 'Ilusão',
    castingTime: '10 minutos',
    range: '90 metros (300 pés)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'areia e espinhos', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 45, sizeUnit: 'm', formatted: 'Cubo de 45m' },
    damageSave: { attackType: 'utility' },
    description: 'Você faz o terreno num cubo de 45m mudar seu visual para parecer outro tipo de ambiente natural (floresta que parece pântano). Construções artificiais originais não disfarçam. Interações podem investigar Ilusão com TR de Investigação(INT) contra a CD.',
    classes: ['Bardo', 'Druida', 'Bruxo', 'Mago']
  },
  {
    id: 'ice-storm',
    name: 'Tempestade de Gelo (Ice Storm)',
    englishName: 'Ice Storm',
    level: 4,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '90 metros (300 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pitada de poeira e gotas dágua', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cylinder', sizeValue: 6, sizeUnit: 'm', formatted: 'Cilindro de 6m raio, 12m alt' },
    damageSave: { damageDice: '2d8 + 4d6', damageType: 'Contundente/Frio', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Bolas de gelo granizo despencam num cilindro 6m raio 12m altura. Cada criatura nele: TR Destreza. 2d8 Contundente + 4d6 Frio. Metade num sucesso. Terreno vira difícil até o final de seu turno seguinte.',
    classes: ['Druida', 'Feiticeiro', 'Mago']
  },
  {
    id: 'locate-creature',
    name: 'Localizar Criatura (Locate Creature)',
    englishName: 'Locate Creature',
    level: 4,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'fio de cabelo ou rastro', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 300, sizeUnit: 'm', formatted: 'Esfera de 300m' },
    damageSave: { attackType: 'utility' },
    description: 'Descreva criatura com que é familiar ou genérica. Pela duração, você sabe a direção até ela. Falha se ela estiver a mais de 300m, protegida magicamente, ou tiver água corrente impedindo o caminho de 3m.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Paladino', 'Patrulheiro', 'Mago']
  },
  {
    id: 'otilukes-resilient-sphere',
    name: 'Esfera Resiliente (Resilient Sphere)',
    englishName: "Otiluke's Resilient Sphere",
    level: 4,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'casca de ovo quebrado, diamante', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { saveStat: 'DEX', saveEffect: 'negate', attackType: 'save' },
    description: 'Esfera imune engolfa criatura ou objeto se caber num domo da esfera luminosa (Médio). Não pode ser danificada ou atravessada (exceto Desintegrar). Criatura ali pode rolar a bola de hamster.',
    classes: ['Mago']
  },
  {
    id: 'phantasmal-killer',
    name: 'Assassino Fantasmagórico (Phantasmal Killer)',
    englishName: 'Phantasmal Killer',
    level: 4,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '4d10', damageType: 'Psíquico', saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'O alvo percebe a ilusão de seus maiores medos mortais (que ele mesmo alucina). TR Sabedoria, falha = Assustado (Frightened). Enquanto Assustado nisto, ele toma 4d10 Psíquico no início de seu próprio turno, podendo repetir teste Sabedoria pra encerrar o efeito.',
    classes: ['Mago']
  },
  {
    id: 'stoneskin',
    name: 'Pele de Pedra (Stoneskin)',
    englishName: 'Stoneskin',
    level: 4,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'pó de diamante de 100 PO (consumido)', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'A pele de um alvo tocado fica de pedra, e ganha Resistência a Dano de ataques corpo a corpo (contundente, perfurante e cortante) que sejam de origem não-mágica.',
    classes: ['Druida', 'Patrulheiro', 'Feiticeiro', 'Mago']
  },
  {
    id: 'wall-of-fire',
    name: 'Muralha de Fogo (Wall of Fire)',
    englishName: 'Wall of Fire',
    level: 4,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'fósforo e cera', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'wall', sizeValue: 18, sizeUnit: 'm', formatted: 'Muralha de 18m compr.' },
    damageSave: { damageDice: '5d8', damageType: 'Fogo', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Uma muralha opaca de 18m comp x 6m altura x 30cm exp. Surge. Criaturas lá na invocação rolam TR Destreza p/ evitar o 5d8 de Fogo, e uma das faces laterais emite ondas de 5d8 num raio de 3m da muralha e pra todo mundo que pular ou terminar ali perto.',
    classes: ['Druida', 'Feiticeiro', 'Mago']
  },

  // NÍVEL 5
  {
    id: 'animate-objects',
    name: 'Animar Objetos (Animate Objects)',
    englishName: 'Animate Objects',
    level: 5,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 10 Objetos Inanimados' },
    damageSave: { attackType: 'utility' },
    description: 'Anima até dez objetos inanimados de tamanho Miúdo (cada conta 1), ou objetos maiores consumindo aspas múltiplas (Pequeno 1, Médio 2, Grande 4, Enorme 8). Eles possuem HP, CA, e ataque dependente do tamanho com base na classe de objeto, e você rege eles mentalmente.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'awaken',
    name: 'Despertar (Awaken)',
    englishName: 'Awaken',
    level: 5,
    school: 'Transmutação',
    castingTime: '8 horas',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'ágata valendo 1.000 PO (consumido)', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Besta ou Planta Enorme/Menor' },
    damageSave: { attackType: 'utility' },
    description: 'Você dá senciência animal, elevando Inteligência pra 10 para uma Fera / Planta não senciente e permite fala nativa nela. Fica Charme por 30 dias se amigável. Planta ganha forma móvel parecida com Ent / arbusto ambulante.',
    classes: ['Bardo', 'Druida']
  },
  {
    id: 'cloudkill',
    name: 'Névoa Mortal (Cloudkill)',
    englishName: 'Cloudkill',
    level: 5,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 6, sizeUnit: 'm', formatted: 'Esfera de 6m raio' },
    damageSave: { damageDice: '5d8', damageType: 'Veneno', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Névoa de 6m de raio de veneno letal pesada bloqueia a visão. Cada criatura (mesmo retendo ar) começando o turno lá toma TR Constituição pra não levar 5d8 Veneno, ou 1/2 no Sucedido. A névoa rola 3 metros por si só a longe de você por turno.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'commune',
    name: 'Comunhão (Commune)',
    englishName: 'Commune',
    level: 5,
    school: 'Adivinhação',
    castingTime: '1 minuto',
    range: 'Pessoal',
    duration: '1 minuto',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'incenso e ampola divinadora (água/benta)', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Contacta sua Deidade por poder. Faça até três (3) perguntas fechadas de SIM/NÃO relativas à sua religião e o mestre responderá divinamente corretamente num sopro, contanto que seja num limite universal (ou responde Inseguro).',
    classes: ['Clérigo']
  },
  {
    id: 'conjure-elemental',
    name: 'Conjurar Elemental (Conjure Elemental)',
    englishName: 'Conjure Elemental',
    level: 5,
    school: 'Conjuração',
    castingTime: '1 minuto',
    range: '27 metros (90 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'cálice de água ou poeira, etc. dependendo do Elemental', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Elemental ND 5' },
    damageSave: { attackType: 'utility' },
    description: 'O conjurador tira do pranto do elemento natural vizinho: cria 1 Elemental Fogo/Água/Terra/Ar (até ND 5) lá. Aliado aos teus comandos. Se você perder CONCENTRAÇÃO, o elemental FICA no plano e vira Hostil com você para a morte até sumir dps 1 hr.',
    classes: ['Druida', 'Mago']
  },
  {
    id: 'contact-other-plane',
    name: 'Contato Extraplanar (Contact Other Plane)',
    englishName: 'Contact Other Plane',
    level: 5,
    school: 'Adivinhação',
    castingTime: '1 minuto',
    range: 'Pessoal',
    duration: '1 minuto',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { saveStat: 'INT', saveEffect: 'negate', attackType: 'save' },
    description: 'Mentalmente contacta demônio ou ser alheio alienígena pra 5 respostas de sim/não. VOCÊ TEM QUE passar TR de Inteligência 15 ou sofre 6d6 Psíquico, e fica Insano. Numa vez segura (Sim/Não/Tavez/Desconhecido etc).',
    classes: ['Bruxo', 'Mago']
  },
  {
    id: 'contagion',
    name: 'Praga (Contagion)',
    englishName: 'Contagion',
    level: 5,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '7 dias',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'melee_spell' },
    description: 'Ataque corpo-a-corpo mágico. Se acertar, aplica veneno base (envenenado). No final de 3 turnos dele ele realiza 3 TR CON; se passar na maioria o feitiço falha. Se perder na maioria dos TR a criatura é acometida por uma super doença severa escolhida que paralisa atributos / cegueira prolongada (febre de tremores etc).',
    classes: ['Clérigo', 'Druida']
  },
  {
    id: 'creation',
    name: 'Criação (Creation)',
    englishName: 'Creation',
    level: 5,
    school: 'Ilusão',
    castingTime: '1 minuto',
    range: '9 metros (30 pés)',
    duration: 'Especial',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'argila ou tecido miniatura amarrado num barbante pequeno', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 1.5, sizeUnit: 'm', formatted: '1 Objeto de até 1.5m' },
    damageSave: { attackType: 'utility' },
    description: 'Molda material mágico da Sombra em objeto inanimado que perdura de alguns minutos a algumas horas a depender da matéria real imitada (Metal raro = 1 minuto / Cordas, Madeira = 12h-24h).',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'dominate-person',
    name: 'Dominar Pessoa (Dominate Person)',
    englishName: 'Dominate Person',
    level: 5,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Humanóide' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Domina humanóide com telepatia. A criatura se torna Enfeitiçada (Charm), se você lutar ganha Desvantagem TR Sab. Você dá comandos telepáticos diretos com ação ou pega o controle total físico pra rodar ataques pro grupo, agindo como avatar remoto, exigindo apenas a sua Ação Normal a cada rodada. Termina dps TR caso ela tomar danos extras.',
    classes: ['Bardo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'dream',
    name: 'Sonho (Dream)',
    englishName: 'Dream',
    level: 5,
    school: 'Ilusão',
    castingTime: '1 minuto',
    range: 'Especial (Ilimitado)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'punhado de areia negra', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura Alvo que dorme' },
    damageSave: { damageDice: '3d6', damageType: 'Psíquico', saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'O Mensageiro (Você ou outro) invade os sonhos de uma criatura onde quer q ele durma para fazer RP total. Pode agir monstruoso assustando ele (TR Sab para não tomar 3d6 Psíquico no despertar e o impedir de receber os benefícios da Cura de Descanso Longo).',
    classes: ['Bardo', 'Bruxo', 'Mago']
  },
  {
    id: 'geas',
    name: 'Missão (Geas)',
    englishName: 'Geas',
    level: 5,
    school: 'Encantamento',
    castingTime: '1 minuto',
    range: '18 metros (60 pés)',
    duration: '30 dias',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '5d10', damageType: 'Psíquico', saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Força uma missão (TR Sabedoria). A criatura Enfeitiçada não fará atividades proibidas e buscará realizar seu comando. Uma falha de quebrar/não fazer a missão, sofre terríveis 5d10 dano Psíquico uma vez ao dia pela infração desleal, punição severa do encanto.',
    classes: ['Bardo', 'Clérigo', 'Druida', 'Paladino', 'Mago']
  },
  {
    id: 'greater-restoration',
    name: 'Restauração Maior (Greater Restoration)',
    englishName: 'Greater Restoration',
    level: 5,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'pó de diamante equivalente a 100 PO (consumido)', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Você imbui criatura neutralizando Encantamento (Charm/Maldição) Petrificado, Pontos de Atributos Sugados Reduzidos em Drenagem, nível Exausto.',
    classes: ['Bardo', 'Clérigo', 'Druida']
  },
  {
    id: 'mass-cure-wounds',
    name: 'Curar Ferimentos em Massa (Mass Cure Wounds)',
    englishName: 'Mass Cure Wounds',
    level: 5,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 9, sizeUnit: 'm', formatted: '6 Criaturas em 9m raio' },
    damageSave: { damageDice: '3d8 + mod', damageType: 'Cura', attackType: 'utility' },
    description: 'Uma explosão radiante cura todos ao redor. Escolha 6 aliados no ponto, que se recuperam em 3d8 + Sua Habilidade. (Não afeta Zumbis).',
    classes: ['Bardo', 'Clérigo', 'Druida']
  },
  {
    id: 'modify-memory',
    name: 'Modificar Memória (Modify Memory)',
    englishName: 'Modify Memory',
    level: 5,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Reescreve memória base recente (TR Sab, Enfeitiçada e atordoada no 1 minuto, onde você fala pra descrever 1 evento dos últimos 24h a sumir ou modificar 10min de memória falsos pro alvo acreditar ser 100% verídica).',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'raise-dead',
    name: 'Reviver os Mortos (Raise Dead)',
    englishName: 'Raise Dead',
    level: 5,
    school: 'Necromancia',
    castingTime: '1 hora',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'diamante avaliado em 500 PO consumido', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura morta há 10 dias' },
    damageSave: { attackType: 'utility' },
    description: 'Ressuscita cadáver que não esteja apodrecendo por mais de 10 dias com sua alma disposta a retornar. Regressa a 1 HP mas sob -4 penalidade universal (rolagens jogadas testes), sumindo gradativamente com Descansos Longos.',
    classes: ['Bardo', 'Clérigo', 'Paladino']
  },
  {
    id: 'reincarnate',
    name: 'Reencarnação (Reincarnate)',
    englishName: 'Reincarnate',
    level: 5,
    school: 'Transmutação',
    castingTime: '1 hora',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'óleos raros puros avaliados em 1000 PO consumidos', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Usa um pedacinho de corpo/pêlo da vítima, refaz e atrai a alma dela formando uma NOVA RAÇA DE CORPO FISICO (Roletado aleatoriamente D100 Tabela da Raça como Orc, Halfling, Elfo, Humano, Gnomo, Anão) adulto saudável para viver a continuação mental e memórias e classe.',
    classes: ['Druida']
  },
  {
    id: 'wall-of-force',
    name: 'Muralha de Energia (Wall of Force)',
    englishName: 'Wall of Force',
    level: 5,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pouco de vidro pó cristal fino', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'wall', sizeValue: 6, sizeUnit: 'm', formatted: 'Painéis 3x3 ou Domo 6m' },
    damageSave: { attackType: 'utility' },
    description: 'Parede de energia que cruza o plano etéreo invisivel intransponivel, nenhuma magia, dano ou coisa passa, sequer imune ao dissipar magia (só Desintegrar anula / apaga a magia brutalmente).',
    classes: ['Mago']
  },
  {
    id: 'wall-of-stone',
    name: 'Muralha de Pedra (Wall of Stone)',
    englishName: 'Wall of Stone',
    level: 5,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'bloco gema ou barro de argila', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'wall', sizeValue: 30, sizeUnit: 'm', formatted: 'Até 10 Painéis 3x3 de rocha grossa' },
    damageSave: { saveStat: 'DEX', saveEffect: 'negate', attackType: 'utility' },
    description: 'Invoca uma parede dura real de pedra 15 cm de espessura (ou 30cm mais curta) se funde à rocha da terra / piso, provendo Cobertura e Obscurecimento. AC 15 HPs (30 HP) painel. Se Concentrar o Tempo total, parede FICA e é PERMANENTE (Transmutada de forma verídica).',
    classes: ['Druida', 'Mago']
  },

  // NÍVEL 6
  {
    id: 'blade-barrier',
    name: 'Barreira de Lâminas (Blade Barrier)',
    englishName: 'Blade Barrier',
    level: 6,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '27 metros (90 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'wall', sizeValue: 30, sizeUnit: 'm', formatted: '30m compr, 6m alt' },
    damageSave: { damageDice: '6d10', damageType: 'Cortante', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Cria tempestade densa e zunidora que fere severamente quem ficar nas lâminas circulares afiadas giratórias 6d10 cortante na passarela e provê Três Quartos de cobertura impenetrável por mísseis da magia. Dificulta deslocamento cortando na falha (TR Destreza).',
    classes: ['Clérigo']
  },
  {
    id: 'chain-lightning',
    name: 'Corrente de Relâmpagos (Chain Lightning)',
    englishName: 'Chain Lightning',
    level: 6,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '45 metros (150 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'cabelos / pele marta ou fios prateados / vidro pino', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: '1 Alvo Inicial + 3 Alvos Secundários' },
    damageSave: { damageDice: '10d8', damageType: 'Elétrico', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Raio letal avança sobre o principal 10d8 Eletricidade e ricocheteia arcos para os outros 3 próximos q tiverem na até 9m, TR de destreza em todos reduz dano. Dano poderoso num grupo aglomerado.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'find-the-path',
    name: 'Encontrar o Caminho (Find the Path)',
    englishName: 'Find the Path',
    level: 6,
    school: 'Adivinhação',
    castingTime: '1 minuto',
    range: 'Pessoal',
    duration: 'Até 1 dia',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'itens topográficos ou instrumentos oráculos de 100 POs', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Mostra o caminho físico exato/menor a destino natural fixo e não mágico na localidade q tenha presenciado ou tenha pertences dele pra saber as escolhas geográficas (como passar a muralha X a pé até as escadas Y).',
    classes: ['Bardo', 'Clérigo', 'Druida']
  },
  {
    id: 'globe-of-invulnerability',
    name: 'Globo de Invulnerabilidade (Globe of Invulnerability)',
    englishName: 'Globe of Invulnerability',
    level: 6,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Pessoal (raio 3m)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'bola vidro miuda de argila cristal', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 3, sizeUnit: 'm', formatted: 'Cúpula mágica esfera 3m' },
    damageSave: { attackType: 'utility' },
    description: 'O feitiço impede Magias de conjuradores nivel 1º ao 5º passarem a quem está dentro. Os efeitos não rolam se eles o conjurarem para os seres do centro, protegendo brutalmente feitiços e efeitos pesados da classe adversaria. Pode ser upcasted.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'harm',
    name: 'Doença Plena (Harm)',
    englishName: 'Harm',
    level: 6,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '14d6', damageType: 'Necrótico', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Doença devastadora corrompe carne. Alvo (TR Const) sofre 14d6 dano Necrótico profundo letal e seu MAX de vida Ponto de Vida Total diminui pela exata quantidade tomada por 1 hora. Não cai abaixo de 1 PV, mas beira a morte (Não destrói nem construtos/morto vivos).',
    classes: ['Clérigo']
  },
  {
    id: 'heal',
    name: 'Cura Completa (Heal)',
    englishName: 'Heal',
    level: 6,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '70', damageType: 'Cura', attackType: 'utility' },
    description: 'O poder radiante supremo: Você cura num instante mágico exatos 70 Pontos de Vida, dissipa cegueira surdez pragas normais na vítima imediato com toque.',
    classes: ['Clérigo', 'Druida']
  },
  {
    id: 'programmed-illusion',
    name: 'Ilusão Programada (Programmed Illusion)',
    englishName: 'Programmed Illusion',
    level: 6,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: 'Até dissipada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: '25 PO velo marta, safira gema fina prateada', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 9, sizeUnit: 'm', formatted: 'Cubo ilusório de cenas 9m' },
    damageSave: { saveStat: 'INT', saveEffect: 'negate', attackType: 'utility' },
    description: 'Sons, Cheiros de Ilusão ficam gravadas num loop/código "gatilho" na masmorra/cenario, se ativando, por 5 mins e repetindo na parede/teto (Dragão voando assustador q passa pra enganar os players nas costas). Fica ativa e engatilhada.',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'sunbeam',
    name: 'Raio Solar (Sunbeam)',
    englishName: 'Sunbeam',
    level: 6,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Pessoal (linha de 18m)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um prisma ou lente solar', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'line', sizeValue: 18, sizeUnit: 'm', formatted: 'Feixe (Linha) de 18m comp x 1.5m' },
    damageSave: { damageDice: '6d8', damageType: 'Radiante', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Um pilar radiante (Linha 18m). Todos nele tomam TR Cons. 6d8 radiante e Cegueira ao falhar. (Metade se passar sem cegar). Morto/vivos,Limo desvantagem. Pela concentração, o conjurador solta AÇÕES repetidas p/ criar o relâmpago de SOL sempre que precisar com as mesmas penalidades de raio no turno!',
    classes: ['Druida', 'Feiticeiro', 'Mago']
  },
  {
    id: 'true-seeing',
    name: 'Visão da Verdade (True Seeing)',
    englishName: 'True Seeing',
    level: 6,
    school: 'Adivinhação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'ungüento raro precioso (cogumelo/mirra, pó rubi safira 25 po) no olho', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura Voluntária' },
    damageSave: { attackType: 'utility' },
    description: 'Criatura passa enxergar 36m Ilusões verdadeiras (detecta shapechangers disfarces metarmofos), portais do Plano Etereo ao olhar da natureza.',
    classes: ['Bardo', 'Clérigo', 'Bruxo', 'Mago']
  }
];
