import { SRDItem } from './types';

export const BATCH_7_WONDROUS_J_Z: SRDItem[] = [
  {
    id: 'lantern-of-revealing',
    name: 'Lanterna de Revelação',
    englishName: 'Lantern of Revealing',
    type: 'Item Mágico (Lanterna)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Queima por 6h o frasco puro de óleo. Traz luz brilhante em 9m. Todos os seres invisíveis ocultos dentro desta luz surgem materializados perfeitamente à visão como eles realmente são.',
    value: '600 PO',
    weight: 2,
  },
  {
    id: 'manual-of-bodily-health',
    name: 'Manual de Saúde Corporal',
    englishName: 'Manual of Bodily Health',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Lendo ativamente (48h/6 dias), a sua Constituição Máxima será perpetuada recebendo 2 Pontos extras (Mesmo ultrapassando 20). Após lido fecha a magia por 1 século.',
    value: '20.000 PO',
    weight: 5,
  },
  {
    id: 'manual-of-gainful-exercise',
    name: 'Manual de Exercício Físico (Ganho)',
    englishName: 'Manual of Gainful Exercise',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Lendo (48h/6 dias), confere ao leitor aumento massivo fixo +2 de Força (Strength Max), expandindo os limites para o máximo. Recupera mágica após um século de lido.',
    value: '20.000 PO',
    weight: 5,
  },
  {
    id: 'manual-of-quickness-of-action',
    name: 'Manual de Ação Rápida',
    englishName: 'Manual of Quickness of Action',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Lendo (48h/6 dias), confere +2 permanente em Destreza (Agilidade e Reflexos). Limites estendidos perpetuamente. Perca a magia do exemplar durante 1 século.',
    value: '20.000 PO',
    weight: 5,
  },
  {
    id: 'tome-of-clear-thought',
    name: 'Tomo do Pensamento Claro',
    englishName: 'Tome of Clear Thought',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Lendo (48h/6 dias), proporciona um Intelecto aguçado (+2 Inteligência fixo Permanente). O livro esgota o misticismo e repousa por cem anos sem poderes.',
    value: '20.000 PO',
    weight: 5,
  },
  {
    id: 'tome-of-leadership-and-influence',
    name: 'Tomo de Liderança e Influência',
    englishName: 'Tome of Leadership and Influence',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Lendo (48h/6 dias), provê +2 em Carisma absoluto (Aumenta o limite global acima do 20 para seu personagem). A magia descansa um século inteiro.',
    value: '20.000 PO',
    weight: 5,
  },
  {
    id: 'tome-of-understanding',
    name: 'Tomo da Compreensão',
    englishName: 'Tome of Understanding',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Lendo (48h/6 dias), Sabedoria (Wisdom Max) tem incremento mágico fixado em +2 para a vida toda.',
    value: '20.000 PO',
    weight: 5,
  },
  {
    id: 'manual-of-golems',
    name: 'Manual de Golens',
    englishName: 'Manual of Golems',
    type: 'Item Mágico (Livro)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Apenas conjuradores divinos/arcanos leem a complexidade rúnica, garantindo-lhes poder criar (gastando em ouro 120 dias) vida artificial leal: um Golem que obedece seus criadores passivamente sem pestanejar. As páginas queimam.',
    value: '50.000 PO',
    weight: 5,
  },
  {
    id: 'necklace-of-adaptation',
    name: 'Colar de Adaptação',
    englishName: 'Necklace of Adaptation',
    type: 'Item Mágico (Colar)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Permite ao seu detentor a respiração eterna saudável imaculada garantindo-lhe nunca ser asfixiado submerso, imune perfeitamente no gás venenoso planar e ambientes vazios.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'necklace-of-fireballs',
    name: 'Colar de Bolas de Fogo',
    englishName: 'Necklace of Fireballs',
    type: 'Item Mágico (Colar)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Contém 1d6 + 3 pérolas. Você pode sacar (como Ação) e detonar magias ardentes idênticas a Explosão de Bola de Fogo de Nível 3. Arrancar pérolas juntas somam o nível cast total (DC 15 de Destreza da gema avermelhada).',
    value: '3.000 PO',
    weight: 1,
  },
  {
    id: 'pearl-of-power',
    name: 'Pérola do Poder',
    englishName: 'Pearl of Power',
    type: 'Item Mágico (Gema)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização por um Conjurador',
    description: 'Com sua Ação o conjurador puxa a ressonância desta pérola recuperando pra ele um Slot de Magia (Spell Slot) idêntico gasto até no máximo Nível 3 (Magia Arcana ou Divina).',
    value: '800 PO',
    weight: 0,
  },
  {
    id: 'periapt-of-health',
    name: 'Periápito da Saúde',
    englishName: 'Periapt of Health',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'O utente ganha imunidade contínua a qualquer forma de doença grave, as doenças em seu corpo congelam caso coloque esse objeto divino enquanto repousa adoentado.',
    value: '400 PO',
    weight: 1,
  },
  {
    id: 'periapt-of-proof-against-poison',
    name: 'Periápito de Prova contra Veneno',
    englishName: 'Periapt of Proof against Poison',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'A joia protege você, impedindo ativamente que adquira Condições nefastas perigosas fixadas por (Envenenado). Confere a Imunidade de dano e reações envenenadas letais.',
    value: '4.000 PO',
    weight: 1,
  },
  {
    id: 'periapt-of-wound-closure',
    name: 'Periápito de Fechar Feridas',
    englishName: 'Periapt of Wound Closure',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Estabiliza a criatura morta imaculadamente: em zero Vida você vira estável no início do turno de dados da morte. Ao rolar Dados de Vida durante Descansos, recupera os Hit Points maximizados / duplicados nos dados extras das pancadas perdidas passadas.',
    value: '800 PO',
    weight: 1,
  },
  {
    id: 'quivers-of-ehlonna',
    name: 'Aljava de Ehlonna',
    englishName: 'Quiver of Ehlonna',
    type: 'Item Mágico (Aljava)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Possui 3 compartimentos extensos dimensionais que estocam: 1º (60 flechas e munições). 2º (Dezenas de azagaias e dardos menores - 18 itens). 3º (Cabem hastes/lanças e arcos compridos até o total de 6 objetos gigantes). Pesa levíssima 1 Kg no máximo.',
    value: '600 PO',
    weight: 2,
  },
  {
    id: 'slippers-of-spider-climbing',
    name: 'Sapatilhas de Escalar de Aranha',
    englishName: 'Slippers of Spider Climbing',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Proporcionam passos grudados em quaisquer superfícies teto/paredes e tetos verticais, invertidos ou de cabeça pra baixo. Liberando suas mãos seguras sem perder o bônus na caminhada.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'sphere-of-annihilation',
    name: 'Esfera da Aniquilação',
    englishName: 'Sphere of Annihilation',
    type: 'Item Mágico (Artefato)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: false,
    description: 'Um buraco vácuo esférico (60cm) paralisado; Nada sobrevive sem levar dano ao tocá-la (4d10 Força cósmica). Mágicos precisam de alto valor e foco cognitivo Arcano absoluto DC para tentar arrastar/movê-la, se não apagam/sugam a si na entropia planar dimensional escura da falha contínua.',
    value: '90.000 PO',
    weight: 0,
  }
];
