import { SRDSpell } from './types';

export const BATCH_6_SPELLS: SRDSpell[] = [
  {
    id: 'aid',
    name: 'Auxílio (Aid)',
    englishName: 'Aid',
    level: 2,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma tira de pano branco', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 3 criaturas' },
    damageSave: { attackType: 'utility' },
    description: 'Sua magia fortalece os aliados com tenacidade e determinação. Escolha até três criaturas no alcance. O máximo de pontos de vida e os pontos de vida atuais de cada alvo aumentam em 5 pela duração.',
    classes: ['Clérigo', 'Paladino']
  },
  {
    id: 'animal-friendship',
    name: 'Amizade Animal (Animal Friendship)',
    englishName: 'Animal Friendship',
    level: 1,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um bocado de comida', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Fera' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Esta magia permite que você convença uma besta que você não quer prejudicá-la. Escolha uma besta que você possa ver dentro do alcance. Ela deve ver e ouvir você. Se a Inteligência dela for 4 ou maior, a magia falha. Senão, a besta deve ser bem sucedida num TR de Sabedoria ou ficará enfeitiçada por você pela duração.',
    classes: ['Bardo', 'Druida', 'Patrulheiro']
  },
  {
    id: 'animal-messenger',
    name: 'Mensageiro Animal (Animal Messenger)',
    englishName: 'Animal Messenger',
    level: 2,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: '24 horas',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um pedaço de comida', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Fera' },
    damageSave: { attackType: 'utility' },
    description: 'Você usa uma Besta minúscula como mensageiro. Você especifica um local e um destinatário genérico, e a besta viaja até lá voando (75km/dia) ou andando (35km/dia) e entrega sua mensagem sussurrada.',
    classes: ['Bardo', 'Druida', 'Patrulheiro']
  },
  {
    id: 'animal-shapes',
    name: 'Formas Animais (Animal Shapes)',
    englishName: 'Animal Shapes',
    level: 8,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 24 horas',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 9, sizeUnit: 'm', formatted: 'Criaturas voluntárias em 9m' },
    damageSave: { attackType: 'utility' },
    description: 'Você transforma qualquer número de criaturas voluntárias num raio de 9 metros. Você escolhe uma Besta de ND 4 ou menor. Todos os alvos assumem essa mesma forma. Como uma ação em turnos seguintes, você pode mudar a forma de todos.',
    classes: ['Druida']
  },
  {
    id: 'antilife-shell',
    name: 'Cúpula Antivida (Antilife Shell)',
    englishName: 'Antilife Shell',
    level: 5,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Pessoal (raio de 3m)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 3, sizeUnit: 'm', formatted: 'Esfera (Raio 3m)' },
    damageSave: { attackType: 'utility' },
    description: 'Uma barreira cintilante impede a entrada de seres vivos não mortos-vivos ou constructos. A barreira se move com você. Se você forçar a barreira contra uma criatura, a magia se desfaz.',
    classes: ['Druida']
  },
  {
    id: 'antipathysympathy',
    name: 'Antipatia/Simpatia (Antipathy/Sympathy)',
    englishName: 'Antipathy/Sympathy',
    level: 8,
    school: 'Encantamento',
    castingTime: '1 hora',
    range: '18 metros (60 pés)',
    duration: '10 dias',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'alumínio para antipatia ou mel para simpatia', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: 'Objeto ou Criatura' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Alvo se torna um ímã ou repelente extremo. Escolha um tipo de criatura inteligente. Se Antipatia: o tipo repele a se aproximar a menos de 18m (Frightened TR Sabedoria). Se Simpatia: atrai obsessivamente (Charm TR Sabedoria).',
    classes: ['Druida', 'Mago']
  },
  {
    id: 'arcane-lock',
    name: 'Tranca Arcana (Arcane Lock)',
    englishName: 'Arcane Lock',
    level: 2,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até dissipada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'pó de ouro de 25 PO consumido', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Porta/Baú' },
    damageSave: { attackType: 'utility' },
    description: 'Tranca magicamente uma porta, baú ou janela. Você e aliados designados abrem livremente. Aumenta a CD para arrombar a força ou destrancar (ferramentas) em 10.',
    classes: ['Mago']
  },
  {
    id: 'augury',
    name: 'Augúrio (Augury)',
    englishName: 'Augury',
    level: 2,
    school: 'Adivinhação',
    castingTime: '1 minuto',
    range: 'Pessoal',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'varetas divinatórias ou ossos gravados de 25 PO', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Prevê os resultados das suas ações na próxima meia hora (Bomba/Ruim/Ambos/Nenhum). Se conjurar de novo antes do descanso longo há 25% chance de resposta aleatória.',
    classes: ['Clérigo']
  },
  {
    id: 'bane',
    name: 'Perdição (Bane)',
    englishName: 'Bane',
    level: 1,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma gota de sangue', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 3 criaturas' },
    damageSave: { saveStat: 'CHA', saveEffect: 'negate', attackType: 'save' },
    description: 'Amaldiçoa três alvos num alcance de 9m que falharem no TR Carisma. Sempre que o alvo fizer uma rolagem de ataque ou teste de resistência antes do fim da magia, ele subtrai 1d4 do resultado.',
    classes: ['Bardo', 'Clérigo']
  },
  {
    id: 'barkskin',
    name: 'Pele de Árvore (Barkskin)',
    englishName: 'Barkskin',
    level: 2,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um punhado de casca de carvalho', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Você toca uma criatura. Até o feitiço acabar, a pele da criatura tem a textura áspera da casca de uma árvore, e a CA dela não pode ser menor que 16, independente de qual tipo de armadura esteja usando.',
    classes: ['Druida', 'Patrulheiro']
  },
  {
    id: 'bestow-curse',
    name: 'Rogar Maldição (Bestow Curse)',
    englishName: 'Bestow Curse',
    level: 3,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Amaldiçoa uma criatura. Escolha o efeito: Desvantagem em testes de 1 habilidade, desvantagem contra seus ataques, ou gastar a ação rodando Sabedoria para não fazer nada no turno, ou seus ataques causam +1d8 necrótico extra a ela.',
    classes: ['Bardo', 'Clérigo', 'Mago']
  },
  {
    id: 'blight',
    name: 'Secar (Blight)',
    englishName: 'Blight',
    level: 4,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura (viva/planta)' },
    damageSave: { damageDice: '8d8', damageType: 'Necrótico', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Magia necromântica suga a umidade da vítima. Plantas sofrem desvantagem no TR e dano máximo automático (64). Criaturas tomam 8d8 Necrótico no TR de Constituição. Mortos vivos e Construtos são imunes.',
    classes: ['Druida', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'branding-smite',
    name: 'Destruição Marcante (Branding Smite)',
    englishName: 'Branding Smite',
    level: 2,
    school: 'Evocação',
    castingTime: '1 ação bônus',
    range: 'Pessoal',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { damageDice: '2d6', damageType: 'Radiante', attackType: 'utility' },
    description: 'Sua próxima arma corpo a corpo acerta com chamas astrais. Causa 2d6 Radiante extra. O alvo brilha (lança luz) e não pode se tornar invisível até a magia terminar.',
    classes: ['Paladino']
  },
  {
    id: 'calm-emotions',
    name: 'Acalmar Emoções (Calm Emotions)',
    englishName: 'Calm Emotions',
    level: 2,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 6, sizeUnit: 'm', formatted: 'Esfera de 6m Raio' },
    damageSave: { saveStat: 'CHA', saveEffect: 'negate', attackType: 'save' },
    description: 'Você suprime emoções em área TR Carisma. Escolha entre: Suprimir efeito de Enfeitiçado (Charm) ou Amedrontado (Frightened), OU tornar um inimigo indiferente e não violento perante os combates enquanto não os machucarem.',
    classes: ['Bardo', 'Clérigo']
  },
  {
    id: 'charm-person',
    name: 'Enfeitiçar Pessoa (Charm Person)',
    englishName: 'Charm Person',
    level: 1,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Humanóide' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Humanóide tenta um TR de Sabedoria (com Vantagem se estiverem em combate). Se falhar, fica Enfeitiçado por você, considerando-o um amigo confiável. Quebra se o grupo o ferir. Ele sabe que foi encantado quando termina.',
    classes: ['Bardo', 'Druida', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'circle-of-death',
    name: 'Círculo da Morte (Circle of Death)',
    englishName: 'Circle of Death',
    level: 6,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: '45 metros (150 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'pérola negra de 500 PO esmagada (consumida)', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 18, sizeUnit: 'm', formatted: 'Esfera imensa (Raio 18m)' },
    damageSave: { damageDice: '8d6', damageType: 'Necrótico', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Energia negativa devasta os vivos em 18m. Todos rolam TR Constituição e recebem 8d6 Dano Necrótico.',
    classes: ['Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'color-spray',
    name: 'Leque Cromático (Color Spray)',
    englishName: 'Color Spray',
    level: 1,
    school: 'Ilusão',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'areia tingida', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cone', sizeValue: 4.5, sizeUnit: 'm', formatted: 'Cone de 4.5m (15 pés)' },
    damageSave: { attackType: 'utility' },
    description: 'Ofusca luz colorida. Você rola 6d10 (esse é o pool de PVs cegados). Somando os pontos de vida dos alvos em cone (do menor HP pro maior HP atual), cega todas criaturas que a soma abranja, até seu próximo turno sem resistência possível.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'commune-with-nature',
    name: 'Comunhão com a Natureza (Commune With Nature)',
    englishName: 'Commune With Nature',
    level: 5,
    school: 'Adivinhação',
    castingTime: '1 minuto',
    range: 'Pessoal',
    duration: 'Instantânea',
    concentration: false,
    ritual: true,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 4500, sizeUnit: 'm', formatted: 'Raio de 3 Milhas (ao ar livre)' },
    damageSave: { attackType: 'utility' },
    description: 'Você se torna uno à geografia externa numa área de até 5 km de raio ao ar livre. Você aprende fatos gerais (Três fatos: presença mortos vivos, prédios, minerais, fadas ou perigos iminentes na mata).',
    classes: ['Druida', 'Patrulheiro']
  },
  {
    id: 'compulsion',
    name: 'Compulsão (Compulsion)',
    englishName: 'Compulsion',
    level: 4,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Criaturas à escolha em 9m' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Criaturas que você ver no alcance rolam TR Sabedoria. Se falharem, você determina uma direção usando Ação Bônus e todas usarão todo o Deslocamento no próprio turno delas para se mover naquela exata direção.',
    classes: ['Bardo']
  },
  {
    id: 'conjure-animals',
    name: 'Conjurar Animais (Conjure Animals)',
    englishName: 'Conjure Animals',
    level: 3,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Bestas fadas (1 a 8 criaturas)' },
    damageSave: { attackType: 'utility' },
    description: 'Você invoca espíritos de bestas feéricos. Opções: 1 Fera (ND 2), 2 Feras (ND 1), 4 Feras (ND 1/2) ou 8 Feras (ND 1/4). Agem passivamente por você, mas obedecem comandos de combate perfeitamente. DM fornece a lista de opções de animais conjurados baseados na região.',
    classes: ['Druida', 'Patrulheiro']
  },
  {
    id: 'conjure-fey',
    name: 'Conjurar Fada (Conjure Fey)',
    englishName: 'Conjure Fey',
    level: 6,
    school: 'Conjuração',
    castingTime: '1 minuto',
    range: '27 metros (90 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Fada ND 6 ou menor' },
    damageSave: { attackType: 'utility' },
    description: 'Evoca Fada forte de ND 6 aliada a seus comandos. Se concentração quebrar o feérico fica 100% Hostil e te ataca pra vingança da servidão! ',
    classes: ['Druida', 'Bruxo']
  },
  {
    id: 'contingency',
    name: 'Contingência (Contingency)',
    englishName: 'Contingency',
    level: 6,
    school: 'Evocação',
    castingTime: '10 minutos',
    range: 'Pessoal',
    duration: '10 dias',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'estatueta luxuosa de si mesmo 1500 PO', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Armazena 1 Magia GATILHO em você mesmo (Até magia nível 5). Você define a condição exata (Ex: "Ativar Pele de Pedra quando me baterem"). Quando ocorrer, ela lança instantânea sem uso de reação ou tempo!',
    classes: ['Mago']
  },
  {
    id: 'create-food-and-water',
    name: 'Criar Comida e Água (Create Food and Water)',
    englishName: 'Create Food and Water',
    level: 3,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 1.5, sizeUnit: 'm', formatted: 'Rações para 15 seres' },
    damageSave: { attackType: 'utility' },
    description: 'Você manifesta 20 kg de comida comestível razoável e 110 L dágua fresca pura para um pelotão de 15 homens ou 5 cavalos alimentados pelo dia todo. Some estragando se não for comida em 24h.',
    classes: ['Clérigo', 'Paladino']
  },
  {
    id: 'create-or-destroy-water',
    name: 'Criar ou Destruir Água (Create or Destroy Water)',
    englishName: 'Create or Destroy Water',
    level: 1,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'gota de água', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'cube', sizeValue: 9, sizeUnit: 'm', formatted: 'Cubo de 9m / Recipiente' },
    damageSave: { attackType: 'utility' },
    description: 'CRIA 38L dágua num recipiente aberto (ou chove no cubo de 9m apagando fogos pequenos). DESTRÓI a mesma quantia (ou acaba névoa num cubo).',
    classes: ['Clérigo', 'Druida']
  },
  {
    id: 'create-undead',
    name: 'Criar Mortos-Vivos (Create Undead)',
    englishName: 'Create Undead',
    level: 6,
    school: 'Necromancia',
    castingTime: '1 minuto',
    range: '3 metros (10 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'potes de terra argila tumular / 1 ônix preta para CADA zumbi por corpo', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 3 Carniçais Iniciais' },
    damageSave: { attackType: 'utility' },
    description: 'Você deve castar somente À NOITE! Escolhe até três cadáveres. Transforma todos em Carniçais (Ghouls)! Estão sob sua patente absoluta nas proximas 24hr. Para manter as rédeas de novo no dia seguinte precisa gastar essa magia só p/ dominar antes do tempo acabar!',
    classes: ['Clérigo', 'Bruxo', 'Mago']
  }
];
