import { SRDItem } from './types';

export const BATCH_12_GENERIC_GEAR: SRDItem[] = [
  // Armaduras e Escudos Genéricos
  {
    id: 'armor-1',
    name: 'Armadura +1',
    englishName: 'Armor, +1',
    type: 'Item Mágico (Qualquer Armadura)',
    category: 'Armadura',
    rarity: 'Rara',
    attunement: false,
    description: 'Uma armadura habilmente construída imbuída com magias defletoras que se mantém afiadas protetoras. Você recebe fixo +1 absoluto e contínuo contábil global no seu valor total final passivo da CA da proteção base desta armadura especial. (Pode ser uma de Couro batido, cota de malha, placa pesada brilhante, etc).',
    value: '1.500 PO',
    weight: 0,
  },
  {
    id: 'armor-2',
    name: 'Armadura +2',
    englishName: 'Armor, +2',
    type: 'Item Mágico (Qualquer Armadura)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Extremamente formidável forja anã arcana ou artífice lendário pura magia fixa vitalícia protetora, conferindo contínuo passivamente total somatório bônus de absoluto +2 AC puro na armadura base desta exata armadura no final das contas defletoras do portador.',
    value: '6.000 PO',
    weight: 0,
  },
  {
    id: 'armor-3',
    name: 'Armadura +3',
    englishName: 'Armor, +3',
    type: 'Item Mágico (Qualquer Armadura)',
    category: 'Armadura',
    rarity: 'Lendária',
    attunement: false,
    description: 'Um escudo da malha divina de puro mithral supremo forjado nas divindades protetoras eternas sem uso do tempo envelhecido quebrando ferro natural. Esta poderosa malha confere absolutos totais defensivos esmagadores contínuos somatórios impenetráveis mágicos inatos de puro +3 mágico (AC Bônus da armadura) permanente passiva.',
    value: '25.000 PO',
    weight: 0,
  },
  {
    id: 'shield-of-missile-attraction',
    name: 'Escudo de Atração de Projéteis',
    englishName: 'Shield of Missile Attraction',
    type: 'Item Mágico (Escudo)',
    category: 'Armadura',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Este escudo é excelente, embora Amaldiçoado na essência imã caótica mágica sombria. Você ganha de forma irrestrita Resistência Divina Absoluta total e fixa em relação (Danos esmagadores diretos contra flechas de combates de longo alcance variados letais e projéteis da vida). Porém a maldição suga: sempre que estiverem mirando 3m próximo do dono nele, ele desvia atraindo o letal projétil mágico pro escudeiro absorver ativamente ou ricochetear pro escudo fatal mágico absoluto letal da área.',
    value: '6.000 PO',
    weight: 6,
  },
  {
    id: 'spellguard-shield',
    name: 'Escudo Guarda-Magias',
    englishName: 'Spellguard Shield',
    type: 'Item Mágico (Escudo)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Escudo anti-magia abjurador gravado de runas blindadas letais anuladoras mágicas absolutas de reflexão celestiais fixas de prata cósmica, que lhe confere Vantagens mágicas imediatas protetivas ativas contínuas absolutas no momento exato em Rolagens contra todos os puros Salvamentos Ativos contra (Feitiços em geral ou efeitos diretos sobrenaturais iminentes celestes cruéis totais mortais visando os portadores letais da luz), e além disto causa inimigos sempre errar Desvantagens em rolamentos ativos para atacar portadores mágicos em geral absolutos na vida.',
    value: '15.000 PO',
    weight: 6,
  },
  // Armas Genéricas e Munições
  {
    id: 'weapon-1',
    name: 'Arma +1',
    englishName: 'Weapon, +1',
    type: 'Item Mágico (Qualquer Arma)',
    category: 'Arma',
    rarity: 'Incomum',
    attunement: false,
    description: 'Borda prateada afiada perfeita forjada nas bigornas celestes (qualquer espada de corte pesada letal rápida mágica). Confere aos punhos um letal e fixo inabalável de Vantagem extra nos atributos acertos de jogadas (Ataques) puros inatos diretos + bônus e rolagens definitivos letais +1 (Danos puros absolutos da sorte contínuos e mágicos letais de base extra bônus fixos contábeis globais final).',
    value: '500 PO',
    weight: 0,
  },
  {
    id: 'weapon-2',
    name: 'Arma +2',
    englishName: 'Weapon, +2',
    type: 'Item Mágico (Qualquer Arma)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: false,
    description: 'Confere Vantagem exata fixa bônus de acertos contínuos passivos mágicos fatais (+2 exatos inquebráveis definitivos passivos puros diretos absolutos mágicos fixados puros da sorte) Ataque + Danos vitais bônus mágicos globais da espada fina (Garante dano Mágico imune).',
    value: '4.000 PO',
    weight: 0,
  },
  {
    id: 'weapon-3',
    name: 'Arma +3',
    englishName: 'Weapon, +3',
    type: 'Item Mágico (Qualquer Arma)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'As famosas lâminas cortantes dos elfos da morte blindados do rei supremo, a magia superior celestial letal absoluta passiva desta peça de joia de ferreiro lhe confere (+3 mágico exato fixo em Rolagens absolutas de precisão base dos Acertos cruéis) + (+3 exatos globais letais passivos de Bônus da tabela do Dano contínuo impiedoso letal nobre na base fixa absoluta passiva extraída).',
    value: '15.000 PO',
    weight: 0,
  },
  {
    id: 'ammunition-1',
    name: 'Munição +1',
    englishName: 'Ammunition, +1',
    type: 'Item Mágico (Qualquer Munição)',
    category: 'Arma',
    rarity: 'Incomum',
    attunement: false,
    description: 'Cada flecha destas (vendida geralmente aos blocos encapados ou ponta runa simples de fogo/prata) garantem bônus inato ativo somado absoluto +1 letal puro nas rolagens vitais (Acerto passivos e Dano base mágicos contínuos fixos imbuído das forças cruéis vitais da sorte global ativadora) no choque destruído em combate.',
    value: '10 PO',
    weight: 0,
  },
  {
    id: 'ammunition-2',
    name: 'Munição +2',
    englishName: 'Ammunition, +2',
    type: 'Item Mágico (Qualquer Munição)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: false,
    description: 'Flechas runadas perfurantes fatais absolutas. Fornecem bônus de magia +2 acerto de rolamento no disparo somatório final e +2 danos mágicos letais bônus irrestritos.',
    value: '50 PO',
    weight: 0,
  },
  {
    id: 'ammunition-3',
    name: 'Munição +3',
    englishName: 'Ammunition, +3',
    type: 'Item Mágico (Qualquer Munição)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Garante absolutos formidáveis imbatíveis totais e letais passivos destrutivos vitais de pura magia celestial inata +3 Acerto exato divino de força vital contínua global base +3 de Dano bônus divino no alvo rasgado celestial fixo da vida na rolagem antes das magias sumirem gastas de uso.',
    value: '250 PO',
    weight: 0,
  }
];
