import { SRDSpell } from './types';

export const BATCH_8_SPELLS: SRDSpell[] = [
  {
    id: 'freezing-sphere',
    name: 'Esfera Congelante (Freezing Sphere)',
    englishName: "Otiluke's Freezing Sphere",
    level: 6,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '90 metros (300 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma bolinha de cristal', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 18, sizeUnit: 'm', formatted: 'Esfera de 18m de Raio' },
    damageSave: { damageDice: '10d6', damageType: 'Frio', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Explosão glacial extrema (TR Constituição) causa 10d6 de dano de Frio. A água no alcance congela em chão sólido firme se não houver criaturas ali. Você também pode guardar a bola pequena por 1 minuto antes de arremessá-la qual granada de estilingue!',
    classes: ['Mago']
  },
  {
    id: 'giant-insect',
    name: 'Inseto Gigante (Giant Insect)',
    englishName: 'Giant Insect',
    level: 4,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Insetos (10 centopeias, 3 aranhas, 5 vespas ou 1 escorpião)' },
    damageSave: { attackType: 'utility' },
    description: 'Transforma insetos mundanos rústicos do chão no bando monstro gigante equivalente. Comandos verbais livres do conjurador para os gigantes atuarem lutando até morrerem na mesma proporção.',
    classes: ['Druida']
  },
  {
    id: 'glibness',
    name: 'Loquacidade (Glibness)',
    englishName: 'Glibness',
    level: 8,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: '1 hora',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Magia que te deixa num encantamento vocal mestre. Toda vez que rolar TESTE DE CARISMA você pode transformar qualquer resultado do D20 no DADO como número 15. E feitiços que deduzem verdades mentais nunca revelam o que você omite.',
    classes: ['Bardo']
  },
  {
    id: 'goodberry',
    name: 'Bom Fruto (Goodberry)',
    englishName: 'Goodberry',
    level: 1,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'ramo visco', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 10 Frutas mágicas criadas' },
    damageSave: { damageDice: '1', damageType: 'Cura', attackType: 'utility' },
    description: 'Surge na sua mão até dez bagas frescas frutíferas suculentas imbuídas com energia da natureza. Qualquer criatura come uma na sua Ação pra se curar exatamente 1 Ponto de Vida, e fornece toda provisão alimento prum humano de um dia!',
    classes: ['Druida', 'Patrulheiro']
  },
  {
    id: 'guiding-bolt',
    name: 'Raio Guia (Guiding Bolt)',
    englishName: 'Guiding Bolt',
    level: 1,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '36 metros (120 pés)',
    duration: '1 rodada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '4d6', damageType: 'Radiante', attackType: 'ranged_spell' },
    description: 'Feixe de luz atinge inimigo sagrado. Ataque Corpo a Corpo Mágico acerta: Dano letal inicial radiante massivo 4d6 de pura luz! Após isso até seu próximo turno um aliado seu possuirá VANTAGEM no 1º ataque rolado nesse alvo brilhoso focado.',
    classes: ['Clérigo']
  },
  {
    id: 'hallow',
    name: 'Consagrar (Hallow)',
    englishName: 'Hallow',
    level: 5,
    school: 'Evocação',
    castingTime: '24 horas',
    range: 'Toque',
    duration: 'Até dissipada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'ervas erva doce óleos sagrados de no mínimo 1.000 PO consumidos', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 18, sizeUnit: 'm', formatted: 'Esfera (Raio 18m)' },
    damageSave: { attackType: 'utility' },
    description: 'Consagra / Profana 1 área de forma definitiva. Efeitos: Celestes Infernais não entram nela ou enfeitiçam os que estão protegidos lá dentro, E ACRESCENTA UM EFEITO MÁGICO PERMANENTE EXTRA TIPO CORAGEM, LINGUAGEM LUZ LUZ DO DIA SOMBRAS ETC que você seleciona ativamente. Pode proteger fortalezas inteiras de raças sombrias invasoras.',
    classes: ['Clérigo']
  },
  {
    id: 'heroes-feast',
    name: 'Banquete dos Heróis (Heroes\' Feast)',
    englishName: "Heroes' Feast",
    level: 6,
    school: 'Conjuração',
    castingTime: '10 minutos',
    range: '9 metros (30 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'taça sagrada divina ornada preciosa valorizada 1.000 PO consumida', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'multiple_targets', formatted: 'Até 12 pessoas (Consumidores)' },
    damageSave: { attackType: 'utility' },
    description: 'Sumona baquete banqueteiro épico esplendoroso que curar todos problemas do grupo (Removendo venenos medos). Todos ganham bônus permanentes pro dia (Vantagem TR Sabedoria), (Imune à medos envenenamento), E MÁXIMO DE PV MÁXIMO SÃO AUMENTADOS e atuais por fortes brutos +2d10 pelo dia longo inteiro!',
    classes: ['Clérigo', 'Druida']
  },
  {
    id: 'heroism',
    name: 'Heroísmo (Heroism)',
    englishName: 'Heroism',
    level: 1,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Toca ombros aliado e ele é infundido a se opor: Ele torna-se imune ao medo (Frightened), e no começo DE CADA UM DE SEUS TURNOS NO COMBATE recebe PV Temporários igual seu MODIFICADOR MAGIA que atuam como mitigação natural reciclável.',
    classes: ['Bardo', 'Paladino']
  },
  {
    id: 'hideous-laughter',
    name: 'Riso Histérico (Hideous Laughter)',
    englishName: "Tasha's Hideous Laughter",
    level: 1,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'penas finas pontiagudas, tortas voadoras minúsculas engraçadas pó', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Uma criatura com Inteligência maior que 4 rola TR Sabedoria. Ao falhar, cai na risada brutal se contorcendo ao chão caindo Caído (Prone) e incapacitado total de agir por não conseguir focar! Repete no fim do turno dela (Com Vantagem toda vez que você ou aliado nela dar Dano no coitado no chão rindo).',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'holy-aura',
    name: 'Aura Sagrada (Holy Aura)',
    englishName: 'Holy Aura',
    level: 8,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'pêlo minúsculo prateado cristal 1.000 PO cravado', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 9, sizeUnit: 'm', formatted: 'Aura radiante (Raio 9m)' },
    damageSave: { attackType: 'utility' },
    description: 'Emanas uma luz divina (9m) protegendo os seus do diabo. (VOCÊS e até ali ganham Vantagem TODOS OS Testes Resistências)!! e todos monstros Inimigos atacando vocês na Aura tomam automática Desvantagem nisto! Sem falar q mortos/infernais tentando acertar vcs cegam-se no processo! Magia de Buff Supremo End Game.',
    classes: ['Clérigo']
  },
  {
    id: 'hunters-mark',
    name: 'Marca do Caçador (Hunter\'s Mark)',
    englishName: "Hunter's Mark",
    level: 1,
    school: 'Adivinhação',
    castingTime: '1 ação bônus',
    range: '27 metros (90 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { damageDice: '1d6', damageType: 'Arma', attackType: 'utility' },
    description: 'Sua preza de emboscada. Vc mira magia alvo: TODOS os ataques base SEUS neste alvo dão MAIS +1D6 Extra no final. Além de te dar Vantagens nos rastreamentos/sobrevivência/percepção de rastreá-lo no escuro longo. Pode mover pra novo se original for Morto.',
    classes: ['Patrulheiro']
  },
  {
    id: 'inflict-wounds',
    name: 'Infligir Ferimentos (Inflict Wounds)',
    englishName: 'Inflict Wounds',
    level: 1,
    school: 'Necromancia',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { damageDice: '3d10', damageType: 'Necrótico', attackType: 'melee_spell' },
    description: 'Ao focar energias caóticas da escuridão pro sacerdote bater no peito: Ataque mágico em alvo, Se acerta leva danos pesados letais nível 1: 3d10 de Dano Necrótico direto massivo.',
    classes: ['Clérigo']
  },
  {
    id: 'insect-plague',
    name: 'Praga de Insetos (Insect Plague)',
    englishName: 'Insect Plague',
    level: 5,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '90 metros (300 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pó, areia açúcar sujo', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 6, sizeUnit: 'm', formatted: 'Esfera (Raio 6m)' },
    damageSave: { damageDice: '4d10', damageType: 'Perfurante', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Besouros abelhas mosquitos enchem as vistas! (Área obscurecimento pesado visão, vira terreno difícil pra pisar). Começou no turno de lá toma Picada maciça: TR Const e 4d10 de Danos Perfurantes insetos mortais (metade passou).',
    classes: ['Clérigo', 'Druida', 'Feiticeiro']
  },
  {
    id: 'irresistible-dance',
    name: 'Dança Irresistível (Irresistible Dance)',
    englishName: "Otto's Irresistible Dance",
    level: 6,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'Faz um bicho começar um solo violento de Break-Dance cômico de imediato obrigatório que ele queira ou NÃO (Dura na Marra no primeiro turno sem teste antes!). Ela gasta movimentos, recebe DEsvantagem Dex no reflexo / atacando. Para se libertar após isso deve passar uma AÇÃO rolagem Inteira no teste TR de Sabedoria pra pausar a valsa forçada.',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'legend-lore',
    name: 'Lendas e Histórias (Legend Lore)',
    englishName: 'Legend Lore',
    level: 5,
    school: 'Adivinhação',
    castingTime: '10 minutos',
    range: 'Pessoal',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'bastões marfim chifres gravados de po 250 ouro (consumidos em cada consulta ao Além)', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Cite ou toque objeto lugar e ou pessoa DE RENOME EXTREMO/Lendário na crônica. Trará à sua mente todo conto escondido perdido rima lenda lore a respeito do nome misterioso (Exemplo como destruir o colar único misterioso anão da lenda tal)!',
    classes: ['Bardo', 'Clérigo', 'Mago']
  }
];
