import { SRDItem } from './types';
import { BATCH_2_RINGS } from './srd-items-batch-2';
import { BATCH_3_WANDS_STAVES_RODS } from './srd-items-batch-3';
import { BATCH_4_WEAPONS } from './srd-items-batch-4';
import { BATCH_5_ARMORS } from './srd-items-batch-5';
import { BATCH_6_WONDROUS_A_I } from './srd-items-batch-6';
import { BATCH_7_WONDROUS_J_Z } from './srd-items-batch-7';
import { BATCH_8_POTIONS_SCROLLS } from './srd-items-batch-8';
import { BATCH_9_WEARABLES } from './srd-items-batch-9';
import { BATCH_10_COLLECTIONS } from './srd-items-batch-10';
import { BATCH_11_WONDROUS } from './srd-items-batch-11';
import { BATCH_12_GENERIC_GEAR } from './srd-items-batch-12';
import { BATCH_13_VARIANTS } from './srd-items-batch-13-variants';
import { BATCH_14_UNIQUES } from './srd-items-batch-14-uniques';

export const BATCH_1_ITEMS: SRDItem[] = [
  // ==========================================
  // POÇÕES & CONSUMÍVEIS (POTIONS & CONSUMABLES)
  // ==========================================
  {
    id: 'potion-of-healing-common',
    name: 'Poção de Cura',
    englishName: 'Potion of Healing',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Comum',
    attunement: false,
    description: 'Você recupera 2d4 + 2 pontos de vida ao beber esta poção de líquido vermelho brilhante que borbulha suavemente.',
    value: '50 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-healing-greater',
    name: 'Poção de Cura Maior',
    englishName: 'Potion of Healing (Greater)',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Você recupera 4d4 + 4 pontos de vida ao beber esta poção vermelha translúcida.',
    value: '150 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-healing-superior',
    name: 'Poção de Cura Superior',
    englishName: 'Potion of Healing (Superior)',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Rara',
    attunement: false,
    description: 'Você recupera 8d4 + 8 pontos de vida ao beber esta poção brilhante e cintilante.',
    value: '450 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-healing-supreme',
    name: 'Poção de Cura Suprema',
    englishName: 'Potion of Healing (Supreme)',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Você recupera 10d4 + 20 pontos de vida ao beber esta poção incandescente.',
    value: '1.350 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-climbing',
    name: 'Poção de Escalada',
    englishName: 'Potion of Climbing',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Comum',
    attunement: false,
    description: 'Por 1 hora ao beber esta poção, você ganha deslocamento de escalada igual ao seu deslocamento de caminhada e tem vantagem em testes de Força (Atletismo) para escalar.',
    value: '50 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-invisibility',
    name: 'Poção de Invisibilidade',
    englishName: 'Potion of Invisibility',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Ao beber esta poção, você fica invisível por 1 hora. O efeito termina antecipadamente se você atacar ou conjurar uma magia.',
    value: '500 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-speed',
    name: 'Poção de Velocidade',
    englishName: 'Potion of Speed',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Ao beber esta poção, você ganha o efeito da magia Velocidade (Haste) por 1 minuto (sem necessidade de concentração).',
    value: '400 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-water-breathing',
    name: 'Poção de Respirar na Água',
    englishName: 'Potion of Water Breathing',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Ao beber esta poção, você pode respirar sob a água por 1 hora.',
    value: '100 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-heroism',
    name: 'Poção de Heroísmo',
    englishName: 'Potion of Heroism',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Rara',
    attunement: false,
    description: 'Ao beber esta poção azul borbulhante, você ganha 10 pontos de vida temporários que duram por 1 hora. Durante esse tempo, você está sob o efeito da magia Benção (Bless).',
    value: '180 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-growth',
    name: 'Poção de Crescimento',
    englishName: 'Potion of Growth',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Ao beber esta poção, você ganha o efeito de crescimento da magia Aumentar/Reduzir por 1d4 horas.',
    value: '150 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-diminution',
    name: 'Poção de Diminuição',
    englishName: 'Potion of Diminution',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Rara',
    attunement: false,
    description: 'Ao beber esta poção, você diminui de tamanho conforme o efeito de redução da magia Aumentar/Reduzir por 1d4 horas.',
    value: '250 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-resistance',
    name: 'Poção de Resistência',
    englishName: 'Potion of Resistance',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Ao beber esta poção, você ganha resistência a um tipo de dano específico (Ácido, Concusão, Fogo, Frio, Eletricidade, Necrótico, Veneno, Psíquico, Radiante ou Trovão) por 1 hora.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-giant-strength-hill',
    name: 'Poção de Força do Gigante da Colina',
    englishName: 'Potion of Hill Giant Strength',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Ao beber esta poção, seu valor de Força torna-se 21 por 1 hora. Se sua Força já for igual ou maior, a poção não tem efeito.',
    value: '200 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-giant-strength-fire',
    name: 'Poção de Força do Gigante do Fogo',
    englishName: 'Potion of Fire Giant Strength',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Rara',
    attunement: false,
    description: 'Ao beber esta poção, seu valor de Força torna-se 25 por 1 hora.',
    value: '500 PO',
    weight: 0.5,
  },
  {
    id: 'elixir-of-health',
    name: 'Elixir de Saúde',
    englishName: 'Elixir of Health',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Rara',
    attunement: false,
    description: 'Ao beber este elixir transparente com detalhes dourados, você cura qualquer doença que o afete e remove as condições Cego, Surdo, Paralisado e Envenenado.',
    value: '350 PO',
    weight: 0.5,
  },
  {
    id: 'oil-of-sharpness',
    name: 'Óleo de Afiação',
    englishName: 'Oil of Sharpness',
    type: 'Poção Mágica (Óleo)',
    category: 'Poção',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Este óleo pode cobrir uma arma cortante ou perfurante ou até 5 munições. A aplicação leva 1 minuto. Por 1 hora, a arma ganha +3 de bônus nas jogadas de ataque e dano.',
    value: '600 PO',
    weight: 0.5,
  },
  {
    id: 'oil-of-slipperiness',
    name: 'Óleo de Besuntamiento',
    englishName: 'Oil of Slipperiness',
    type: 'Poção Mágica (Óleo)',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Aplicar este óleo no corpo leva 10 minutos. Por 8 horas, você ganha os efeitos da magia Movimentação Livre (Freedom of Movement).',
    value: '150 PO',
    weight: 0.5,
  },

  // ==========================================
  // ITENS MARAVILHOSOS (WONDROUS ITEMS)
  // ==========================================
  {
    id: 'bag-of-holding',
    name: 'Mochila de Carga',
    englishName: 'Bag of Holding',
    type: 'Item Mágico (Maravilhoso)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Esta mochila possui um espaço interior extradimensional consideravelmente maior que suas dimensões externas. Ela pode conter até 250 kg de peso e tem um volume máximo de 1,8 metros cúbicos. A mochila pesa sempre 7,5 kg, independentemente do conteúdo.',
    value: '500 PO',
    weight: 15,
  },
  {
    id: 'handy-haversack',
    name: 'Mochila Prática de Heward',
    englishName: "Heward's Handy Haversack",
    type: 'Item Mágico (Maravilhoso)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Esta mochila tem um bolso central e dois bolsos laterais extradimensionais. Qualquer item colocado na mochila estará sempre no topo quando você estender a mão para retirá-lo, exigindo apenas uma ação interativa.',
    value: '2.000 PO',
    weight: 5,
  },
  {
    id: 'portable-hole',
    name: 'Buraco Portátil',
    englishName: 'Portable Hole',
    type: 'Item Mágico (Maravilhoso)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: false,
    description: 'Um pano preto dobrável que se desdobra em um círculo de 1,8 metros de diâmetro. Quando colocado em uma superfície sólida, cria um espaço extradimensional de 3 metros de profundidade.',
    value: '5.000 PO',
    weight: 0.1,
  },
  {
    id: 'boots-of-elvenkind',
    name: 'Botas de Elfo',
    englishName: 'Boots of Elvenkind',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Enquanto usar estas botas, seus passos não produzem som e você tem vantagem em testes de Destreza (Furtividade) que dependam de se mover silenciosamente.',
    value: '400 PO',
    weight: 1,
  },
  {
    id: 'boots-of-speed',
    name: 'Botas de Velocidade',
    englishName: 'Boots of Speed',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar estas botas, você pode usar uma ação bônus para estalar os calcanhares e dobrar seu deslocamento de caminhada. Ataques de oportunidade contra você têm desvantagem enquanto o efeito estiver ativo (até 10 minutos por dia).',
    value: '4.000 PO',
    weight: 1,
  },
  {
    id: 'boots-of-striding-and-springing',
    name: 'Botas de Passada e Pulo',
    englishName: 'Boots of Striding and Springing',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Seu deslocamento de caminhada se torna 9 metros se for menor, e não é reduzido por carregar peso excessivo. Além disso, a distância de seus saltos é triplicada.',
    value: '450 PO',
    weight: 1,
  },
  {
    id: 'winged-boots',
    name: 'Botas Aladas',
    englishName: 'Winged Boots',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar estas botas, você ganha deslocamento de voo igual ao seu deslocamento de caminhada. Você pode voar por até 4 horas por dia (fracionáveis).',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'cloak-of-displacement',
    name: 'Capa do Deslocamento',
    englishName: 'Cloak of Displacement',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar esta capa, ela projeta uma ilusão mágica de você ao seu lado, fazendo com que todas as jogadas de ataque contra você tenham Desvantagem. Se você sofrer dano, a ilusão é interrompida até o início do seu próximo turno.',
    value: '4.000 PO',
    weight: 3,
  },
  {
    id: 'cloak-of-elvenkind',
    name: 'Capa de Elfo',
    englishName: 'Cloak of Elvenkind',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Com o capuz levantado, testes de Sabedoria (Percepção) feitos para notar você têm desvantagem, e você tem vantagem em testes de Destreza (Furtividade) para se esconder.',
    value: '500 PO',
    weight: 1,
  },
  {
    id: 'cloak-of-protection',
    name: 'Capa de Proteção',
    englishName: 'Cloak of Protection',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Você recebe +1 de bônus na Classe de Armadura (CA) e em todos os testes de resistência enquanto usar esta capa.',
    value: '500 PO',
    weight: 3,
  },
  {
    id: 'cloak-of-the-bat',
    name: 'Capa do Morcego',
    englishName: 'Cloak of the Bat',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Esta capa concede vantagem em testes de Destreza (Furtividade). Na penumbra ou escuridão, você pode voar ou se transformar em um morcego.',
    value: '2.500 PO',
    weight: 3,
  },
  {
    id: 'bracers-of-archery',
    name: 'Braceletes de Arquearia',
    englishName: 'Bracers of Archery',
    type: 'Item Mágico (Braçadeiras)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar estes braceletes, você tem proficiência com arco curto e arco longo, e recebe +2 de bônus nas jogadas de dano com arcos.',
    value: '300 PO',
    weight: 1,
  },
  {
    id: 'bracers-of-defense',
    name: 'Braceletes da Defesa',
    englishName: 'Bracers of Defense',
    type: 'Item Mágico (Braçadeiras)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Você recebe +2 de bônus na CA se não estiver usando armadura nem empunhando um escudo.',
    value: '3.000 PO',
    weight: 1,
  },
  {
    id: 'gauntlets-of-ogre-power',
    name: 'Manoplas de Força do Ogro',
    englishName: 'Gauntlets of Ogre Power',
    type: 'Item Mágico (Luvas)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Seu valor de Força se torna 19 enquanto usar estas manoplas de metal pesado.',
    value: '500 PO',
    weight: 2,
  },
  {
    id: 'headband-of-intellect',
    name: 'Tiara de Inteligência',
    englishName: 'Headband of Intellect',
    type: 'Item Mágico (Diadema)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Seu valor de Inteligência se torna 19 enquanto usar este diadema cravejado.',
    value: '500 PO',
    weight: 0.5,
  },
  {
    id: 'amulet-of-health',
    name: 'Amuleto de Saúde',
    englishName: 'Amulet of Health',
    type: 'Item Mágico (Amuleto)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Seu valor de Constituição se torna 19 enquanto usar este amuleto reluzente.',
    value: '4.000 PO',
    weight: 1,
  },
  {
    id: 'belt-of-giant-strength-hill',
    name: 'Cinto de Força do Gigante da Colina',
    englishName: 'Belt of Hill Giant Strength',
    type: 'Item Mágico (Cinto)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Seu valor de Força se torna 21 enquanto usar este cinto trabalhado em couro e ossos.',
    value: '4.000 PO',
    weight: 4,
  },
  {
    id: 'belt-of-giant-strength-fire',
    name: 'Cinto de Força do Gigante do Fogo',
    englishName: 'Belt of Fire Giant Strength',
    type: 'Item Mágico (Cinto)',
    category: 'Item Maravilhoso',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Seu valor de Força se torna 25 enquanto usar este cinto forjado em ferro e brasas.',
    value: '20.000 PO',
    weight: 4,
  },
  {
    id: 'stone-of-good-luck',
    name: 'Pedra da Sorte (Luckstone)',
    englishName: 'Stone of Good Luck',
    type: 'Item Mágico (Pedra)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Enquanto esta pedra polida estiver com você, você recebe +1 de bônus em todos os testes de habilidade e testes de resistência.',
    value: '600 PO',
    weight: 0.5,
  },
  {
    id: 'deck-of-many-things',
    name: 'Baralho das Coisas Múltiplas',
    englishName: 'Deck of Many Things',
    type: 'Item Mágico (Artefato)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: false,
    description: 'Este baralho de marfim ou pergaminho contém 13 ou 22 cartas gravadas com símbolos místico-fatídicos. Antes de puxar uma carta, você deve declarar quantas pretende puxar. Cada carta produz um efeito permanente e avassalador (concedendo desejos, riquezas, ruína da alma, avatares da morte ou ruína de reinos).',
    value: '50.000 PO',
    weight: 1,
  },
  {
    id: 'eyes-of-minute-seeing',
    name: 'Olhos de Ver Detalhes',
    englishName: 'Eyes of Minute Seeing',
    type: 'Item Mágico (Óculos)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Lentes de cristal que permitem enxergar pequenos detalhes a até 30 cm de distância com clareza microscópica, concedendo vantagem em testes de Sabedoria (Percepção) para examinar objetos pequenos.',
    value: '300 PO',
    weight: 0.5,
  },
  {
    id: 'goggles-of-night',
    name: 'Óculos da Noite',
    englishName: 'Goggles of Night',
    type: 'Item Mágico (Óculos)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Enquanto usar estes óculos com lentes escuras, você ganha Visão no Escuro em um raio de 18 metros. Se você já tiver Visão no Escuro, o alcance aumenta em 18 metros.',
    value: '400 PO',
    weight: 0.5,
  },
  {
    id: 'helm-of-comprehending-languages',
    name: 'Elmo de Compreender Idiomas',
    englishName: 'Helm of Comprehending Languages',
    type: 'Item Mágico (Elmo)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Enquanto usar este elmo, você pode entender o significado de qualquer idioma falado ou escrito que você ouvir ou ler.',
    value: '500 PO',
    weight: 3,
  },
  {
    id: 'helm-of-telepathy',
    name: 'Elmo de Telepatia',
    englishName: 'Helm of Telepathy',
    type: 'Item Mágico (Elmo)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização',
    description: 'Permite se comunicar telepaticamente com criaturas a até 9 metros, usar a magia Ler Pensamentos (Detect Thoughts) e Sugestão (Suggestion).',
    value: '1.500 PO',
    weight: 3,
  },
  {
    id: 'helm-of-teleportation',
    name: 'Elmo de Teleporte',
    englishName: 'Helm of Teleportation',
    type: 'Item Mágico (Elmo)',
    category: 'Item Maravilhoso',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Este elmo possui 3 cargas. Enquanto o usar, você pode gastar 1 carga para conjurar a magia Teleporte.',
    value: '4.500 PO',
    weight: 3,
  },
  {
    id: 'robe-of-useful-items',
    name: 'Robe de Itens Úteis',
    englishName: 'Robe of Useful Items',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Um manto coberto de remendos de tecido com formatos de itens cotidianos (escadas, adagas, espelhos, barcos, cavalos). Você pode destacar um remendo para transformá-lo no item real instantaneamente.',
    value: '1.000 PO',
    weight: 4,
  },
  {
    id: 'robe-of-the-archmagi',
    name: 'Robe dos Arquimagos',
    englishName: 'Robe of the Archmagi',
    type: 'Item Mágico (Vestuário)',
    category: 'Item Maravilhoso',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização por Conjurador (Mago, Bruxo ou Feiticeiro)',
    description: 'Este manti nobre concede CA base 15 + mod de Destreza, vantagem em testes de resistência contra magias e efeitos mágicos, e aumenta a CD de suas magias e o bônus de ataque mágico em +2.',
    value: '40.000 PO',
    weight: 4,
  },

  // ==========================================
  // ARMAS MÁGICAS (MAGIC WEAPONS)
  // ==========================================
  {
    id: 'weapon-plus-1',
    name: 'Arma Mágica +1',
    englishName: 'Weapon +1',
    type: 'Arma Mágica (Qualquer)',
    category: 'Arma',
    rarity: 'Incomum',
    attunement: false,
    description: 'Você tem +1 de bônus nas jogadas de ataque e dano feitas com esta arma mágica.',
    value: '500 PO',
    weight: 3,
  },
  {
    id: 'weapon-plus-2',
    name: 'Arma Mágica +2',
    englishName: 'Weapon +2',
    type: 'Arma Mágica (Qualquer)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: false,
    description: 'Você tem +2 de bônus nas jogadas de ataque e dano feitas com esta arma mágica.',
    value: '4.000 PO',
    weight: 3,
  },
  {
    id: 'weapon-plus-3',
    name: 'Arma Mágica +3',
    englishName: 'Weapon +3',
    type: 'Arma Mágica (Qualquer)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Você tem +3 de bônus nas jogadas de ataque e dano feitas com esta arma mágica.',
    value: '16.000 PO',
    weight: 3,
  },
  {
    id: 'flame-tongue',
    name: 'Língua de Fogo',
    englishName: 'Flame Tongue',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Você pode usar uma ação bônus para falar a palavra de comando, fazendo com que chamas brotem da lâmina. Enquanto ardendo, a espada emite luz brilhante num raio de 12 metros e causa 2d6 de dano de fogo adicional em cada acerto.',
    value: '5.000 PO',
    weight: 3,
  },
  {
    id: 'frost-brand',
    name: 'Marca do Gelo',
    englishName: 'Frost Brand',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Esta espada causa 1d6 de dano de frio adicional em cada acerto. Enquanto a segurar, você tem resistência a dano de fogo.',
    value: '12.000 PO',
    weight: 3,
  },
  {
    id: 'sun-blade',
    name: 'Lâmina do Sol',
    englishName: 'Sun Blade',
    type: 'Arma Mágica (Espada Curta/Longa)',
    category: 'Arma',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Esta empunhadura sem lâmina emite uma lâmina de radiação solar pura. A arma tem +2 nas jogadas de ataque e dano, causa dano radiante em vez de cortante e causa +1d8 de dano radiante extra contra Mortos-Vivos.',
    value: '7.500 PO',
    weight: 2,
  },
  {
    id: 'holy-avenger',
    name: 'Vingadora Sagrada',
    englishName: 'Holy Avenger',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização por um Paladino',
    description: 'Esta espada concede +3 nas jogadas de ataque e dano. Causa 2d10 de dano radiante extra a demônios e mortos-vivos. Enquanto empunhada por um paladino, emite uma aura de 3 metros que concede vantagem em testes de resistência contra magias a todos os aliados.',
    value: '50.000 PO',
    weight: 3,
  },
  {
    id: 'vorpal-sword',
    name: 'Espada Vorpal',
    englishName: 'Vorpal Sword',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Você recebe +3 nas jogadas de ataque e dano com esta espada. Quando você rola um 20 natural na jogada de ataque, você decapita o alvo (se ele tiver pelo menos uma cabeça e puder sobreviver sem ela; caso contrário, sofre 6d8 de dano cortante extra).',
    value: '60.000 PO',
    weight: 3,
  },
  {
    id: 'luck-blade',
    name: 'Lâmina da Sorte',
    englishName: 'Luck Blade',
    type: 'Arma Mágica (Espada)',
    category: 'Arma',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Concede +1 nas jogadas de ataque, dano e testes de resistência. Uma vez por dia, você pode rerolar qualquer jogada de ataque ou teste. A espada vem com 1d3 cargas da magia Desejo (Wish).',
    value: '75.000 PO',
    weight: 3,
  },
  {
    id: 'javelin-of-lightning',
    name: 'Dardo de Relâmpago',
    englishName: 'Javelin of Lightning',
    type: 'Arma Mágica (Dardo)',
    category: 'Arma',
    rarity: 'Incomum',
    attunement: false,
    description: 'Quando arremessado, este dardo se transforma em um raio de eletricidade de 36 metros de comprimento e 1,5 metros de largura. Todas as criaturas na linha devem passar num TR de Destreza CD 13 ou sofrer 4d6 de dano elétrico.',
    value: '750 PO',
    weight: 2,
  },

  // ==========================================
  // ARMADURAS & ESCUDOS (ARMOR & SHIELDS)
  // ==========================================
  {
    id: 'armor-plus-1',
    name: 'Armadura Mágica +1',
    englishName: 'Armor +1',
    type: 'Armadura Mágica (Qualquer)',
    category: 'Armadura',
    rarity: 'Rara',
    attunement: false,
    description: 'Você recebe +1 de bônus na Classe de Armadura enquanto usar esta armadura.',
    value: '1.500 PO',
    weight: 20,
  },
  {
    id: 'armor-plus-2',
    name: 'Armadura Mágica +2',
    englishName: 'Armor +2',
    type: 'Armadura Mágica (Qualquer)',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Você recebe +2 de bônus na Classe de Armadura enquanto usar esta armadura.',
    value: '6.000 PO',
    weight: 20,
  },
  {
    id: 'armor-plus-3',
    name: 'Armadura Mágica +3',
    englishName: 'Armor +3',
    type: 'Armadura Mágica (Qualquer)',
    category: 'Armadura',
    rarity: 'Lendária',
    attunement: false,
    description: 'Você recebe +3 de bônus na Classe de Armadura enquanto usar esta armadura.',
    value: '24.000 PO',
    weight: 20,
  },
  {
    id: 'shield-plus-1',
    name: 'Escudo Mágico +1',
    englishName: 'Shield +1',
    type: 'Escudo Mágico',
    category: 'Armadura',
    rarity: 'Incomum',
    attunement: false,
    description: 'Enquanto empunhar este escudo, você ganha +1 de bônus adicional na CA (totalizando +3 de CA).',
    value: '400 PO',
    weight: 6,
  },
  {
    id: 'animated-shield',
    name: 'Escudo Animado',
    englishName: 'Animated Shield',
    type: 'Escudo Mágico',
    category: 'Armadura',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização',
    description: 'Você pode usar uma ação bônus para soltar este escudo e pronunciar a palavra de comando. O escudo flutua no ar ao seu redor por 1 minuto, protegendo você como se estivesse empunhado, mas deixando suas mãos livres.',
    value: '6.000 PO',
    weight: 6,
  },

  // ==========================================
  // ANÉIS MÁGICOS (RINGS)
  // ==========================================
  {
    id: 'ring-of-protection',
    name: 'Anel de Proteção',
    englishName: 'Ring of Protection',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Você recebe +1 de bônus na Classe de Armadura e em todos os testes de resistência enquanto usar este anel polido.',
    value: '3.500 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-invisibility',
    name: 'Anel de Invisibilidade',
    englishName: 'Ring of Invisibility',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Lendária',
    attunement: 'Requer Sintonização',
    description: 'Enquanto usar este anel, você pode usar uma ação para ficar invisível. Qualquer coisa que esteja vestindo ou carregando fica invisível também. O efeito termina se você atacar ou conjurar uma magia.',
    value: '50.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-spell-storing',
    name: 'Anel de Armazenar Magia',
    englishName: 'Ring of Spell Storing',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Este anel armazena até 5 níveis de magias conjuradas nele por qualquer conjurador. O usuário do anel pode conjurar qualquer magia armazenada nele usando a CD e modificadores do conjurador original.',
    value: '4.000 PO',
    weight: 0.1,
  },
  {
    id: 'ring-of-feather-falling',
    name: 'Anel de Queda Suave',
    englishName: 'Ring of Feather Falling',
    type: 'Anel Mágico',
    category: 'Anel',
    rarity: 'Rara',
    attunement: 'Requer Sintonização',
    description: 'Quando você estiver caindo enquanto usa este anel, você desce a 18 metros por rodada e não sofre dano de queda.',
    value: '2.000 PO',
    weight: 0.1,
  },

  // ==========================================
  // VARINHAS, CAJADOS & BASTÕES (WANDS, STAVES & RODS)
  // ==========================================
  {
    id: 'wand-of-magic-missiles',
    name: 'Varinha de Mísseis Mágicos',
    englishName: 'Wand of Magic Missiles',
    type: 'Varinha Mágica',
    category: 'Varinha',
    rarity: 'Incomum',
    attunement: false,
    description: 'Esta varinha tem 7 cargas. Enquanto a segurar, você pode usar uma ação para gastar 1 ou mais cargas para conjurar a magia Mísseis Mágicos (1 carga = 1º nível, +1 carga por nível superior). Recupera 1d6 + 1 cargas ao amanhecer.',
    value: '300 PO',
    weight: 1,
  },
  {
    id: 'wand-of-fireballs',
    name: 'Varinha de Bolas de Fogo',
    englishName: 'Wand of Fireballs',
    type: 'Varinha Mágica',
    category: 'Varinha',
    rarity: 'Rara',
    attunement: 'Requer Sintonização por um Conjurador',
    description: 'Esta varinha possui 7 cargas. Você pode gastar de 1 a 3 cargas para conjurar a magia Bola de Fogo (CD 15). Recupera 1d6 + 1 cargas por dia.',
    value: '4.500 PO',
    weight: 1,
  },
  {
    id: 'staff-of-power',
    name: 'Cajado do Poder',
    englishName: 'Staff of Power',
    type: 'Cajado Mágico',
    category: 'Cajado',
    rarity: 'Muito Rara',
    attunement: 'Requer Sintonização por Mago, Bruxo ou Feiticeiro',
    description: 'Concede +2 na CA, +2 nos testes de resistência e +2 no ataque mágico. Possui 20 cargas para conjurar diversas magias poderosas (Bola de Fogo, Raio Solar, Paralisar Monstro, etc.) e pode ser quebrado em um Retribuição Golpe (Golpe Suicida de Energia).',
    value: '25.000 PO',
    weight: 4,
  },
  {
    id: 'rod-of-the-pact-keeper-plus-1',
    name: 'Bastão do Guardião do Pacto +1',
    englishName: 'Rod of the Pact Keeper +1',
    type: 'Bastão Mágico',
    category: 'Bastão',
    rarity: 'Incomum',
    attunement: 'Requer Sintonização por um Bruxo',
    description: 'Enquanto segurar este bastão, você ganha +1 de bônus nas jogadas de ataque mágico e na CD dos testes de resistência das suas magias de Bruxo. Além disso, pode recuperar 1 espaço de magia de Bruxo como ação bônus 1 vez por dia.',
    value: '600 PO',
    weight: 2,
  }
];

const ALL_ITEMS_WITH_DUPLICATES: SRDItem[] = [
  ...BATCH_1_ITEMS,
  ...BATCH_2_RINGS,
  ...BATCH_3_WANDS_STAVES_RODS,
  ...BATCH_4_WEAPONS,
  ...BATCH_5_ARMORS,
  ...BATCH_6_WONDROUS_A_I,
  ...BATCH_7_WONDROUS_J_Z,
  ...BATCH_8_POTIONS_SCROLLS,
  ...BATCH_9_WEARABLES,
  ...BATCH_10_COLLECTIONS,
  ...BATCH_11_WONDROUS,
  ...BATCH_12_GENERIC_GEAR,
  ...BATCH_13_VARIANTS,
  ...BATCH_14_UNIQUES
];

// Remove duplicates by ID (keeping the newest one that was added)
export const ALL_SRD_ITEMS: SRDItem[] = Array.from(
  new Map(ALL_ITEMS_WITH_DUPLICATES.map(item => [item.id, item])).values()
);
