import { SRDItem } from './types';

export const BATCH_8_POTIONS_SCROLLS: SRDItem[] = [
  {
    id: 'potion-of-animal-friendship',
    name: 'Poção de Amizade Animal',
    englishName: 'Potion of Animal Friendship',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Incomum',
    attunement: false,
    description: 'Permite lançar o efeito de Amizade Animal (Sabedoria CD 13) por 1 hora contra todas as feras visíveis num raio curto, deixando-as amigáveis passivas e sem intenção de atacá-lo.',
    value: '100 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-clairvoyance',
    name: 'Poção de Clarividência',
    englishName: 'Potion of Clairvoyance',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Rara',
    attunement: false,
    description: 'Ao beber, concede a habilidade Clarividência por dez minutos. Você cria e escolhe um foco de visualização arcana distante invisível ou ouvir lugares remotos sem o perigo de presença física.',
    value: '500 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-flying',
    name: 'Poção de Voo (Voar)',
    englishName: 'Potion of Flying',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Providencia um incrível deslocamento de vôo equivalente à sua velocidade de caminhada ativa durante toda 1 Hora cronometrada sem perigo de cair fatalmente antes de acabar gradualmente no solo macio.',
    value: '800 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-vitality',
    name: 'Poção de Vitalidade',
    englishName: 'Potion of Vitality',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Cura exaustão perigosa/venenos contínuos e restabelece a maximização global dos Pontos de Vida (curando nos dados diários curtos tudo completo e absoluto sem rolagens médias) pelas próximas 24 horas passivas inteiras.',
    value: '1.200 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-giant-strength-frost',
    name: 'Poção de Força do Gigante do Gelo',
    englishName: 'Potion of Frost Giant Strength',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Rara',
    attunement: false,
    description: 'Sua Força física expande bruscamente pra valor mágico fixado a 23 (Mod. +6) durante um período de 1 Hora atípica.',
    value: '500 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-giant-strength-cloud',
    name: 'Poção de Força do Gigante das Nuvens',
    englishName: 'Potion of Cloud Giant Strength',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Muito Rara',
    attunement: false,
    description: 'Sua força expande aos colossais braços de gigante das nuvens, elevando massivamente para valor 27 (Mod. +8) numa duração de 1 Hora.',
    value: '1.000 PO',
    weight: 0.5,
  },
  {
    id: 'potion-of-giant-strength-storm',
    name: 'Poção de Força do Gigante da Tempestade',
    englishName: 'Potion of Storm Giant Strength',
    type: 'Poção Mágica',
    category: 'Poção',
    rarity: 'Lendária',
    attunement: false,
    description: 'Força divina inquebrável. Altera permanentemente durante 1 Hora seus limites absolutos máximos de atributos de D&D para um colossal Status (Força/STR = 29 e +9 de Modificador nos golpes perigosos).',
    value: '3.000 PO',
    weight: 0.5,
  },
  {
    id: 'spell-scroll-cantrip',
    name: 'Pergaminho de Magia (Truque)',
    englishName: 'Spell Scroll (Cantrip)',
    type: 'Pergaminho Mágico',
    category: 'Item Maravilhoso',
    rarity: 'Comum',
    attunement: false,
    description: 'Contém um feitiço cantrip inscrito no pergaminho místico. A leitura requer o truque na sua lista de magia. O papel se desintegra em cinzas pós lido sem perdas pra você.',
    value: '50 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-level-1',
    name: 'Pergaminho de Magia (1º Nível)',
    englishName: 'Spell Scroll (Level 1)',
    type: 'Pergaminho Mágico',
    category: 'Item Maravilhoso',
    rarity: 'Comum',
    attunement: false,
    description: 'Feitiço poderoso Nv 1 garantido sob um teste de (CD 13 Resistência Alvo / +5 Ataque do Papel lido) consumindo no lançamento direto veloz nas linhas.',
    value: '100 PO',
    weight: 0.1,
  },
  {
    id: 'spell-scroll-level-3',
    name: 'Pergaminho de Magia (3º Nível)',
    englishName: 'Spell Scroll (Level 3)',
    type: 'Pergaminho Mágico',
    category: 'Item Maravilhoso',
    rarity: 'Incomum',
    attunement: false,
    description: 'Feitiço perigoso massivo de Nível 3 mágico condensado no pergaminho (ex: Bola de fogo focada sem gastar seu Spell Slot na aventura), (CD resistir Alvo 15 / ataque somado +7 no papel de feitiço absoluto).',
    value: '300 PO',
    weight: 0.1,
  }
];
