import { SRDSpell } from './types';

export const BATCH_5_SPELLS: SRDSpell[] = [
  // NÍVEL 8
  {
    id: 'incendiary-cloud',
    name: 'Névoa Incendiária (Incendiary Cloud)',
    englishName: 'Incendiary Cloud',
    level: 8,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '45 metros (150 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 6, sizeUnit: 'm', formatted: 'Névoa de 6m raio' },
    damageSave: { damageDice: '10d8', damageType: 'Fogo', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'Nuvem rodopiante fumegante opaca surge, obscurece tudo e afasta 3m por turno pela brisa. Quem começa ali dentro rola TR de Destreza pra não levar brutal queima de 10d8 dano Fogo (Metade se passar).',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'maze',
    name: 'Labirinto (Maze)',
    englishName: 'Maze',
    level: 8,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 10 minutos',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Bane automaticamente ALVO para uma dimensão extraplanar labiríntica sem salvamento inicial! A cada turno dele ele gasta AÇÃO e rola TESTE INTELIGÊNCIA CD 20 pra escapar das paredes. Se não passar, fica banido preso sumido por 10 minutos correndo.',
    classes: ['Mago']
  },
  {
    id: 'mind-blank',
    name: 'Limpar a Mente (Mind Blank)',
    englishName: 'Mind Blank',
    level: 8,
    school: 'Abjuração',
    castingTime: '1 ação',
    range: 'Toque',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Proteção mental absoluta 24H. Imunidade total à Psíquico (Dano), à efeitos de Ler mentes, Encantamento (Charm), Adivinhação de magia alheia para saber onde o alvo se encontra, até feitiço Desejo é falho em influenciar/achar esta pessoa tocada.',
    classes: ['Bardo', 'Mago']
  },
  {
    id: 'power-word-stun',
    name: 'Palavra de Poder Atordoar (Power Word Stun)',
    englishName: 'Power Word Stun',
    level: 8,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { saveStat: 'CON', saveEffect: 'negate', attackType: 'save' },
    description: 'Diga a palavra dominadora. Se a criatura atualizada TIVER 150 PVs OU MENOS: Fica ATORDOADA IMEDIATAMENTE. Ela faz um TR de Constituição só no FIM de seus próximos turnos para finalmente conseguir encerrar a paralisia.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'sunburst',
    name: 'Explosão Solar (Sunburst)',
    englishName: 'Sunburst',
    level: 8,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '45 metros (150 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'um espelho fogo', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 18, sizeUnit: 'm', formatted: 'Esfera Gigante 18m Raio' },
    damageSave: { damageDice: '12d6', damageType: 'Radiante', saveStat: 'CON', saveEffect: 'half', attackType: 'save' },
    description: 'Um pilar radiante solar espalha-se 18m raio (Extremamente enorme). Todos TR Constituição 12d6 radiante e Cega quem falhar. Morte vivas e limo rolam desvantagem no salvamento (é Luz real de sol que detona vampiros).',
    classes: ['Druida', 'Feiticeiro', 'Mago']
  },
  {
    id: 'telepathy',
    name: 'Telepatia (Telepathy)',
    englishName: 'Telepathy',
    level: 8,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Especial (Ilimitado)',
    duration: '24 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'fio prata anel', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura Familiar' },
    damageSave: { attackType: 'utility' },
    description: 'Você forja um elo mental 24 Horas com 1 ser conhecido em qualquer lugar do universo que compartilhe do seu mesmo Plano, falando livremente conversando com ele telepaticamente (partilhando emoções).',
    classes: ['Mago']
  },

  // NÍVEL 9
  {
    id: 'astral-projection',
    name: 'Projeção Astral (Astral Projection)',
    englishName: 'Astral Projection',
    level: 9,
    school: 'Necromancia',
    castingTime: '1 hora',
    range: 'Toque',
    duration: 'Especial',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'por pessoa 1 Jacinto raro 1000 PO e fio ouro (consumidos)', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: 'Você e até 8 Voluntários' },
    damageSave: { attackType: 'utility' },
    description: 'Descola a Alma do Corpo (entra em animação suspensa viva em estase) de seu grupo para migrarem pro Plano Astral. Ficam presos lá unidos pelo Fio Prateado inquebrável. Se o fio cortar ou HP astral zerar o alvo ACORDA NO CORPO com zero feridas (Dano não transfere pro corpo físico!).',
    classes: ['Clérigo', 'Mago']
  },
  {
    id: 'foresight',
    name: 'Sexto Sentido / Previsão (Foresight)',
    englishName: 'Foresight',
    level: 9,
    school: 'Adivinhação',
    castingTime: '1 minuto',
    range: 'Toque',
    duration: '8 horas',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'pena de beijaflor puro', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Dá ao ser um presságio de futuro imediato sem chance surpresas Hacking na Matrix das lutas por 8 Horas: Não pode ser surpreso, e VOCÊ RECEBE VANTAGEM NOS SEUS ATAQUES/TESTES HABILIDADE/SALVAMENTOS, E INIMIGOS TEM DESVANTAGEM NOS DELES CONTRA VOCÊ!',
    classes: ['Bardo', 'Druida', 'Mago']
  },
  {
    id: 'gate',
    name: 'Portal (Gate)',
    englishName: 'Gate',
    level: 9,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'diamante perfeito puro brilhante de 5000 PO', raw: 'V, S, M' },
    targetArea: { type: 'area', shape: 'wall', sizeValue: 6, sizeUnit: 'm', formatted: 'Portal 6m em outro Plano' },
    damageSave: { attackType: 'utility' },
    description: 'Cria Fenda Estelar Interdimensional pra qual mundo desejar, onde vc pode Puxar UM SER NOMEADO ESPECÍFICO pelo nome Verdadeiro pra ser Trazido a Força pela gola dele do outro plano pra cair imediatamente na sua frente e ser lidado (ou fugir para este plano que viu).',
    classes: ['Clérigo', 'Feiticeiro', 'Mago']
  },
  {
    id: 'imprisonment',
    name: 'Aprisionamento (Imprisonment)',
    englishName: 'Imprisonment',
    level: 9,
    school: 'Abjuração',
    castingTime: '1 minuto',
    range: '9 metros (30 pés)',
    duration: 'Até dissipada',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'representação visual especial que emula vitima, pó estelar especial 500PO de HD / Nível, componente ritual consumido a depender prisão (correntes)', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura Mítica/Alvo' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'save' },
    description: 'O Mago dita uma prisão perpétua divina. Se Alvo falhar TR Sabedoria, Escolha forma: 1- Sepultamento Terra Oculta, 2- Acorrentado Intocável Fixo, 3- Labirinto Estacionário Invisível, 4- Miniatura Minúscula pra carregar, 5- Indução Sonolenta pra dormir perene debaixo do templo. Requer Desejo divino p/ anular!',
    classes: ['Bruxo', 'Mago']
  },
  {
    id: 'mass-heal',
    name: 'Cura Completa em Massa (Mass Heal)',
    englishName: 'Mass Heal',
    level: 9,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 18, sizeUnit: 'm', formatted: 'Criaturas à Escolha em 18m' },
    damageSave: { damageDice: '700', damageType: 'Cura', attackType: 'utility' },
    description: 'Cura Radiante Absoluta Mítica: Distribua LIVREMENTE EXATOS 700 PONTOS DE VIDA DE CURA pra quem você quiser nas proximidades!!! Além de Dissipar qualquer Cegueira, Doença Surdez sem teste em cada que se beneficiou dos Pontos vitais!',
    classes: ['Clérigo']
  },
  {
    id: 'meteor-swarm',
    name: 'Chuva de Meteoros (Meteor Swarm)',
    englishName: 'Meteor Swarm',
    level: 9,
    school: 'Evocação',
    castingTime: '1 ação',
    range: '1.6 quilômetros (1 milha)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'sphere', sizeValue: 12, sizeUnit: 'm', formatted: '4 Esferas Gigantes (12m Raio)' },
    damageSave: { damageDice: '20d6 Fogo + 20d6 Contund.', damageType: 'Fogo/Contundente', saveStat: 'DEX', saveEffect: 'half', attackType: 'save' },
    description: 'O apocalipse na ponta dos dedos. Você mira QUATRO PONTOS DISTINTOS dentro de uma Milha, em cada ponto DESTRÓI COM CHUVA 12m esfera: Dando ABSURDOS 20d6 Dano Fogo + 20d6 Dano Contundente (Metade com TR Destreza). Pega construções. Se um azarado tiver nas 2 áreas entrepostas leva apenas dano 1x, não duplica.',
    classes: ['Feiticeiro', 'Mago']
  },
  {
    id: 'power-word-heal',
    name: 'Palavra de Poder Curar (Power Word Heal)',
    englishName: 'Power Word Heal',
    level: 9,
    school: 'Evocação',
    castingTime: '1 ação',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Magia Vocal: O alvo toca recupera IMEDIATAMENTE os Seus Pontos De Vida Pro Seu Maximo Limite 100%! Remove Encantado/Assustado/Paralisado/Caído.',
    classes: ['Bardo']
  },
  {
    id: 'power-word-kill',
    name: 'Palavra de Poder Matar (Power Word Kill)',
    englishName: 'Power Word Kill',
    level: 9,
    school: 'Encantamento',
    castingTime: '1 ação',
    range: '18 metros (60 pés)',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura' },
    damageSave: { attackType: 'utility' },
    description: 'Se a criatura que ouvir tiver ATUALMENTE 100 PVs ou menos, ELA MORRE INSTANTANEAMENTE (Sem testes resistência TR pra resistir. Simplesmente o coração cessa mágico). Senão não faz nada e vc perde a magia nível 9 inteira.',
    classes: ['Bardo', 'Feiticeiro', 'Bruxo', 'Mago']
  },
  {
    id: 'shapechange',
    name: 'Alterar Forma (Shapechange)',
    englishName: 'Shapechange',
    level: 9,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, materialsDescription: 'Diadema de joias com formato serpente valendo 1.500 PO', raw: 'V, S, M' },
    targetArea: { type: 'self', shape: 'self' },
    damageSave: { attackType: 'utility' },
    description: 'Polimorfa VOCÊ para qualquer Monstro ND Equivalente do Seu Nivel para Menor que ja tenha visto (Exemplo, Dragão Ancião, Demônio). VocÊ MATÉM Suas Características de Sabedoria/INT e Alinhamentos e Classe, mas ASSUME o HP Corpo Fisico e ATAQUES MITICOS do monstro, pode gastar AÇÃO NO TURNO para TROCAR DE MONSTRO!',
    classes: ['Druida', 'Mago']
  },
  {
    id: 'storm-of-vengeance',
    name: 'Tempestade de Vingança (Storm of Vengeance)',
    englishName: 'Storm of Vengeance',
    level: 9,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: 'Visão',
    duration: 'Até 1 minuto',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: false, raw: 'V, S' },
    targetArea: { type: 'area', shape: 'cylinder', sizeValue: 110, sizeUnit: 'm', formatted: 'Raio de 110m (360 pés)' },
    damageSave: { attackType: 'save' },
    description: 'Concentração apocalíptica do Druida ao ar livre (raio 110m). Turnos: Rod 1 (Surdo Trovão), Rod 2 (Chuva de Ácido 1d6 contínuo em quem ficar), Rod 3 (Seis Raios caem 10d6 para 6 inimigos TR Destr), Rod 4 (Granizo 2d6) Rodada 5+ (Gelo frio intenso até os fim 10 rodadas). Destrói tudo e cega e pune as hordas campais.',
    classes: ['Druida']
  },
  {
    id: 'true-polymorph',
    name: 'Metamorfose Verdadeira (True Polymorph)',
    englishName: 'True Polymorph',
    level: 9,
    school: 'Transmutação',
    castingTime: '1 ação',
    range: '9 metros (30 pés)',
    duration: 'Até 1 hora',
    concentration: true,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, materialsDescription: 'uma gota de mercúrio e argila moldável', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'single_target', formatted: '1 Criatura ou Objeto' },
    damageSave: { saveStat: 'WIS', saveEffect: 'negate', attackType: 'utility' },
    description: 'Transforma CRIATURA PARA CRIATURA (Monstros equivalentes ND) / CRIATURA EM OBJETO INANIMADO / OBJETO EM CRIATURA! SE VOCÊ MANTER CONCENTRADO POR 1 HORA DE CURSO TOTAL A MAGIA É PERMANENTE PRA SEMPRE NA VÍTIMA! O Rei tirano pode ser virado um Cão, ou uma Montanha virada em um Dragão real leal seu permanente.',
    classes: ['Bardo', 'Bruxo', 'Mago']
  },
  {
    id: 'true-resurrection',
    name: 'Ressurreição Verdadeira (True Resurrection)',
    englishName: 'True Resurrection',
    level: 9,
    school: 'Necromancia',
    castingTime: '1 hora',
    range: 'Toque',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: true, material: true, costly: true, consumed: true, materialsDescription: 'água benta e diamantes que somem 25.000 PO valiosos de uma vez consumidos', raw: 'V, S, M' },
    targetArea: { type: 'target', shape: 'touch', formatted: '1 Vida (Nomeada)' },
    damageSave: { attackType: 'utility' },
    description: 'O Pináculo da Vida divina! Traz uma pessoa MORTA A ATÉ NO MÁXIMO 200 ANOS sem falha sem punição de exaustão e até mesmo CRIA UM CORPO FISICO DO ZERO caso ele não exista ou tenha sido engolido / vaporizado (Neste caso você o conjura de frente e nomeia a alma)!',
    classes: ['Clérigo', 'Druida']
  },
  {
    id: 'wish',
    name: 'Desejo (Wish)',
    englishName: 'Wish',
    level: 9,
    school: 'Conjuração',
    castingTime: '1 ação',
    range: 'Pessoal',
    duration: 'Instantânea',
    concentration: false,
    ritual: false,
    components: { verbal: true, somatic: false, material: false, raw: 'V' },
    targetArea: { type: 'self', shape: 'self', formatted: 'Alteração da Realidade Universal' },
    damageSave: { attackType: 'utility' },
    description: 'O feixe alterador do universo, a mais forte magia da Trama (Simples: Imita QUALQUER OUTRA MAGIA do jogo nivel 8 ou menos instantâneo SEM COMPONENTES)! Ou faça o Grande Desejo Complexo pra coisas loucas, o Mestre tem de analisar e decidir a reviravolta distorcida, e você SOBRECARREGA O CORPO, perdendo 33% (1d3 de chance percentual) de PERDER PRA SEMPRE a chance de usar Desejo no futuro!!!',
    classes: ['Feiticeiro', 'Mago']
  }
];
