import { CampaignCalendarConfig } from '@/lib/types/calendar';

export const HARPTOS_CALENDAR: CampaignCalendarConfig = {
  id: 'harptos',
  presetKey: 'harptos',
  name: 'Calendário de Harptos (Reinos Esquecidos / Faerûn)',
  yearSuffix: 'DR (Cômputo dos Vales)',
  daysOfWeek: [
    '1º Dia do Decêndio',
    '2º Dia do Decêndio',
    '3º Dia do Decêndio',
    '4º Dia do Decêndio',
    '5º Dia do Decêndio',
    '6º Dia do Decêndio',
    '7º Dia do Decêndio',
    '8º Dia do Decêndio',
    '9º Dia do Decêndio',
    '10º Dia do Decêndio',
  ],
  hoursInDay: 24,
  minutesInHour: 60,
  months: [
    { id: 'hammer', name: 'Hammer (Mundo Profundo)', days: 30, season: 'winter', description: 'Mês de frio intenso e tempestades de neve.' },
    { id: 'midwinter', name: 'Pleno Inverno (Festival Intercalar)', days: 1, season: 'winter', isIntercalary: true, description: 'Festival que marca a metade do inverno, tradicional para renovação de tratados.' },
    { id: 'alturiak', name: 'Alturiak (A Garra do Inverno)', days: 30, season: 'winter', description: 'Mês das piores geadas e ventos cortantes.' },
    { id: 'ches', name: 'Ches (O Pôr do Sol)', days: 30, season: 'spring', description: 'Equinócio de primavera e início do degelo.' },
    { id: 'tarsakh', name: 'Tarsakh (As Tempestades)', days: 30, season: 'spring', description: 'Mês de chuvas fortes e desabrochar das plantas.' },
    { id: 'greengrass', name: 'Relvaverde (Festival Intercalar)', days: 1, season: 'spring', isIntercalary: true, description: 'Celebração do florescer oficial da primavera e renascimento.' },
    { id: 'mirtul', name: 'Mirtul (O Degelo)', days: 30, season: 'spring', description: 'Tempo ideal para viagens e navegação segura.' },
    { id: 'kythorn', name: 'Kythorn (Tempo das Flores)', days: 30, season: 'summer', description: 'Clima quente e colheitas de frutas silvestres.' },
    { id: 'flamerule', name: 'Flamerule (A Maré de Verão)', days: 30, season: 'summer', description: 'Mês de calor escaldante e solstício de verão.' },
    { id: 'midsummer', name: 'Pleno Verão (Festival Intercalar)', days: 1, season: 'summer', isIntercalary: true, description: 'Noite de banquetes sob as estrelas e magias auspiciosas.' },
    { id: 'eleasis', name: 'Eleasis (O Alto Sol)', days: 30, season: 'summer', description: 'Mês mais quente do ano em Faerûn.' },
    { id: 'highharvestide', name: 'Alta Colheita (Festival Intercalar)', days: 1, season: 'autumn', isIntercalary: true, description: 'Grande feira gastronômica e bênçãos aos deuses da agricultura.' },
    { id: 'eleint', name: 'Eleint (O Desvanecer)', days: 30, season: 'autumn', description: 'Equinócio de outono e ventos dourados.' },
    { id: 'marpenoth', name: 'Marpenoth (Queda das Folhas)', days: 30, season: 'autumn', description: 'Mês de preparação para o inverno e frio crescente.' },
    { id: 'uktar', name: 'Uktar (O Apodrecimento)', days: 30, season: 'autumn', description: 'Folhas caídas e primeiras geadas noturnas.' },
    { id: 'feast_of_moon', name: 'Banquete da Lua (Festival Intercalar)', days: 1, season: 'winter', isIntercalary: true, description: 'Noite sagrada dedicada aos ancestrais e grandes feitos heróicos.' },
    { id: 'nightal', name: 'Nightal (O Retiro)', days: 30, season: 'winter', description: 'Noites longas, solstício de inverno e histórias ao redor da lareira.' },
  ],
  moons: [
    {
      id: 'selune',
      name: 'Selûne',
      cycleInDays: 30.43,
      phaseShiftDays: 0,
      color: '#f8fafc',
      tidalStrength: 'strong',
    },
  ],
  holidays: [
    { id: 'h_midwinter', name: 'Festival do Pleno Inverno', monthIndex: 1, day: 1, isRecurring: true, description: 'Feriado de renovação e alianças de inverno.' },
    { id: 'h_greengrass', name: 'Festival da Relvaverde', monthIndex: 5, day: 1, isRecurring: true, description: 'Flores são jogadas nos rios em honra a Chauntea e Sylvanus.' },
    { id: 'h_midsummer', name: 'Banquete do Pleno Verão', monthIndex: 9, day: 1, isRecurring: true, description: 'Casamentos reais, acordos de paz e festejos à meia-noite.' },
    { id: 'h_highharvest', name: 'Festa da Alta Colheita', monthIndex: 11, day: 1, isRecurring: true, description: 'Comemoração dos celeiros cheios e agradecimento da terra.' },
    { id: 'h_feastmoon', name: 'O Banquete da Lua', monthIndex: 15, day: 1, isRecurring: true, description: 'Contação de lendas e honras aos mortos com tochas acesas.' },
  ],
  startingYear: 1492,
  startingMonthIndex: 12, // Eleint
  startingDay: 14,
  startingHour: 10,
  startingMinute: 0,
};

export const GREYHAWK_CALENDAR: CampaignCalendarConfig = {
  id: 'greyhawk',
  presetKey: 'greyhawk',
  name: 'Calendário de Greyhawk (Flanaess)',
  yearSuffix: 'CY (Ano Comum)',
  daysOfWeek: [
    'Dia de Starday',
    'Dia de Sunday',
    'Dia de Moonday',
    'Dia de Godsday',
    'Dia de Waterday',
    'Dia de Earthday',
    'Dia de Freeday',
  ],
  hoursInDay: 24,
  minutesInHour: 60,
  months: [
    { id: 'needfest', name: 'Needlefest (Semana de Festival)', days: 7, season: 'winter', isIntercalary: true },
    { id: 'fireseek', name: 'Fireseek', days: 28, season: 'winter' },
    { id: 'readying', name: 'Readying', days: 28, season: 'spring' },
    { id: 'coldeven', name: 'Coldeven', days: 28, season: 'spring' },
    { id: 'growfest', name: 'Growfest (Semana de Festival)', days: 7, season: 'spring', isIntercalary: true },
    { id: 'planting', name: 'Planting', days: 28, season: 'spring' },
    { id: 'flocktime', name: 'Flocktime', days: 28, season: 'summer' },
    { id: 'wealsun', name: 'Wealsun', days: 28, season: 'summer' },
    { id: 'richfest', name: 'Richfest (Semana de Festival)', days: 7, season: 'summer', isIntercalary: true },
    { id: 'reaping', name: 'Reaping', days: 28, season: 'summer' },
    { id: 'goodmonth', name: 'Goodmonth', days: 28, season: 'autumn' },
    { id: 'harvester', name: 'Harvester', days: 28, season: 'autumn' },
    { id: 'brewfest', name: 'Brewfest (Semana de Festival)', days: 7, season: 'autumn', isIntercalary: true },
    { id: 'patchwall', name: 'Patchwall', days: 28, season: 'autumn' },
    { id: 'readyreat', name: 'Ready’reat', days: 28, season: 'winter' },
    { id: 'sunsebb', name: 'Sunsebb', days: 28, season: 'winter' },
  ],
  moons: [
    { id: 'luna', name: 'Luna (Lua Prateada)', cycleInDays: 28, phaseShiftDays: 0, color: '#fef08a', tidalStrength: 'strong' },
    { id: 'celene', name: 'Celene (Lua Aquamarina)', cycleInDays: 91, phaseShiftDays: 14, color: '#67e8f9', tidalStrength: 'moderate' },
  ],
  holidays: [
    { id: 'gh_growfest', name: 'Festival do Crescimento', monthIndex: 4, day: 1, isRecurring: true, description: 'Semana de canções para a fertilidade da terra.' },
    { id: 'gh_richfest', name: 'Festival da Riqueza', monthIndex: 8, day: 1, isRecurring: true, description: 'Dias de torneios e celebração do solstício.' },
    { id: 'gh_brewfest', name: 'Festival da Cerveja e Hidromel', monthIndex: 12, day: 1, isRecurring: true, description: 'A grande festa de degustação e banquetes das tavernas.' },
  ],
  startingYear: 591,
  startingMonthIndex: 1,
  startingDay: 1,
  startingHour: 8,
  startingMinute: 0,
};

export const GREGORIAN_CALENDAR: CampaignCalendarConfig = {
  id: 'gregorian',
  presetKey: 'gregorian',
  name: 'Calendário Padrão / Solar (12 Meses)',
  yearSuffix: 'AD / Era Atual',
  daysOfWeek: [
    'Segunda-feira',
    'Terça-feira',
    'Quarta-feira',
    'Quinta-feira',
    'Sexta-feira',
    'Sábado',
    'Domingo',
  ],
  hoursInDay: 24,
  minutesInHour: 60,
  months: [
    { id: 'jan', name: 'Janeiro', days: 31, season: 'summer' },
    { id: 'feb', name: 'Fevereiro', days: 28, season: 'summer' },
    { id: 'mar', name: 'Março', days: 31, season: 'autumn' },
    { id: 'apr', name: 'Abril', days: 30, season: 'autumn' },
    { id: 'may', name: 'Maio', days: 31, season: 'autumn' },
    { id: 'jun', name: 'Junho', days: 30, season: 'winter' },
    { id: 'jul', name: 'Julho', days: 31, season: 'winter' },
    { id: 'aug', name: 'Agosto', days: 31, season: 'winter' },
    { id: 'sep', name: 'Setembro', days: 30, season: 'spring' },
    { id: 'oct', name: 'Outubro', days: 31, season: 'spring' },
    { id: 'nov', name: 'Novembro', days: 30, season: 'spring' },
    { id: 'dec', name: 'Dezembro', days: 31, season: 'summer' },
  ],
  moons: [
    { id: 'luna_earth', name: 'Lua', cycleInDays: 29.53, phaseShiftDays: 0, color: '#f8fafc', tidalStrength: 'strong' },
  ],
  holidays: [
    { id: 'ano_novo', name: 'Ano Novo', monthIndex: 0, day: 1, isRecurring: true, description: 'Início de um novo ciclo anual.' },
    { id: 'solsticio_inverno', name: 'Solstício', monthIndex: 5, day: 21, isRecurring: true, description: 'Mudança de estação solar.' },
  ],
  startingYear: 1492,
  startingMonthIndex: 0,
  startingDay: 1,
  startingHour: 9,
  startingMinute: 0,
};

export const CALENDAR_PRESETS: Record<string, CampaignCalendarConfig> = {
  harptos: HARPTOS_CALENDAR,
  greyhawk: GREYHAWK_CALENDAR,
  gregorian: GREGORIAN_CALENDAR,
};

export const DEFAULT_CALENDAR_CONFIG = HARPTOS_CALENDAR;
